-- autogenerated lush spec on Sat 13 Jan 2024 04:40:51 PM CST
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    SpecialKey                                  { fg="#e8e8e8", bg="#182a2f", }, -- SpecialKey     xxx ctermfg=81 guifg=#e8e8e8 guibg=#182a2f
    TermCursor                                  { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    NonText                                     { fg="#404f53", gui="bold", }, -- NonText        xxx ctermfg=12 gui=bold guifg=#404f53
    EndOfBuffer                                 { NonText }, -- EndOfBuffer    xxx links to NonText
    Whitespace                                  { NonText }, -- Whitespace     xxx links to NonText
    TelescopePreviewHyphen                      { NonText }, -- TelescopePreviewHyphen xxx links to NonText
    TelescopePromptCounter                      { NonText }, -- TelescopePromptCounter xxx links to NonText
    TelescopeResultsDiffUntracked               { NonText }, -- TelescopeResultsDiffUntracked xxx links to NonText
    Directory                                   { fg="#2fb0ab", }, -- Directory      xxx ctermfg=159 guifg=#2fb0ab
    TelescopePreviewDirectory                   { Directory }, -- TelescopePreviewDirectory xxx links to Directory
    TelescopePreviewDate                        { Directory }, -- TelescopePreviewDate xxx links to Directory
    NvimTreeSymlinkFolderName                   { Directory }, -- NvimTreeSymlinkFolderName xxx links to Directory
    NvimTreeOpenedFolderName                    { Directory }, -- NvimTreeOpenedFolderName xxx links to Directory
    NvimTreeFolderName                          { Directory }, -- NvimTreeFolderName xxx links to Directory
    NvimTreeEmptyFolderName                     { Directory }, -- NvimTreeEmptyFolderName xxx links to Directory
    ErrorMsg                                    { fg="#ff0000", bg="#182a2f", gui="bold", }, -- ErrorMsg       xxx ctermfg=15 ctermbg=1 gui=bold guifg=#ff0000 guibg=#182a2f
    NvimInvalidSpacing                          { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    IncSearch                                   { fg="#04171d", bg="#d13434", gui="reverse", }, -- IncSearch      xxx cterm=reverse gui=reverse guifg=#04171d guibg=#d13434
    Search                                      { fg="black", bg="yellow", gui="underline", }, -- Search         xxx ctermfg=0 ctermbg=11 gui=underline guifg=Black guibg=Yellow
    CurSearch                                   { Search }, -- CurSearch      xxx links to Search
    QuickFixLine                                { Search }, -- QuickFixLine   xxx links to Search
    Substitute                                  { Search }, -- Substitute     xxx links to Search
    TelescopePreviewMatch                       { Search }, -- TelescopePreviewMatch xxx links to Search
    MoreMsg                                     { fg="seagreen", gui="bold", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
    ModeMsg                                     { gui="bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    LineNr                                      { fg="#e8e8e8", bg="#182a2f", }, -- LineNr         xxx ctermfg=11 guifg=#e8e8e8 guibg=#182a2f
    LineNrAbove                                 { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                                 { LineNr }, -- LineNrBelow    xxx links to LineNr
    TelescopeResultsLineNr                      { LineNr }, -- TelescopeResultsLineNr xxx links to LineNr
    NvimTreeLineNr                              { LineNr }, -- NvimTreeLineNr xxx links to LineNr
    CursorLineNr                                { fg="#fcfcfc", bg="#182a2f", gui="bold", }, -- CursorLineNr   xxx cterm=underline ctermfg=11 gui=bold guifg=#fcfcfc guibg=#182a2f
    NvimTreeCursorLineNr                        { CursorLineNr }, -- NvimTreeCursorLineNr xxx links to CursorLineNr
    Question                                    { fg="green", gui="bold", }, -- Question       xxx ctermfg=121 gui=bold guifg=Green
    StatusLine                                  { fg="#e8e8e8", bg="#2c3c41", gui="bold", }, -- StatusLine     xxx cterm=bold,reverse gui=bold guifg=#e8e8e8 guibg=#2c3c41
    MsgSeparator                                { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    NvimTreeStatusLine                          { StatusLine }, -- NvimTreeStatusLine xxx links to StatusLine
    StatusLineNC                                { gui="reverse", }, -- StatusLineNC   xxx cterm=reverse gui=reverse
    NvimTreeStatusLineNC                        { StatusLineNC }, -- NvimTreeStatusLineNC xxx links to StatusLineNC
    VertSplit                                   { fg="#d4d4d4", bg="#2c3c41", }, -- VertSplit      xxx guifg=#d4d4d4 guibg=#2c3c41
    WinSeparator                                { VertSplit }, -- WinSeparator   xxx links to VertSplit
    Title                                       { fg="#fcfcfc", gui="bold", }, -- Title          xxx ctermfg=225 gui=bold guifg=#fcfcfc
    FloatTitle                                  { Title }, -- FloatTitle     xxx links to Title
    sym"@text.title"                            { Title }, -- @text.title    xxx links to Title
    LspInfoTitle                                { Title }, -- LspInfoTitle   xxx links to Title
    Visual                                      { bg="darkgrey", }, -- Visual         xxx ctermbg=242 guibg=DarkGrey
    TelescopePreviewLine                        { Visual }, -- TelescopePreviewLine xxx links to Visual
    TelescopeSelection                          { Visual }, -- TelescopeSelection xxx links to Visual
    WarningMsg                                  { fg="#fcfcfc", bg="#ff8800", }, -- WarningMsg     xxx ctermfg=224 guifg=#fcfcfc guibg=#ff8800
    WildMenu                                    { fg="#6ab791", bg="#04171d", }, -- WildMenu       xxx ctermfg=0 ctermbg=11 guifg=#6ab791 guibg=#04171d
    Folded                                      { fg="#c0c0c0", bg="#04171d", }, -- Folded         xxx ctermfg=14 ctermbg=242 guifg=#c0c0c0 guibg=#04171d
    FoldColumn                                  { fg="#f3f2e7", bg="#182a2f", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=#f3f2e7 guibg=#182a2f
    CursorLineFold                              { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                     { fg="#fafafa", bg="#123d0f", gui="bold", }, -- DiffAdd        xxx ctermbg=4 gui=bold guifg=#fafafa guibg=#123d0f
    TelescopeResultsDiffAdd                     { DiffAdd }, -- TelescopeResultsDiffAdd xxx links to DiffAdd
    DiffChange                                  { fg="#fafafa", bg="#151b3c", }, -- DiffChange     xxx ctermbg=5 guifg=#fafafa guibg=#151b3c
    TelescopeResultsDiffChange                  { DiffChange }, -- TelescopeResultsDiffChange xxx links to DiffChange
    DiffDelete                                  { fg="blue", bg="#182a2f", gui="bold", }, -- DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=Blue guibg=#182a2f
    TelescopeResultsDiffDelete                  { DiffDelete }, -- TelescopeResultsDiffDelete xxx links to DiffDelete
    DiffText                                    { fg="#ffffff", bg="#ff0000", gui="bold", }, -- DiffText       xxx cterm=bold ctermbg=9 gui=bold guifg=#ffffff guibg=#ff0000
    SignColumn                                  { fg="#f3f2e7", bg="#182a2f", }, -- SignColumn     xxx ctermfg=14 ctermbg=242 guifg=#f3f2e7 guibg=#182a2f
    CursorLineSign                              { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Conceal                                     { fg="lightgrey", bg="darkgrey", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
    SpellBad                                    { sp="red", gui="undercurl", }, -- SpellBad       xxx ctermbg=9 gui=undercurl guisp=Red
    NvimTreeCutHL                               { SpellBad }, -- NvimTreeCutHL  xxx links to SpellBad
    SpellCap                                    { sp="blue", gui="undercurl", }, -- SpellCap       xxx ctermbg=12 gui=undercurl guisp=Blue
    SpellRare                                   { sp="magenta", gui="undercurl", }, -- SpellRare      xxx ctermbg=13 gui=undercurl guisp=Magenta
    NvimTreeCopiedHL                            { SpellRare }, -- NvimTreeCopiedHL xxx links to SpellRare
    SpellLocal                                  { sp="cyan", gui="undercurl", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
    NvimTreeBookmarkHL                          { SpellLocal }, -- NvimTreeBookmarkHL xxx links to SpellLocal
    Pmenu                                       { fg="#fcfcfc", bg="#182a2f", }, -- Pmenu          xxx ctermfg=0 ctermbg=13 guifg=#fcfcfc guibg=#182a2f
    PmenuKind                                   { Pmenu }, -- PmenuKind      xxx links to Pmenu
    PmenuExtra                                  { Pmenu }, -- PmenuExtra     xxx links to Pmenu
    NormalFloat                                 { Pmenu }, -- NormalFloat    xxx links to Pmenu
    PmenuSel                                    { bg="#2c3c41", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guibg=#2c3c41
    PmenuKindSel                                { PmenuSel }, -- PmenuKindSel   xxx links to PmenuSel
    PmenuExtraSel                               { PmenuSel }, -- PmenuExtraSel  xxx links to PmenuSel
    PmenuSbar                                   { bg="grey", }, -- PmenuSbar      xxx ctermbg=248 guibg=Grey
    PmenuThumb                                  { bg="white", }, -- PmenuThumb     xxx ctermbg=15 guibg=White
    TabLine                                     { gui="underline", bg="darkgrey", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 gui=underline guibg=DarkGrey
    TabLineSel                                  { gui="bold", }, -- TabLineSel     xxx cterm=bold gui=bold
    TabLineFill                                 { gui="reverse", }, -- TabLineFill    xxx cterm=reverse gui=reverse
    CursorColumn                                { bg="#182a2f", }, -- CursorColumn   xxx ctermbg=242 guibg=#182a2f
    NvimTreeCursorColumn                        { CursorColumn }, -- NvimTreeCursorColumn xxx links to CursorColumn
    CursorLine                                  { bg="#182a2f", }, -- CursorLine     xxx cterm=underline guibg=#182a2f
    NvimTreeCursorLine                          { CursorLine }, -- NvimTreeCursorLine xxx links to CursorLine
    ColorColumn                                 { bg="#182a2f", }, -- ColorColumn    xxx ctermbg=1 guibg=#182a2f
    WinBar                                      { gui="bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC                                    { WinBar }, -- WinBarNC       xxx links to WinBar
    Cursor                                      { fg="#04171d", bg="#fcfcfc", }, -- Cursor         xxx guifg=#04171d guibg=#fcfcfc
    lCursor                                     { fg="#04171d", bg="#fcfcfc", }, -- lCursor        xxx guifg=bg guibg=fg
    Normal                                      { fg="#fcfcfc", }, -- Normal         xxx guifg=#fcfcfc
    NvimSpacing                                 { Normal }, -- NvimSpacing    xxx links to Normal
    TelescopeNormal                             { Normal }, -- TelescopeNormal xxx links to Normal
    NvimTreeNormal                              { Normal }, -- NvimTreeNormal xxx links to Normal
    NvimTreePopup                               { Normal }, -- NvimTreePopup  xxx links to Normal
    DapUINormal                                 { Normal }, -- DapUINormal    xxx links to Normal
    DapUIVariable                               { Normal }, -- DapUIVariable  xxx links to Normal
    DapUIValue                                  { Normal }, -- DapUIValue     xxx links to Normal
    DapUIFrameName                              { Normal }, -- DapUIFrameName xxx links to Normal
    FloatShadow                                 { blend=80, bg="black", }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                          { blend=100, bg="black", }, -- FloatShadowThrough xxx guibg=Black blend=100
    RedrawDebugNormal                           { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                            { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                         { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                        { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                       { fg="white", bg="red", }, -- Error          xxx ctermfg=15 ctermbg=9 guifg=White guibg=Red
    NvimInvalid                                 { Error }, -- NvimInvalid    xxx links to Error
    luaParenError                               { Error }, -- luaParenError  xxx links to Error
    luaError                                    { Error }, -- luaError       xxx links to Error
    Todo                                        { fg="#e8e8e8", bg="#04171d", gui="bold,reverse", }, -- Todo           xxx ctermfg=0 ctermbg=11 gui=bold,reverse guifg=#e8e8e8 guibg=#04171d
    sym"@text.todo"                             { Todo }, -- @text.todo     xxx links to Todo
    luaTodo                                     { Todo }, -- luaTodo        xxx links to Todo
    String                                      { fg="#6ab791", }, -- String         xxx guifg=#6ab791
    sym"@string"                                { String }, -- @string        xxx links to String
    NvimString                                  { String }, -- NvimString     xxx links to String
    TelescopePreviewSize                        { String }, -- TelescopePreviewSize xxx links to String
    TelescopePreviewExecute                     { String }, -- TelescopePreviewExecute xxx links to String
    luaString2                                  { String }, -- luaString2     xxx links to String
    luaString                                   { String }, -- luaString      xxx links to String
    Constant                                    { fg="#2fb0ab", }, -- Constant       xxx ctermfg=13 guifg=#2fb0ab
    sym"@constant"                              { Constant }, -- @constant      xxx links to Constant
    sym"@lsp.type.enumMember"                   { Constant }, -- @lsp.type.enumMember xxx links to Constant
    TelescopePreviewGroup                       { Constant }, -- TelescopePreviewGroup xxx links to Constant
    TelescopePreviewUser                        { Constant }, -- TelescopePreviewUser xxx links to Constant
    TelescopePreviewRead                        { Constant }, -- TelescopePreviewRead xxx links to Constant
    TelescopePreviewBlock                       { Constant }, -- TelescopePreviewBlock xxx links to Constant
    TelescopePreviewCharDev                     { Constant }, -- TelescopePreviewCharDev xxx links to Constant
    TelescopePreviewPipe                        { Constant }, -- TelescopePreviewPipe xxx links to Constant
    TelescopeResultsConstant                    { Constant }, -- TelescopeResultsConstant xxx links to Constant
    luaConstant                                 { Constant }, -- luaConstant    xxx links to Constant
    Character                                   { fg="#2fb0ab", }, -- Character      xxx guifg=#2fb0ab
    sym"@character"                             { Character }, -- @character     xxx links to Character
    Number                                      { fg="#2fb0ab", }, -- Number         xxx guifg=#2fb0ab
    sym"@number"                                { Number }, -- @number        xxx links to Number
    NvimNumber                                  { Number }, -- NvimNumber     xxx links to Number
    TelescopeResultsNumber                      { Number }, -- TelescopeResultsNumber xxx links to Number
    luaNumber                                   { Number }, -- luaNumber      xxx links to Number
    Boolean                                     { fg="#2fb0ab", }, -- Boolean        xxx guifg=#2fb0ab
    sym"@boolean"                               { Boolean }, -- @boolean       xxx links to Boolean
    Float                                       { fg="#2fb0ab", }, -- Float          xxx guifg=#2fb0ab
    sym"@float"                                 { Float }, -- @float         xxx links to Float
    Function                                    { fg="#7f705b", }, -- Function       xxx guifg=#7f705b
    sym"@function"                              { Function }, -- @function      xxx links to Function
    sym"@method"                                { Function }, -- @method        xxx links to Function
    sym"@lsp.type.decorator"                    { Function }, -- @lsp.type.decorator xxx links to Function
    sym"@lsp.type.function"                     { Function }, -- @lsp.type.function xxx links to Function
    sym"@lsp.type.method"                       { Function }, -- @lsp.type.method xxx links to Function
    TelescopeResultsFunction                    { Function }, -- TelescopeResultsFunction xxx links to Function
    TelescopeResultsField                       { Function }, -- TelescopeResultsField xxx links to Function
    TelescopeResultsClass                       { Function }, -- TelescopeResultsClass xxx links to Function
    LspInfoList                                 { Function }, -- LspInfoList    xxx links to Function
    luaMetaMethod                               { Function }, -- luaMetaMethod  xxx links to Function
    luaFunction                                 { Function }, -- luaFunction    xxx links to Function
    Identifier                                  { fg="#ff5879", gui="italic", }, -- Identifier     xxx cterm=bold ctermfg=14 gui=italic guifg=#ff5879
    sym"@text.reference"                        { Identifier }, -- @text.reference xxx links to Identifier
    sym"@parameter"                             { Identifier }, -- @parameter     xxx links to Identifier
    sym"@field"                                 { Identifier }, -- @field         xxx links to Identifier
    sym"@property"                              { Identifier }, -- @property      xxx links to Identifier
    sym"@variable"                              { Identifier }, -- @variable      xxx links to Identifier
    sym"@namespace"                             { Identifier }, -- @namespace     xxx links to Identifier
    sym"@lsp.type.parameter"                    { Identifier }, -- @lsp.type.parameter xxx links to Identifier
    sym"@lsp.type.property"                     { Identifier }, -- @lsp.type.property xxx links to Identifier
    sym"@lsp.type.variable"                     { Identifier }, -- @lsp.type.variable xxx links to Identifier
    NvimIdentifier                              { Identifier }, -- NvimIdentifier xxx links to Identifier
    TelescopePromptPrefix                       { Identifier }, -- TelescopePromptPrefix xxx links to Identifier
    TelescopeMultiIcon                          { Identifier }, -- TelescopeMultiIcon xxx links to Identifier
    TelescopeResultsIdentifier                  { Identifier }, -- TelescopeResultsIdentifier xxx links to Identifier
    luaFunc                                     { Identifier }, -- luaFunc        xxx links to Identifier
    Conditional                                 { fg="#d13434", }, -- Conditional    xxx guifg=#d13434
    sym"@conditional"                           { Conditional }, -- @conditional   xxx links to Conditional
    luaCondElse                                 { Conditional }, -- luaCondElse    xxx links to Conditional
    luaCond                                     { Conditional }, -- luaCond        xxx links to Conditional
    Statement                                   { fg="#d13434", gui="bold", }, -- Statement      xxx ctermfg=11 gui=bold guifg=#d13434
    Repeat                                      { Statement }, -- Repeat         xxx links to Statement
    Exception                                   { Statement }, -- Exception      xxx links to Statement
    TelescopePreviewWrite                       { Statement }, -- TelescopePreviewWrite xxx links to Statement
    TelescopePreviewSocket                      { Statement }, -- TelescopePreviewSocket xxx links to Statement
    luaStatement                                { Statement }, -- luaStatement   xxx links to Statement
    Label                                       { fg="#1697b1", }, -- Label          xxx guifg=#1697b1
    sym"@label"                                 { Label }, -- @label         xxx links to Label
    LspInfoBorder                               { Label }, -- LspInfoBorder  xxx links to Label
    luaLabel                                    { Label }, -- luaLabel       xxx links to Label
    Operator                                    { fg="#d13434", }, -- Operator       xxx guifg=#d13434
    sym"@operator"                              { Operator }, -- @operator      xxx links to Operator
    NvimAssignment                              { Operator }, -- NvimAssignment xxx links to Operator
    NvimOperator                                { Operator }, -- NvimOperator   xxx links to Operator
    TelescopeResultsOperator                    { Operator }, -- TelescopeResultsOperator xxx links to Operator
    luaOperator                                 { Operator }, -- luaOperator    xxx links to Operator
    Keyword                                     { fg="#d13434", gui="bold", }, -- Keyword        xxx gui=bold guifg=#d13434
    sym"@keyword"                               { Keyword }, -- @keyword       xxx links to Keyword
    TelescopePreviewSticky                      { Keyword }, -- TelescopePreviewSticky xxx links to Keyword
    PreProc                                     { fg="#d13434", }, -- PreProc        xxx ctermfg=81 guifg=#d13434
    Include                                     { PreProc }, -- Include        xxx links to PreProc
    Macro                                       { PreProc }, -- Macro          xxx links to PreProc
    PreCondit                                   { PreProc }, -- PreCondit      xxx links to PreProc
    sym"@preproc"                               { PreProc }, -- @preproc       xxx links to PreProc
    Define                                      { fg="#d13434", }, -- Define         xxx guifg=#d13434
    sym"@constant.macro"                        { Define }, -- @constant.macro xxx links to Define
    sym"@define"                                { Define }, -- @define        xxx links to Define
    StorageClass                                { fg="#ff5879", gui="italic", }, -- StorageClass   xxx gui=italic guifg=#ff5879
    sym"@storageclass"                          { StorageClass }, -- @storageclass  xxx links to StorageClass
    Type                                        { fg="#ff5879", gui="bold", }, -- Type           xxx ctermfg=121 gui=bold guifg=#ff5879
    Structure                                   { Type }, -- Structure      xxx links to Type
    Typedef                                     { Type }, -- Typedef        xxx links to Type
    sym"@type"                                  { Type }, -- @type          xxx links to Type
    sym"@lsp.type.type"                         { Type }, -- @lsp.type.type xxx links to Type
    NvimNumberPrefix                            { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                             { Type }, -- NvimOptionSigil xxx links to Type
    TelescopeMultiSelection                     { Type }, -- TelescopeMultiSelection xxx links to Type
    LspInfoFiletype                             { Type }, -- LspInfoFiletype xxx links to Type
    Tag                                         { fg="#d13434", }, -- Tag            xxx guifg=#d13434
    sym"@tag"                                   { Tag }, -- @tag           xxx links to Tag
    Special                                     { fg="#fcfcfc", }, -- Special        xxx ctermfg=224 guifg=#fcfcfc
    SpecialChar                                 { Special }, -- SpecialChar    xxx links to Special
    Delimiter                                   { Special }, -- Delimiter      xxx links to Special
    SpecialComment                              { Special }, -- SpecialComment xxx links to Special
    Debug                                       { Special }, -- Debug          xxx links to Special
    sym"@constant.builtin"                      { Special }, -- @constant.builtin xxx links to Special
    sym"@function.builtin"                      { Special }, -- @function.builtin xxx links to Special
    sym"@constructor"                           { Special }, -- @constructor   xxx links to Special
    TelescopePreviewLink                        { Special }, -- TelescopePreviewLink xxx links to Special
    TelescopeMatching                           { Special }, -- TelescopeMatching xxx links to Special
    DiagnosticError                             { fg="red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticVirtualTextError                  { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticFloatingError                     { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticSignError                         { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    NvimTreeLspDiagnosticsError                 { DiagnosticError }, -- NvimTreeLspDiagnosticsError xxx links to DiagnosticError
    DiagnosticWarn                              { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticVirtualTextWarn                   { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticFloatingWarn                      { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                          { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    NvimTreeLspDiagnosticsWarning               { DiagnosticWarn }, -- NvimTreeLspDiagnosticsWarning xxx links to DiagnosticWarn
    DiagnosticInfo                              { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticVirtualTextInfo                   { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticFloatingInfo                      { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                          { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    NvimTreeLspDiagnosticsInformation           { DiagnosticInfo }, -- NvimTreeLspDiagnosticsInformation xxx links to DiagnosticInfo
    DiagnosticHint                              { fg="lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticVirtualTextHint                   { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticFloatingHint                      { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticSignHint                          { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    NvimTreeLspDiagnosticsHint                  { DiagnosticHint }, -- NvimTreeLspDiagnosticsHint xxx links to DiagnosticHint
    DiagnosticOk                                { fg="lightgreen", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticVirtualTextOk                     { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticFloatingOk                        { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticSignOk                            { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    DiagnosticUnderlineError                    { sp="red", gui="underline", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                     { sp="orange", gui="underline", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                     { sp="lightblue", gui="underline", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                     { sp="lightgrey", gui="underline", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    DiagnosticUnderlineOk                       { sp="lightgreen", gui="underline", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    DiagnosticDeprecated                        { sp="red", gui="strikethrough", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    Comment                                     { fg="#f3f2e7", }, -- Comment        xxx ctermfg=14 guifg=#f3f2e7
    DiagnosticUnnecessary                       { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@text.literal"                          { Comment }, -- @text.literal  xxx links to Comment
    sym"@comment"                               { Comment }, -- @comment       xxx links to Comment
    sym"@lsp.type.comment"                      { Comment }, -- @lsp.type.comment xxx links to Comment
    TelescopeResultsComment                     { Comment }, -- TelescopeResultsComment xxx links to Comment
    LspInfoTip                                  { Comment }, -- LspInfoTip     xxx links to Comment
    NvimTreeGitIgnored                          { Comment }, -- NvimTreeGitIgnored xxx links to Comment
    luaComment                                  { Comment }, -- luaComment     xxx links to Comment
    Underlined                                  { fg="#80a0ff", gui="underline", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#80a0ff
    sym"@text.uri"                              { Underlined }, -- @text.uri      xxx links to Underlined
    sym"@text.underline"                        { Underlined }, -- @text.underline xxx links to Underlined
    MatchParen                                  { fg="#ff8800", bg="darkcyan", gui="underline", }, -- MatchParen     xxx ctermbg=6 gui=underline guifg=#ff8800 guibg=DarkCyan
    Ignore                                      { fg="#04171d", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                           { fg="red", bg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                             { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape               { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape        { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    CmpItemAbbrDefault                          { fg="#fcfcfc", }, -- CmpItemAbbrDefault xxx guifg=#fcfcfc
    CmpItemAbbr                                 { CmpItemAbbrDefault }, -- CmpItemAbbr    xxx links to CmpItemAbbrDefault
    CmpItemAbbrDeprecatedDefault                { fg="#f3f2e7", }, -- CmpItemAbbrDeprecatedDefault xxx guifg=#f3f2e7
    CmpItemAbbrDeprecated                       { CmpItemAbbrDeprecatedDefault }, -- CmpItemAbbrDeprecated xxx links to CmpItemAbbrDeprecatedDefault
    CmpItemAbbrMatchDefault                     { fg="#fcfcfc", }, -- CmpItemAbbrMatchDefault xxx guifg=#fcfcfc
    CmpItemAbbrMatch                            { CmpItemAbbrMatchDefault }, -- CmpItemAbbrMatch xxx links to CmpItemAbbrMatchDefault
    CmpItemAbbrMatchFuzzyDefault                { fg="#fcfcfc", }, -- CmpItemAbbrMatchFuzzyDefault xxx guifg=#fcfcfc
    CmpItemAbbrMatchFuzzy                       { CmpItemAbbrMatchFuzzyDefault }, -- CmpItemAbbrMatchFuzzy xxx links to CmpItemAbbrMatchFuzzyDefault
    CmpItemKindDefault                          { fg="#fcfcfc", }, -- CmpItemKindDefault xxx guifg=#fcfcfc
    CmpItemKind                                 { CmpItemKindDefault }, -- CmpItemKind    xxx links to CmpItemKindDefault
    CmpItemMenuDefault                          { fg="#fcfcfc", }, -- CmpItemMenuDefault xxx guifg=#fcfcfc
    CmpItemMenu                                 { CmpItemMenuDefault }, -- CmpItemMenu    xxx links to CmpItemMenuDefault
    rubyAttribute                               { fg="#032c36", }, -- rubyAttribute  xxx guifg=#032c36
    rubyLocalVariableOrMethod                   { fg="#1697b1", }, -- rubyLocalVariableOrMethod xxx guifg=#1697b1
    rubyGlobalVariable                          { fg="#1697b1", gui="italic", }, -- rubyGlobalVariable xxx gui=italic guifg=#1697b1
    rubyInstanceVariable                        { fg="#1697b1", }, -- rubyInstanceVariable xxx guifg=#1697b1
    rubyKeyword                                 { fg="#d13434", }, -- rubyKeyword    xxx guifg=#d13434
    rubyKeywordAsMethod                         { fg="#d13434", gui="bold", }, -- rubyKeywordAsMethod xxx gui=bold guifg=#d13434
    rubyClassDeclaration                        { fg="#d13434", gui="bold", }, -- rubyClassDeclaration xxx gui=bold guifg=#d13434
    rubyClass                                   { fg="#d13434", gui="bold", }, -- rubyClass      xxx gui=bold guifg=#d13434
    rubyNumber                                  { fg="#2fb0ab", }, -- rubyNumber     xxx guifg=#2fb0ab
    pythonBuiltinFunc                           { fg="#032c36", }, -- pythonBuiltinFunc xxx guifg=#032c36
    goBuiltins                                  { fg="#032c36", }, -- goBuiltins     xxx guifg=#032c36
    jsBuiltins                                  { fg="#032c36", }, -- jsBuiltins     xxx guifg=#032c36
    jsFunction                                  { fg="#d13434", gui="bold", }, -- jsFunction     xxx gui=bold guifg=#d13434
    jsGlobalObjects                             { fg="#ff5879", }, -- jsGlobalObjects xxx guifg=#ff5879
    jsAssignmentExps                            { fg="#1697b1", }, -- jsAssignmentExps xxx guifg=#1697b1
    htmlLink                                    { fg="#1697b1", gui="underline", }, -- htmlLink       xxx gui=underline guifg=#1697b1
    htmlStatement                               { fg="#d13434", }, -- htmlStatement  xxx guifg=#d13434
    htmlSpecialTagName                          { fg="#d13434", }, -- htmlSpecialTagName xxx guifg=#d13434
    mkdCode                                     { fg="#032c36", }, -- mkdCode        xxx guifg=#032c36
    NvimTreeExecFile                            { fg="#d13434", gui="bold", }, -- NvimTreeExecFile xxx gui=bold guifg=#d13434
    NvimTreeRootFolder                          { fg="#032c36", }, -- NvimTreeRootFolder xxx guifg=#032c36
    NvimTreeFolderIcon                          { fg="#8094b4", }, -- NvimTreeFolderIcon xxx guifg=#8094b4
    NvimTreeClosedFolderIcon                    { NvimTreeFolderIcon }, -- NvimTreeClosedFolderIcon xxx links to NvimTreeFolderIcon
    NvimTreeOpenedFolderIcon                    { NvimTreeFolderIcon }, -- NvimTreeOpenedFolderIcon xxx links to NvimTreeFolderIcon
    NvimTreeSymlink                             { fg="#d4d4d4", gui="bold", }, -- NvimTreeSymlink xxx gui=bold guifg=#d4d4d4
    NvimTreeIndentMarker                        { fg="#8094b4", }, -- NvimTreeIndentMarker xxx guifg=#8094b4
    NvimTreeBookmark                            { fg="#d13434", }, -- NvimTreeBookmark xxx guifg=#d13434
    NvimTreeLiveFilterValue                     { gui="bold", }, -- NvimTreeLiveFilterValue xxx gui=bold
    NvimTreeLiveFilterPrefix                    { fg="#032c36", gui="bold", }, -- NvimTreeLiveFilterPrefix xxx gui=bold guifg=#032c36
    NvimTreeWindowPicker                        { fg="#ededed", bg="#4493c8", gui="bold", }, -- NvimTreeWindowPicker xxx gui=bold guifg=#ededed guibg=#4493c8
    NvimTreeGitNew                              { fg="#404f53", }, -- NvimTreeGitNew xxx guifg=#404f53
    NvimTreeFileNew                             { NvimTreeGitNew }, -- NvimTreeFileNew xxx links to NvimTreeGitNew
    NvimTreeGitRenamed                          { fg="#032c36", }, -- NvimTreeGitRenamed xxx guifg=#032c36
    NvimTreeFileRenamed                         { NvimTreeGitRenamed }, -- NvimTreeFileRenamed xxx links to NvimTreeGitRenamed
    NvimTreeGitMerge                            { fg="#1697b1", }, -- NvimTreeGitMerge xxx guifg=#1697b1
    NvimTreeFileMerge                           { NvimTreeGitMerge }, -- NvimTreeFileMerge xxx links to NvimTreeGitMerge
    NvimTreeGitStaged                           { fg="#d13434", }, -- NvimTreeGitStaged xxx guifg=#d13434
    NvimTreeFileStaged                          { NvimTreeGitStaged }, -- NvimTreeFileStaged xxx links to NvimTreeGitStaged
    NvimTreeGitDeleted                          { fg="#ff8800", }, -- NvimTreeGitDeleted xxx guifg=#ff8800
    NvimTreeFileDeleted                         { NvimTreeGitDeleted }, -- NvimTreeFileDeleted xxx links to NvimTreeGitDeleted
    NvimTreeGitDirty                            { fg="#ff8800", }, -- NvimTreeGitDirty xxx guifg=#ff8800
    NvimTreeFileDirty                           { NvimTreeGitDirty }, -- NvimTreeFileDirty xxx links to NvimTreeGitDirty
    NvimTreeModifiedFile                        { fg="#d13434", }, -- NvimTreeModifiedFile xxx guifg=#d13434
    NvimTreeOpenedFile                          { fg="#d13434", gui="bold", }, -- NvimTreeOpenedFile xxx gui=bold guifg=#d13434
    NvimTreeOpenedFileIcon                      { NvimTreeOpenedFile }, -- NvimTreeOpenedFileIcon xxx links to NvimTreeOpenedFile
    NvimTreeImageFile                           { fg="#032c36", gui="bold", }, -- NvimTreeImageFile xxx gui=bold guifg=#032c36
    NvimTreeSpecialFile                         { fg="#404f53", gui="bold,underline", }, -- NvimTreeSpecialFile xxx gui=bold,underline guifg=#404f53
    DevIconHrl                                  { fg="#b83998", }, -- DevIconHrl     xxx ctermfg=163 guifg=#b83998
    DevIconEpp                                  { fg="#ffa61a", }, -- DevIconEpp     xxx ctermfg=214 guifg=#ffa61a
    DevIconElm                                  { fg="#519aba", }, -- DevIconElm     xxx ctermfg=74 guifg=#519aba
    DevIconCobol                                { fg="#005ca5", }, -- DevIconCobol   xxx ctermfg=25 guifg=#005ca5
    DevIconOpenBSD                              { fg="#000000", }, -- DevIconOpenBSD xxx ctermfg=16 guifg=#000000
    DevIconLhs                                  { fg="#a074c4", }, -- DevIconLhs     xxx ctermfg=140 guifg=#a074c4
    DevIconKotlinScript                         { fg="#7f52ff", }, -- DevIconKotlinScript xxx ctermfg=99 guifg=#7f52ff
    DevIconCxx                                  { fg="#519aba", }, -- DevIconCxx     xxx ctermfg=74 guifg=#519aba
    DevIconCss                                  { fg="#42a5f5", }, -- DevIconCss     xxx ctermfg=75 guifg=#42a5f5
    DevIconCs                                   { fg="#596706", }, -- DevIconCs      xxx ctermfg=58 guifg=#596706
    DevIconPm                                   { fg="#519aba", }, -- DevIconPm      xxx ctermfg=74 guifg=#519aba
    DevIconWebmanifest                          { fg="#f1e05a", }, -- DevIconWebmanifest xxx ctermfg=185 guifg=#f1e05a
    DevIconCrystal                              { fg="#c8c8c8", }, -- DevIconCrystal xxx ctermfg=251 guifg=#c8c8c8
    DevIconSh                                   { fg="#4d5a5e", }, -- DevIconSh      xxx ctermfg=240 guifg=#4d5a5e
    DevIconCpp                                  { fg="#519aba", }, -- DevIconCpp     xxx ctermfg=74 guifg=#519aba
    DevIconCoffee                               { fg="#cbcb41", }, -- DevIconCoffee  xxx ctermfg=185 guifg=#cbcb41
    DevIconBzl                                  { fg="#89e051", }, -- DevIconBzl     xxx ctermfg=113 guifg=#89e051
    DevIconClojureJS                            { fg="#519aba", }, -- DevIconClojureJS xxx ctermfg=74 guifg=#519aba
    DevIconVHDL                                 { fg="#019833", }, -- DevIconVHDL    xxx ctermfg=28 guifg=#019833
    DevIconCjs                                  { fg="#f1f134", }, -- DevIconCjs     xxx ctermfg=227 guifg=#f1f134
    DevIconClojure                              { fg="#8dc149", }, -- DevIconClojure xxx ctermfg=113 guifg=#8dc149
    DevIconHuff                                 { fg="#4242c7", }, -- DevIconHuff    xxx ctermfg=56 guifg=#4242c7
    DevIconConfiguration                        { fg="#ececec", }, -- DevIconConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconCPlusPlus                            { fg="#f34b7d", }, -- DevIconCPlusPlus xxx ctermfg=204 guifg=#f34b7d
    DevIconTrueTypeFont                         { fg="#ececec", }, -- DevIconTrueTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconConfigRu                             { fg="#701516", }, -- DevIconConfigRu xxx ctermfg=52 guifg=#701516
    DevIconBash                                 { fg="#89e051", }, -- DevIconBash    xxx ctermfg=113 guifg=#89e051
    DevIconAppleScript                          { fg="#6d8085", }, -- DevIconAppleScript xxx ctermfg=66 guifg=#6d8085
    DevIconClojureDart                          { fg="#519aba", }, -- DevIconClojureDart xxx ctermfg=74 guifg=#519aba
    DevIconTs                                   { fg="#519aba", }, -- DevIconTs      xxx ctermfg=74 guifg=#519aba
    DevIconPyx                                  { fg="#5aa7e4", }, -- DevIconPyx     xxx ctermfg=39 guifg=#5aa7e4
    DevIconToml                                 { fg="#ffffff", }, -- DevIconToml    xxx ctermfg=231 guifg=#ffffff
    DevIconBazelWorkspace                       { fg="#89e051", }, -- DevIconBazelWorkspace xxx ctermfg=113 guifg=#89e051
    DevIconCts                                  { fg="#519aba", }, -- DevIconCts     xxx ctermfg=74 guifg=#519aba
    DevIconDump                                 { fg="#dad8d8", }, -- DevIconDump    xxx ctermfg=188 guifg=#dad8d8
    DevIconTcl                                  { fg="#1e5cb3", }, -- DevIconTcl     xxx ctermfg=25 guifg=#1e5cb3
    DevIconTypeScriptReactTest                  { fg="#1354bf", }, -- DevIconTypeScriptReactTest xxx ctermfg=26 guifg=#1354bf
    DevIconTwig                                 { fg="#8dc149", }, -- DevIconTwig    xxx ctermfg=113 guifg=#8dc149
    DevIconHeex                                 { fg="#a074c4", }, -- DevIconHeex    xxx ctermfg=140 guifg=#a074c4
    DevIconSystemVerilog                        { fg="#019833", }, -- DevIconSystemVerilog xxx ctermfg=28 guifg=#019833
    DevIconAzureCli                             { fg="#0078d4", }, -- DevIconAzureCli xxx ctermfg=32 guifg=#0078d4
    DevIconTailwindConfig                       { fg="#20c2e3", }, -- DevIconTailwindConfig xxx ctermfg=45 guifg=#20c2e3
    DevIconTestJs                               { fg="#cbcb41", }, -- DevIconTestJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconSvg                                  { fg="#ffb13b", }, -- DevIconSvg     xxx ctermfg=214 guifg=#ffb13b
    DevIconSvelte                               { fg="#ff3e00", }, -- DevIconSvelte  xxx ctermfg=196 guifg=#ff3e00
    DevIconApp                                  { fg="#9f0500", }, -- DevIconApp     xxx ctermfg=124 guifg=#9f0500
    DevIconSql                                  { fg="#dad8d8", }, -- DevIconSql     xxx ctermfg=188 guifg=#dad8d8
    DevIconPrisma                               { fg="#ffffff", }, -- DevIconPrisma  xxx ctermfg=231 guifg=#ffffff
    DevIconTFVars                               { fg="#5f43e9", }, -- DevIconTFVars  xxx ctermfg=93 guifg=#5f43e9
    DevIconExe                                  { fg="#9f0500", }, -- DevIconExe     xxx ctermfg=124 guifg=#9f0500
    DevIconVala                                 { fg="#7239b3", }, -- DevIconVala    xxx ctermfg=91 guifg=#7239b3
    DevIconHbs                                  { fg="#f0772b", }, -- DevIconHbs     xxx ctermfg=202 guifg=#f0772b
    DevIconLog                                  { fg="#ffffff", }, -- DevIconLog     xxx ctermfg=231 guifg=#ffffff
    DevIconScss                                 { fg="#f55385", }, -- DevIconScss    xxx ctermfg=204 guifg=#f55385
    DevIconEmbeddedOpenTypeFont                 { fg="#ececec", }, -- DevIconEmbeddedOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconScheme                               { fg="#eeeeee", }, -- DevIconScheme  xxx ctermfg=255 guifg=#eeeeee
    DevIconScala                                { fg="#cc3e44", }, -- DevIconScala   xxx ctermfg=167 guifg=#cc3e44
    DevIconSvelteConfig                         { fg="#ff3e00", }, -- DevIconSvelteConfig xxx ctermfg=196 guifg=#ff3e00
    DevIconRs                                   { fg="#dea584", }, -- DevIconRs      xxx ctermfg=216 guifg=#dea584
    DevIconRakefile                             { fg="#701516", }, -- DevIconRakefile xxx ctermfg=52 guifg=#701516
    sym"DevIconPy.typed"                        { fg="#ffbc03", }, -- DevIconPy.typed xxx ctermfg=214 guifg=#ffbc03
    DevIconLicense                              { fg="#d0bf41", }, -- DevIconLicense xxx ctermfg=185 guifg=#d0bf41
    DevIconGitCommit                            { fg="#41535b", }, -- DevIconGitCommit xxx ctermfg=239 guifg=#41535b
    DevIconIco                                  { fg="#cbcb41", }, -- DevIconIco     xxx ctermfg=185 guifg=#cbcb41
    DevIconPackageLockJson                      { fg="#7a0d21", }, -- DevIconPackageLockJson xxx ctermfg=52 guifg=#7a0d21
    DevIconMakefile                             { fg="#6d8086", }, -- DevIconMakefile xxx ctermfg=66 guifg=#6d8086
    DevIconZsh                                  { fg="#89e051", }, -- DevIconZsh     xxx ctermfg=113 guifg=#89e051
    DevIconTypeScriptReactSpec                  { fg="#1354bf", }, -- DevIconTypeScriptReactSpec xxx ctermfg=26 guifg=#1354bf
    DevIconPyd                                  { fg="#ffe291", }, -- DevIconPyd     xxx ctermfg=222 guifg=#ffe291
    DevIconRb                                   { fg="#701516", }, -- DevIconRb      xxx ctermfg=52 guifg=#701516
    DevIconDockerfile                           { fg="#458ee6", }, -- DevIconDockerfile xxx ctermfg=68 guifg=#458ee6
    DevIconD                                    { fg="#427819", }, -- DevIconD       xxx ctermfg=28 guifg=#427819
    DevIconSpecJs                               { fg="#cbcb41", }, -- DevIconSpecJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconGemfile                              { fg="#701516", }, -- DevIconGemfile xxx ctermfg=52 guifg=#701516
    DevIconBrewfile                             { fg="#701516", }, -- DevIconBrewfile xxx ctermfg=52 guifg=#701516
    DevIconPy                                   { fg="#ffbc03", }, -- DevIconPy      xxx ctermfg=214 guifg=#ffbc03
    DevIconXlsx                                 { fg="#207245", }, -- DevIconXlsx    xxx ctermfg=29 guifg=#207245
    DevIconXls                                  { fg="#207245", }, -- DevIconXls     xxx ctermfg=29 guifg=#207245
    DevIconXcPlayground                         { fg="#e37933", }, -- DevIconXcPlayground xxx ctermfg=166 guifg=#e37933
    DevIconWebm                                 { fg="#fd971f", }, -- DevIconWebm    xxx ctermfg=208 guifg=#fd971f
    DevIconWav                                  { fg="#66d8ef", }, -- DevIconWav     xxx ctermfg=45 guifg=#66d8ef
    DevIconPsScriptModulefile                   { fg="#6975c4", }, -- DevIconPsScriptModulefile xxx ctermfg=68 guifg=#6975c4
    DevIconSuo                                  { fg="#e37933", }, -- DevIconSuo     xxx ctermfg=166 guifg=#e37933
    DevIconStyl                                 { fg="#8dc149", }, -- DevIconStyl    xxx ctermfg=113 guifg=#8dc149
    DevIconPsManifestfile                       { fg="#6975c4", }, -- DevIconPsManifestfile xxx ctermfg=68 guifg=#6975c4
    DevIconPsScriptfile                         { fg="#4273ca", }, -- DevIconPsScriptfile xxx ctermfg=68 guifg=#4273ca
    DevIconSlim                                 { fg="#e34c26", }, -- DevIconSlim    xxx ctermfg=196 guifg=#e34c26
    DevIconRproj                                { fg="#358a5b", }, -- DevIconRproj   xxx ctermfg=29 guifg=#358a5b
    DevIconRlib                                 { fg="#dea584", }, -- DevIconRlib    xxx ctermfg=216 guifg=#dea584
    DevIconPyo                                  { fg="#ffe291", }, -- DevIconPyo     xxx ctermfg=222 guifg=#ffe291
    DevIconPyc                                  { fg="#ffe291", }, -- DevIconPyc     xxx ctermfg=222 guifg=#ffe291
    DevIconPsd                                  { fg="#519aba", }, -- DevIconPsd     xxx ctermfg=74 guifg=#519aba
    DevIconPl                                   { fg="#519aba", }, -- DevIconPl      xxx ctermfg=74 guifg=#519aba
    DevIconPpt                                  { fg="#cb4a32", }, -- DevIconPpt     xxx ctermfg=160 guifg=#cb4a32
    DevIconSettingsJson                         { fg="#854cc7", }, -- DevIconSettingsJson xxx ctermfg=98 guifg=#854cc7
    DevIconPhp                                  { fg="#a074c4", }, -- DevIconPhp     xxx ctermfg=140 guifg=#a074c4
    DevIconOpenTypeFont                         { fg="#ececec", }, -- DevIconOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconOPUS                                 { fg="#f88a02", }, -- DevIconOPUS    xxx ctermfg=208 guifg=#f88a02
    DevIconOgg                                  { fg="#66d8ef", }, -- DevIconOgg     xxx ctermfg=45 guifg=#66d8ef
    DevIconMustache                             { fg="#e37933", }, -- DevIconMustache xxx ctermfg=166 guifg=#e37933
    DevIconMp4                                  { fg="#fd971f", }, -- DevIconMp4     xxx ctermfg=208 guifg=#fd971f
    DevIconOrgMode                              { fg="#77aa99", }, -- DevIconOrgMode xxx ctermfg=73 guifg=#77aa99
    DevIconMOV                                  { fg="#fd971f", }, -- DevIconMOV     xxx ctermfg=208 guifg=#fd971f
    DevIconMkv                                  { fg="#fd971f", }, -- DevIconMkv     xxx ctermfg=208 guifg=#fd971f
    DevIconMint                                 { fg="#87c095", }, -- DevIconMint    xxx ctermfg=108 guifg=#87c095
    DevIconM4V                                  { fg="#fd971f", }, -- DevIconM4V     xxx ctermfg=208 guifg=#fd971f
    DevIconZshprofile                           { fg="#89e051", }, -- DevIconZshprofile xxx ctermfg=113 guifg=#89e051
    DevIconGo                                   { fg="#519aba", }, -- DevIconGo      xxx ctermfg=74 guifg=#519aba
    DevIconMl                                   { fg="#e37933", }, -- DevIconMl      xxx ctermfg=166 guifg=#e37933
    DevIconRazorPage                            { fg="#512bd4", }, -- DevIconRazorPage xxx ctermfg=56 guifg=#512bd4
    DevIconVimrc                                { fg="#019833", }, -- DevIconVimrc   xxx ctermfg=28 guifg=#019833
    DevIconGodotProject                         { fg="#6d8086", }, -- DevIconGodotProject xxx ctermfg=66 guifg=#6d8086
    DevIconBinaryGLTF                           { fg="#ffb13b", }, -- DevIconBinaryGLTF xxx ctermfg=214 guifg=#ffb13b
    DevIconFsscript                             { fg="#519aba", }, -- DevIconFsscript xxx ctermfg=74 guifg=#519aba
    DevIconEjs                                  { fg="#cbcb41", }, -- DevIconEjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconDiff                                 { fg="#41535b", }, -- DevIconDiff    xxx ctermfg=239 guifg=#41535b
    DevIconMd                                   { fg="#ffffff", }, -- DevIconMd      xxx ctermfg=231 guifg=#ffffff
    DevIconDrools                               { fg="#ffafaf", }, -- DevIconDrools  xxx ctermfg=217 guifg=#ffafaf
    DevIconDocx                                 { fg="#185abd", }, -- DevIconDocx    xxx ctermfg=26 guifg=#185abd
    DevIconDoc                                  { fg="#185abd", }, -- DevIconDoc     xxx ctermfg=26 guifg=#185abd
    DevIconCson                                 { fg="#cbcb41", }, -- DevIconCson    xxx ctermfg=185 guifg=#cbcb41
    DevIconCp                                   { fg="#519aba", }, -- DevIconCp      xxx ctermfg=74 guifg=#519aba
    DevIconBmp                                  { fg="#a074c4", }, -- DevIconBmp     xxx ctermfg=140 guifg=#a074c4
    DevIconAac                                  { fg="#66d8ef", }, -- DevIconAac     xxx ctermfg=45 guifg=#66d8ef
    DevIconLiquid                               { fg="#95bf47", }, -- DevIconLiquid  xxx ctermfg=106 guifg=#95bf47
    DevIconRake                                 { fg="#701516", }, -- DevIconRake    xxx ctermfg=52 guifg=#701516
    DevIconKotlin                               { fg="#7f52ff", }, -- DevIconKotlin  xxx ctermfg=99 guifg=#7f52ff
    DevIconVim                                  { fg="#019833", }, -- DevIconVim     xxx ctermfg=28 guifg=#019833
    DevIconKsh                                  { fg="#4d5a5e", }, -- DevIconKsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconZorin                                { fg="#14a1e8", }, -- DevIconZorin   xxx ctermfg=39 guifg=#14a1e8
    DevIconJsx                                  { fg="#20c2e3", }, -- DevIconJsx     xxx ctermfg=45 guifg=#20c2e3
    DevIconNPMrc                                { fg="#e8274b", }, -- DevIconNPMrc   xxx ctermfg=197 guifg=#e8274b
    DevIconJs                                   { fg="#f1f134", }, -- DevIconJs      xxx ctermfg=227 guifg=#f1f134
    DevIconJl                                   { fg="#a270ba", }, -- DevIconJl      xxx ctermfg=133 guifg=#a270ba
    DevIconNPMIgnore                            { fg="#e8274b", }, -- DevIconNPMIgnore xxx ctermfg=197 guifg=#e8274b
    DevIconHurl                                 { fg="#ff0288", }, -- DevIconHurl    xxx ctermfg=198 guifg=#ff0288
    DevIconGitModules                           { fg="#41535b", }, -- DevIconGitModules xxx ctermfg=239 guifg=#41535b
    DevIconGitlabCI                             { fg="#e24329", }, -- DevIconGitlabCI xxx ctermfg=196 guifg=#e24329
    DevIconLua                                  { fg="#51a0cf", }, -- DevIconLua     xxx ctermfg=74 guifg=#51a0cf
    DevIconGitIgnore                            { fg="#41535b", }, -- DevIconGitIgnore xxx ctermfg=239 guifg=#41535b
    DevIconGitConfig                            { fg="#41535b", }, -- DevIconGitConfig xxx ctermfg=239 guifg=#41535b
    DevIconGitAttributes                        { fg="#41535b", }, -- DevIconGitAttributes xxx ctermfg=239 guifg=#41535b
    DevIconMarkdown                             { fg="#519aba", }, -- DevIconMarkdown xxx ctermfg=74 guifg=#519aba
    DevIconSlackware                            { fg="#475fa9", }, -- DevIconSlackware xxx ctermfg=61 guifg=#475fa9
    DevIconRedhat                               { fg="#ee0000", }, -- DevIconRedhat  xxx ctermfg=196 guifg=#ee0000
    DevIconEslintrc                             { fg="#4b32c3", }, -- DevIconEslintrc xxx ctermfg=56 guifg=#4b32c3
    DevIconEslintIgnore                         { fg="#4b32c3", }, -- DevIconEslintIgnore xxx ctermfg=56 guifg=#4b32c3
    DevIconEditorConfig                         { fg="#ffffff", }, -- DevIconEditorConfig xxx ctermfg=231 guifg=#ffffff
    DevIconOut                                  { fg="#9f0500", }, -- DevIconOut     xxx ctermfg=124 guifg=#9f0500
    DevIconRockyLinux                           { fg="#0fb37d", }, -- DevIconRockyLinux xxx ctermfg=36 guifg=#0fb37d
    DevIconBashrc                               { fg="#89e051", }, -- DevIconBashrc  xxx ctermfg=113 guifg=#89e051
    DevIconBashProfile                          { fg="#89e051", }, -- DevIconBashProfile xxx ctermfg=113 guifg=#89e051
    DevIconRaspberryPiOS                        { fg="#be1848", }, -- DevIconRaspberryPiOS xxx ctermfg=161 guifg=#be1848
    DevIconBabelrc                              { fg="#cbcb41", }, -- DevIconBabelrc xxx ctermfg=185 guifg=#cbcb41
    DevIconPop_OS                               { fg="#48b9c7", }, -- DevIconPop_OS  xxx ctermfg=73 guifg=#48b9c7
    DevIconReScriptInterface                    { fg="#f55385", }, -- DevIconReScriptInterface xxx ctermfg=204 guifg=#f55385
    DevIconParrot                               { fg="#000000", }, -- DevIconParrot  xxx ctermfg=16 guifg=#000000
    DevIconTor                                  { fg="#519aba", }, -- DevIconTor     xxx ctermfg=74 guifg=#519aba
    DevIconopenSUSE                             { fg="#6fb424", }, -- DevIconopenSUSE xxx ctermfg=70 guifg=#6fb424
    DevIconEex                                  { fg="#a074c4", }, -- DevIconEex     xxx ctermfg=140 guifg=#a074c4
    DevIconNixOS                                { fg="#7ab1db", }, -- DevIconNixOS   xxx ctermfg=110 guifg=#7ab1db
    DevIconManjaro                              { fg="#33b959", }, -- DevIconManjaro xxx ctermfg=35 guifg=#33b959
    DevIconR                                    { fg="#2266ba", }, -- DevIconR       xxx ctermfg=25 guifg=#2266ba
    DevIconMageia                               { fg="#2397d4", }, -- DevIconMageia  xxx ctermfg=67 guifg=#2397d4
    DevIconPxd                                  { fg="#5aa7e4", }, -- DevIconPxd     xxx ctermfg=39 guifg=#5aa7e4
    DevIconKali                                 { fg="#ffffff", }, -- DevIconKali    xxx ctermfg=231 guifg=#ffffff
    DevIconBat                                  { fg="#c1f12e", }, -- DevIconBat     xxx ctermfg=191 guifg=#c1f12e
    DevIconImportConfiguration                  { fg="#ececec", }, -- DevIconImportConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconIllumos                              { fg="#ff430f", }, -- DevIconIllumos xxx ctermfg=196 guifg=#ff430f
    DevIconBazelBuild                           { fg="#89e051", }, -- DevIconBazelBuild xxx ctermfg=113 guifg=#89e051
    DevIconDefault                              { fg="#6d8086", }, -- DevIconDefault xxx ctermfg=66 guifg=#6d8086
    DevIconGentoo                               { fg="#b1abce", }, -- DevIconGentoo  xxx ctermfg=146 guifg=#b1abce
    DevIconFreeBSD                              { fg="#c90f02", }, -- DevIconFreeBSD xxx ctermfg=160 guifg=#c90f02
    DevIconFedora                               { fg="#072a5e", }, -- DevIconFedora  xxx ctermfg=17 guifg=#072a5e
    DevIconEndeavour                            { fg="#7b3db9", }, -- DevIconEndeavour xxx ctermfg=91 guifg=#7b3db9
    DevIconTerminal                             { fg="#31b53e", }, -- DevIconTerminal xxx ctermfg=34 guifg=#31b53e
    DevIconElementary                           { fg="#5890c2", }, -- DevIconElementary xxx ctermfg=67 guifg=#5890c2
    DevIconVerilog                              { fg="#019833", }, -- DevIconVerilog xxx ctermfg=28 guifg=#019833
    DevIconDevuan                               { fg="#404a52", }, -- DevIconDevuan  xxx ctermfg=238 guifg=#404a52
    DevIconDeepin                               { fg="#2ca7f8", }, -- DevIconDeepin  xxx ctermfg=39 guifg=#2ca7f8
    DevIconDebian                               { fg="#a80030", }, -- DevIconDebian  xxx ctermfg=88 guifg=#a80030
    DevIconDesktopEntry                         { fg="#563d7c", }, -- DevIconDesktopEntry xxx ctermfg=54 guifg=#563d7c
    DevIconVoid                                 { fg="#295340", }, -- DevIconVoid    xxx ctermfg=23 guifg=#295340
    DevIconBudgie                               { fg="#ffffff", }, -- DevIconBudgie  xxx ctermfg=231 guifg=#ffffff
    DevIconArtix                                { fg="#41b4d7", }, -- DevIconArtix   xxx ctermfg=38 guifg=#41b4d7
    DevIconAOSC                                 { fg="#000000", }, -- DevIconAOSC    xxx ctermfg=16 guifg=#000000
    DevIconCMake                                { fg="#6d8086", }, -- DevIconCMake   xxx ctermfg=66 guifg=#6d8086
    DevIconAlpine                               { fg="#0d597f", }, -- DevIconAlpine  xxx ctermfg=24 guifg=#0d597f
    DevIconAlmalinux                            { fg="#000000", }, -- DevIconAlmalinux xxx ctermfg=16 guifg=#000000
    DevIconApple                                { fg="#a2aaad", }, -- DevIconApple   xxx ctermfg=248 guifg=#a2aaad
    DevIconAi                                   { fg="#cbcb41", }, -- DevIconAi      xxx ctermfg=185 guifg=#cbcb41
    DevIconSln                                  { fg="#854cc7", }, -- DevIconSln     xxx ctermfg=98 guifg=#854cc7
    DevIconMts                                  { fg="#519aba", }, -- DevIconMts     xxx ctermfg=74 guifg=#519aba
    DevIconFsharp                               { fg="#519aba", }, -- DevIconFsharp  xxx ctermfg=74 guifg=#519aba
    DevIconSpecTs                               { fg="#519aba", }, -- DevIconSpecTs  xxx ctermfg=74 guifg=#519aba
    DevIconPsb                                  { fg="#519aba", }, -- DevIconPsb     xxx ctermfg=74 guifg=#519aba
    DevIconYaml                                 { fg="#6d8086", }, -- DevIconYaml    xxx ctermfg=66 guifg=#6d8086
    DevIconPyi                                  { fg="#ffbc03", }, -- DevIconPyi     xxx ctermfg=214 guifg=#ffbc03
    DevIconXaml                                 { fg="#512bd4", }, -- DevIconXaml    xxx ctermfg=56 guifg=#512bd4
    DevIconZshrc                                { fg="#89e051", }, -- DevIconZshrc   xxx ctermfg=113 guifg=#89e051
    DevIconLuaurc                               { fg="#00a2ff", }, -- DevIconLuaurc  xxx ctermfg=75 guifg=#00a2ff
    DevIconCsv                                  { fg="#89e051", }, -- DevIconCsv     xxx ctermfg=113 guifg=#89e051
    DevIconTxt                                  { fg="#89e051", }, -- DevIconTxt     xxx ctermfg=113 guifg=#89e051
    DevIconGvimrc                               { fg="#019833", }, -- DevIconGvimrc  xxx ctermfg=28 guifg=#019833
    DevIconJsonc                                { fg="#cbcb41", }, -- DevIconJsonc   xxx ctermfg=185 guifg=#cbcb41
    DevIconLock                                 { fg="#bbbbbb", }, -- DevIconLock    xxx ctermfg=250 guifg=#bbbbbb
    DevIconCSharpProject                        { fg="#512bd4", }, -- DevIconCSharpProject xxx ctermfg=56 guifg=#512bd4
    DevIconPdf                                  { fg="#b30b00", }, -- DevIconPdf     xxx ctermfg=124 guifg=#b30b00
    DevIconPxi                                  { fg="#5aa7e4", }, -- DevIconPxi     xxx ctermfg=39 guifg=#5aa7e4
    DevIconMdx                                  { fg="#519aba", }, -- DevIconMdx     xxx ctermfg=74 guifg=#519aba
    DevIconProcfile                             { fg="#a074c4", }, -- DevIconProcfile xxx ctermfg=140 guifg=#a074c4
    DevIconUbuntu                               { fg="#dd4814", }, -- DevIconUbuntu  xxx ctermfg=196 guifg=#dd4814
    DevIconJava                                 { fg="#cc3e44", }, -- DevIconJava    xxx ctermfg=167 guifg=#cc3e44
    DevIconGraphQL                              { fg="#e535ab", }, -- DevIconGraphQL xxx ctermfg=199 guifg=#e535ab
    DevIconXml                                  { fg="#e37933", }, -- DevIconXml     xxx ctermfg=166 guifg=#e37933
    DevIconMli                                  { fg="#e37933", }, -- DevIconMli     xxx ctermfg=166 guifg=#e37933
    DevIconHh                                   { fg="#a074c4", }, -- DevIconHh      xxx ctermfg=140 guifg=#a074c4
    DevIconSml                                  { fg="#e37933", }, -- DevIconSml     xxx ctermfg=166 guifg=#e37933
    DevIconClojureC                             { fg="#8dc149", }, -- DevIconClojureC xxx ctermfg=113 guifg=#8dc149
    DevIconJson                                 { fg="#cbcb41", }, -- DevIconJson    xxx ctermfg=185 guifg=#cbcb41
    DevIconDropbox                              { fg="#0061fe", }, -- DevIconDropbox xxx ctermfg=27 guifg=#0061fe
    DevIconElf                                  { fg="#9f0500", }, -- DevIconElf     xxx ctermfg=124 guifg=#9f0500
    DevIconProlog                               { fg="#e4b854", }, -- DevIconProlog  xxx ctermfg=179 guifg=#e4b854
    DevIconJson5                                { fg="#cbcb41", }, -- DevIconJson5   xxx ctermfg=185 guifg=#cbcb41
    DevIconSolus                                { fg="#4b5163", }, -- DevIconSolus   xxx ctermfg=239 guifg=#4b5163
    DevIconExs                                  { fg="#a074c4", }, -- DevIconExs     xxx ctermfg=140 guifg=#a074c4
    DevIconSabayon                              { fg="#c6c6c6", }, -- DevIconSabayon xxx ctermfg=251 guifg=#c6c6c6
    DevIconArch                                 { fg="#0f94d2", }, -- DevIconArch    xxx ctermfg=67 guifg=#0f94d2
    DevIconAwk                                  { fg="#4d5a5e", }, -- DevIconAwk     xxx ctermfg=240 guifg=#4d5a5e
    DevIconLess                                 { fg="#563d7c", }, -- DevIconLess    xxx ctermfg=54 guifg=#563d7c
    DevIconHtm                                  { fg="#e34c26", }, -- DevIconHtm     xxx ctermfg=196 guifg=#e34c26
    DevIconCsh                                  { fg="#4d5a5e", }, -- DevIconCsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconEnv                                  { fg="#faf743", }, -- DevIconEnv     xxx ctermfg=227 guifg=#faf743
    DevIconGuix                                 { fg="#ffcc00", }, -- DevIconGuix    xxx ctermfg=220 guifg=#ffcc00
    DevIconBibTeX                               { fg="#cbcb41", }, -- DevIconBibTeX  xxx ctermfg=185 guifg=#cbcb41
    DevIconTempl                                { fg="#dbbd30", }, -- DevIconTempl   xxx ctermfg=178 guifg=#dbbd30
    DevIconConf                                 { fg="#6d8086", }, -- DevIconConf    xxx ctermfg=66 guifg=#6d8086
    DevIconFavicon                              { fg="#cbcb41", }, -- DevIconFavicon xxx ctermfg=185 guifg=#cbcb41
    DevIconQuery                                { fg="#90a850", }, -- DevIconQuery   xxx ctermfg=107 guifg=#90a850
    DevIconBazel                                { fg="#89e051", }, -- DevIconBazel   xxx ctermfg=113 guifg=#89e051
    DevIconHxx                                  { fg="#a074c4", }, -- DevIconHxx     xxx ctermfg=140 guifg=#a074c4
    DevIconFlac                                 { fg="#66d8ef", }, -- DevIconFlac    xxx ctermfg=45 guifg=#66d8ef
    DevIconMjs                                  { fg="#f1f134", }, -- DevIconMjs     xxx ctermfg=227 guifg=#f1f134
    DevIconZig                                  { fg="#f69a1b", }, -- DevIconZig     xxx ctermfg=172 guifg=#f69a1b
    DevIconSass                                 { fg="#f55385", }, -- DevIconSass    xxx ctermfg=204 guifg=#f55385
    DevIconWindows                              { fg="#00a4ef", }, -- DevIconWindows xxx ctermfg=39 guifg=#00a4ef
    DevIconNswag                                { fg="#85ea2d", }, -- DevIconNswag   xxx ctermfg=112 guifg=#85ea2d
    DevIconTestTs                               { fg="#519aba", }, -- DevIconTestTs  xxx ctermfg=74 guifg=#519aba
    DevIconWebOpenFontFormat                    { fg="#ececec", }, -- DevIconWebOpenFontFormat xxx ctermfg=255 guifg=#ececec
    DevIconTSConfig                             { fg="#519aba", }, -- DevIconTSConfig xxx ctermfg=74 guifg=#519aba
    DevIconGDScript                             { fg="#6d8086", }, -- DevIconGDScript xxx ctermfg=66 guifg=#6d8086
    DevIconVlang                                { fg="#5d87bf", }, -- DevIconVlang   xxx ctermfg=67 guifg=#5d87bf
    DevIconDart                                 { fg="#03589c", }, -- DevIconDart    xxx ctermfg=25 guifg=#03589c
    DevIconRmd                                  { fg="#519aba", }, -- DevIconRmd     xxx ctermfg=74 guifg=#519aba
    DevIconWebpack                              { fg="#519aba", }, -- DevIconWebpack xxx ctermfg=74 guifg=#519aba
    DevIconYml                                  { fg="#6d8086", }, -- DevIconYml     xxx ctermfg=66 guifg=#6d8086
    DevIconPackedResource                       { fg="#6d8086", }, -- DevIconPackedResource xxx ctermfg=66 guifg=#6d8086
    DevIconAvif                                 { fg="#a074c4", }, -- DevIconAvif    xxx ctermfg=140 guifg=#a074c4
    DevIconSolidity                             { fg="#519aba", }, -- DevIconSolidity xxx ctermfg=74 guifg=#519aba
    DevIconTsx                                  { fg="#1354bf", }, -- DevIconTsx     xxx ctermfg=26 guifg=#1354bf
    DevIconGruntfile                            { fg="#e37933", }, -- DevIconGruntfile xxx ctermfg=166 guifg=#e37933
    DevIconCMakeLists                           { fg="#6d8086", }, -- DevIconCMakeLists xxx ctermfg=66 guifg=#6d8086
    DevIconVagrantfile                          { fg="#1563ff", }, -- DevIconVagrantfile xxx ctermfg=27 guifg=#1563ff
    DevIconGulpfile                             { fg="#cc3e44", }, -- DevIconGulpfile xxx ctermfg=167 guifg=#cc3e44
    DevIconSwift                                { fg="#e37933", }, -- DevIconSwift   xxx ctermfg=166 guifg=#e37933
    DevIconDsStore                              { fg="#41535b", }, -- DevIconDsStore xxx ctermfg=239 guifg=#41535b
    DevIconTex                                  { fg="#3d6117", }, -- DevIconTex     xxx ctermfg=22 guifg=#3d6117
    DevIconTerraform                            { fg="#5f43e9", }, -- DevIconTerraform xxx ctermfg=93 guifg=#5f43e9
    DevIconLuau                                 { fg="#00a2ff", }, -- DevIconLuau    xxx ctermfg=75 guifg=#00a2ff
    DevIconLinux                                { fg="#000000", }, -- DevIconLinux   xxx ctermfg=16 guifg=#000000
    DevIconTextResource                         { fg="#cbcb41", }, -- DevIconTextResource xxx ctermfg=185 guifg=#cbcb41
    DevIconJavaScriptReactTest                  { fg="#20c2e3", }, -- DevIconJavaScriptReactTest xxx ctermfg=45 guifg=#20c2e3
    DevIconTextScene                            { fg="#a074c4", }, -- DevIconTextScene xxx ctermfg=140 guifg=#a074c4
    DevIconMotoko                               { fg="#9772fb", }, -- DevIconMotoko  xxx ctermfg=135 guifg=#9772fb
    DevIconIni                                  { fg="#6d8086", }, -- DevIconIni     xxx ctermfg=66 guifg=#6d8086
    DevIconReScript                             { fg="#cc3e44", }, -- DevIconReScript xxx ctermfg=167 guifg=#cc3e44
    DevIconFsx                                  { fg="#519aba", }, -- DevIconFsx     xxx ctermfg=74 guifg=#519aba
    DevIconMixLock                              { fg="#a074c4", }, -- DevIconMixLock xxx ctermfg=140 guifg=#a074c4
    DevIconFsi                                  { fg="#519aba", }, -- DevIconFsi     xxx ctermfg=74 guifg=#519aba
    DevIconMaterial                             { fg="#b83998", }, -- DevIconMaterial xxx ctermfg=163 guifg=#b83998
    DevIconC                                    { fg="#599eff", }, -- DevIconC       xxx ctermfg=111 guifg=#599eff
    DevIconMp3                                  { fg="#66d8ef", }, -- DevIconMp3     xxx ctermfg=45 guifg=#66d8ef
    DevIconHtml                                 { fg="#e44d26", }, -- DevIconHtml    xxx ctermfg=196 guifg=#e44d26
    DevIconDb                                   { fg="#dad8d8", }, -- DevIconDb      xxx ctermfg=188 guifg=#dad8d8
    DevIconHs                                   { fg="#a074c4", }, -- DevIconHs      xxx ctermfg=140 guifg=#a074c4
    DevIconZshenv                               { fg="#89e051", }, -- DevIconZshenv  xxx ctermfg=113 guifg=#89e051
    DevIconFs                                   { fg="#519aba", }, -- DevIconFs      xxx ctermfg=74 guifg=#519aba
    DevIconHpp                                  { fg="#a074c4", }, -- DevIconHpp     xxx ctermfg=140 guifg=#a074c4
    DevIconHaml                                 { fg="#eaeae1", }, -- DevIconHaml    xxx ctermfg=255 guifg=#eaeae1
    DevIconVue                                  { fg="#8dc149", }, -- DevIconVue     xxx ctermfg=113 guifg=#8dc149
    DevIconEdn                                  { fg="#519aba", }, -- DevIconEdn     xxx ctermfg=74 guifg=#519aba
    DevIconGitLogo                              { fg="#f14c28", }, -- DevIconGitLogo xxx ctermfg=196 guifg=#f14c28
    DevIconH                                    { fg="#a074c4", }, -- DevIconH       xxx ctermfg=140 guifg=#a074c4
    DevIconNix                                  { fg="#7ebae4", }, -- DevIconNix     xxx ctermfg=110 guifg=#7ebae4
    DevIconM4A                                  { fg="#66d8ef", }, -- DevIconM4A     xxx ctermfg=45 guifg=#66d8ef
    DevIconNim                                  { fg="#f3d400", }, -- DevIconNim     xxx ctermfg=220 guifg=#f3d400
    DevIconFortran                              { fg="#734f96", }, -- DevIconFortran xxx ctermfg=97 guifg=#734f96
    DevIconLeex                                 { fg="#a074c4", }, -- DevIconLeex    xxx ctermfg=140 guifg=#a074c4
    DevIconsbt                                  { fg="#cc3e44", }, -- DevIconsbt     xxx ctermfg=167 guifg=#cc3e44
    DevIconNodeModules                          { fg="#e8274b", }, -- DevIconNodeModules xxx ctermfg=197 guifg=#e8274b
    DevIconPackageJson                          { fg="#e8274b", }, -- DevIconPackageJson xxx ctermfg=197 guifg=#e8274b
    DevIconGemspec                              { fg="#701516", }, -- DevIconGemspec xxx ctermfg=52 guifg=#701516
    DevIconCentos                               { fg="#a2518d", }, -- DevIconCentos  xxx ctermfg=132 guifg=#a2518d
    DevIconJpegXl                               { fg="#a074c4", }, -- DevIconJpegXl  xxx ctermfg=140 guifg=#a074c4
    DevIconWebp                                 { fg="#a074c4", }, -- DevIconWebp    xxx ctermfg=140 guifg=#a074c4
    DevIconGif                                  { fg="#a074c4", }, -- DevIconGif     xxx ctermfg=140 guifg=#a074c4
    DevIconPng                                  { fg="#a074c4", }, -- DevIconPng     xxx ctermfg=140 guifg=#a074c4
    DevIconJpeg                                 { fg="#a074c4", }, -- DevIconJpeg    xxx ctermfg=140 guifg=#a074c4
    DevIconJpg                                  { fg="#a074c4", }, -- DevIconJpg     xxx ctermfg=140 guifg=#a074c4
    DevIconSig                                  { fg="#e37933", }, -- DevIconSig     xxx ctermfg=166 guifg=#e37933
    DevIconFennel                               { fg="#fff3d7", }, -- DevIconFennel  xxx ctermfg=230 guifg=#fff3d7
    DevIconRss                                  { fg="#fb9d3b", }, -- DevIconRss     xxx ctermfg=215 guifg=#fb9d3b
    DevIconWasm                                 { fg="#5c4cdb", }, -- DevIconWasm    xxx ctermfg=62 guifg=#5c4cdb
    DevIconFish                                 { fg="#4d5a5e", }, -- DevIconFish    xxx ctermfg=240 guifg=#4d5a5e
    DevIconXul                                  { fg="#e37933", }, -- DevIconXul     xxx ctermfg=166 guifg=#e37933
    DevIconPp                                   { fg="#ffa61a", }, -- DevIconPp      xxx ctermfg=214 guifg=#ffa61a
    DevIconJavaScriptReactSpec                  { fg="#20c2e3", }, -- DevIconJavaScriptReactSpec xxx ctermfg=45 guifg=#20c2e3
    DevIconEx                                   { fg="#a074c4", }, -- DevIconEx      xxx ctermfg=140 guifg=#a074c4
    DevIconErb                                  { fg="#701516", }, -- DevIconErb     xxx ctermfg=52 guifg=#701516
    DevIconErl                                  { fg="#b83998", }, -- DevIconErl     xxx ctermfg=163 guifg=#b83998
    NeoscrollHiddenCursor                       { gui="reverse", blend=100, }, -- NeoscrollHiddenCursor xxx gui=reverse blend=100
    MiniAnimateCursor                           { gui="reverse,nocombine", }, -- MiniAnimateCursor xxx cterm=reverse,nocombine gui=reverse,nocombine
    MiniAnimateNormalFloat                      { }, -- MiniAnimateNormalFloat xxx cterm= gui=
    lualine_a_insert                            { fg="#000000", bg="#6ab791", gui="bold", }, -- lualine_a_insert xxx gui=bold guifg=#000000 guibg=#6ab791
    lualine_c_insert                            { fg="#ffffff", bg="#182a2f", }, -- lualine_c_insert xxx guifg=#ffffff guibg=#182a2f
    lualine_b_insert                            { fg="#6ab791", bg="#000000", }, -- lualine_b_insert xxx guifg=#6ab791 guibg=#000000
    lualine_a_command                           { fg="#000000", bg="#ff5879", gui="bold", }, -- lualine_a_command xxx gui=bold guifg=#000000 guibg=#ff5879
    lualine_c_command                           { fg="#ffffff", bg="#182a2f", }, -- lualine_c_command xxx guifg=#ffffff guibg=#182a2f
    lualine_b_command                           { fg="#ff5879", bg="#000000", }, -- lualine_b_command xxx guifg=#ff5879 guibg=#000000
    lualine_a_replace                           { fg="#000000", bg="#1697b1", gui="bold", }, -- lualine_a_replace xxx gui=bold guifg=#000000 guibg=#1697b1
    lualine_c_replace                           { fg="#ffffff", bg="#182a2f", }, -- lualine_c_replace xxx guifg=#ffffff guibg=#182a2f
    lualine_b_replace                           { fg="#1697b1", bg="#000000", }, -- lualine_b_replace xxx guifg=#1697b1 guibg=#000000
    lualine_a_visual                            { fg="#000000", bg="#2fb0ab", gui="bold", }, -- lualine_a_visual xxx gui=bold guifg=#000000 guibg=#2fb0ab
    lualine_c_visual                            { fg="#ffffff", bg="#182a2f", }, -- lualine_c_visual xxx guifg=#ffffff guibg=#182a2f
    lualine_b_visual                            { fg="#2fb0ab", bg="#000000", }, -- lualine_b_visual xxx guifg=#2fb0ab guibg=#000000
    lualine_a_normal                            { fg="#000000", bg="#d13434", gui="bold", }, -- lualine_a_normal xxx gui=bold guifg=#000000 guibg=#d13434
    lualine_c_normal                            { fg="#ffffff", bg="#182a2f", }, -- lualine_c_normal xxx guifg=#ffffff guibg=#182a2f
    lualine_b_normal                            { fg="#d13434", bg="#000000", }, -- lualine_b_normal xxx guifg=#d13434 guibg=#000000
    lualine_b_diff_added_normal                 { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_normal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_insert                 { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_insert xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_visual                 { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_visual xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_replace                { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_replace xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_command                { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_command xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_terminal               { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_terminal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_inactive               { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_inactive xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_normal              { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_normal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_insert              { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_insert xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_visual              { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_visual xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_replace             { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_replace xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_command             { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_command xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_terminal            { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_terminal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_inactive            { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_inactive xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_removed_normal               { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_normal xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_insert               { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_insert xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_visual               { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_visual xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_replace              { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_replace xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_command              { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_command xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_terminal             { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_terminal xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_inactive             { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_inactive xxx guifg=#0000ff guibg=#000000
    lualine_b_diagnostics_error_normal          { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_normal xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_insert          { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_insert xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_visual          { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_visual xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_replace         { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_replace xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_command         { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_command xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_terminal        { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_terminal xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_inactive        { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_inactive xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_warn_normal           { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_normal xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_insert           { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_insert xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_visual           { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_visual xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_replace          { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_replace xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_command          { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_command xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_terminal         { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_terminal xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_inactive         { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_inactive xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_info_normal           { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_normal xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_insert           { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_insert xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_visual           { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_visual xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_replace          { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_replace xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_command          { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_command xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_terminal         { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_terminal xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_inactive         { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_inactive xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_hint_normal           { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_normal xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_insert           { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_insert xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_visual           { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_visual xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_replace          { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_replace xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_command          { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_command xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_terminal         { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_terminal xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_inactive         { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_inactive xxx guifg=#d3d3d3 guibg=#000000
    DapUIScope                                  { fg="#00f1f5", }, -- DapUIScope     xxx guifg=#00f1f5
    DapUIType                                   { fg="#d484ff", }, -- DapUIType      xxx guifg=#d484ff
    DapUIModifiedValue                          { fg="#00f1f5", gui="bold", }, -- DapUIModifiedValue xxx gui=bold guifg=#00f1f5
    DapUIDecoration                             { fg="#00f1f5", }, -- DapUIDecoration xxx guifg=#00f1f5
    DapUIThread                                 { fg="#a9ff68", }, -- DapUIThread    xxx guifg=#a9ff68
    DapUIStoppedThread                          { fg="#00f1f5", }, -- DapUIStoppedThread xxx guifg=#00f1f5
    DapUISource                                 { fg="#d484ff", }, -- DapUISource    xxx guifg=#d484ff
    DapUILineNumber                             { fg="#00f1f5", }, -- DapUILineNumber xxx guifg=#00f1f5
    DapUIBreakpointsLine                        { DapUILineNumber }, -- DapUIBreakpointsLine xxx links to DapUILineNumber
    DapUIFloatBorder                            { fg="#00f1f5", }, -- DapUIFloatBorder xxx guifg=#00f1f5
    DapUIWatchesEmpty                           { fg="#f70067", }, -- DapUIWatchesEmpty xxx guifg=#f70067
    DapUIWatchesValue                           { fg="#a9ff68", }, -- DapUIWatchesValue xxx guifg=#a9ff68
    DapUIWatchesError                           { fg="#f70067", }, -- DapUIWatchesError xxx guifg=#f70067
    DapUIBreakpointsPath                        { fg="#00f1f5", }, -- DapUIBreakpointsPath xxx guifg=#00f1f5
    DapUIBreakpointsInfo                        { fg="#a9ff68", }, -- DapUIBreakpointsInfo xxx guifg=#a9ff68
    DapUIBreakpointsCurrentLine                 { fg="#a9ff68", gui="bold", }, -- DapUIBreakpointsCurrentLine xxx gui=bold guifg=#a9ff68
    DapUICurrentFrameName                       { DapUIBreakpointsCurrentLine }, -- DapUICurrentFrameName xxx links to DapUIBreakpointsCurrentLine
    DapUIBreakpointsDisabledLine                { fg="#424242", }, -- DapUIBreakpointsDisabledLine xxx guifg=#424242
    DapUIStepOver                               { fg="#00f1f5", }, -- DapUIStepOver  xxx guifg=#00f1f5
    DapUIStepInto                               { fg="#00f1f5", }, -- DapUIStepInto  xxx guifg=#00f1f5
    DapUIStepBack                               { fg="#00f1f5", }, -- DapUIStepBack  xxx guifg=#00f1f5
    DapUIStepOut                                { fg="#00f1f5", }, -- DapUIStepOut   xxx guifg=#00f1f5
    DapUIStop                                   { fg="#f70067", }, -- DapUIStop      xxx guifg=#f70067
    DapUIPlayPause                              { fg="#a9ff68", }, -- DapUIPlayPause xxx guifg=#a9ff68
    DapUIRestart                                { fg="#a9ff68", }, -- DapUIRestart   xxx guifg=#a9ff68
    DapUIUnavailable                            { fg="#424242", }, -- DapUIUnavailable xxx guifg=#424242
    DapUIWinSelect                              { fg="#00f1f5", gui="bold", }, -- DapUIWinSelect xxx ctermfg=14 gui=bold guifg=#00f1f5
    DapUINormalNC                               { }, -- DapUINormalNC  xxx cterm= gui=
    DapUIPlayPauseNC                            { fg="#a9ff68", }, -- DapUIPlayPauseNC xxx cterm= gui= guifg=#a9ff68
    DapUIRestartNC                              { fg="#a9ff68", }, -- DapUIRestartNC xxx cterm= gui= guifg=#a9ff68
    DapUIStopNC                                 { fg="#f70067", }, -- DapUIStopNC    xxx cterm= gui= guifg=#f70067
    DapUIUnavailableNC                          { fg="#424242", }, -- DapUIUnavailableNC xxx cterm= gui= guifg=#424242
    DapUIStepOverNC                             { fg="#00f1f5", }, -- DapUIStepOverNC xxx cterm= gui= guifg=#00f1f5
    DapUIStepIntoNC                             { fg="#00f1f5", }, -- DapUIStepIntoNC xxx cterm= gui= guifg=#00f1f5
    DapUIStepBackNC                             { fg="#00f1f5", }, -- DapUIStepBackNC xxx cterm= gui= guifg=#00f1f5
    DapUIStepOutNC                              { fg="#00f1f5", }, -- DapUIStepOutNC xxx cterm= gui= guifg=#00f1f5
    lualine_x_filetype_DevIconDefault_normal    { fg="#6d8086", bg="#182a2f", }, -- lualine_x_filetype_DevIconDefault_normal xxx guifg=#6d8086 guibg=#182a2f
    lualine_x_filetype_DevIconDefault_insert    { fg="#6d8086", bg="#182a2f", }, -- lualine_x_filetype_DevIconDefault_insert xxx guifg=#6d8086 guibg=#182a2f
    lualine_x_filetype_DevIconDefault_visual    { fg="#6d8086", bg="#182a2f", }, -- lualine_x_filetype_DevIconDefault_visual xxx guifg=#6d8086 guibg=#182a2f
    lualine_x_filetype_DevIconDefault_replace   { fg="#6d8086", bg="#182a2f", }, -- lualine_x_filetype_DevIconDefault_replace xxx guifg=#6d8086 guibg=#182a2f
    lualine_x_filetype_DevIconDefault_command   { fg="#6d8086", bg="#182a2f", }, -- lualine_x_filetype_DevIconDefault_command xxx guifg=#6d8086 guibg=#182a2f
    lualine_x_filetype_DevIconDefault_terminal  { fg="#6d8086", bg="#182a2f", }, -- lualine_x_filetype_DevIconDefault_terminal xxx guifg=#6d8086 guibg=#182a2f
    lualine_x_filetype_DevIconDefault_inactive  { fg="#6d8086", bg="#182a2f", }, -- lualine_x_filetype_DevIconDefault_inactive xxx guifg=#6d8086 guibg=#182a2f
    lualine_x_filetype_DevIconLua_normal        { fg="#51a0cf", bg="#182a2f", }, -- lualine_x_filetype_DevIconLua_normal xxx guifg=#51a0cf guibg=#182a2f
    lualine_x_filetype_DevIconLua_insert        { fg="#51a0cf", bg="#182a2f", }, -- lualine_x_filetype_DevIconLua_insert xxx guifg=#51a0cf guibg=#182a2f
    lualine_x_filetype_DevIconLua_visual        { fg="#51a0cf", bg="#182a2f", }, -- lualine_x_filetype_DevIconLua_visual xxx guifg=#51a0cf guibg=#182a2f
    lualine_x_filetype_DevIconLua_replace       { fg="#51a0cf", bg="#182a2f", }, -- lualine_x_filetype_DevIconLua_replace xxx guifg=#51a0cf guibg=#182a2f
    lualine_x_filetype_DevIconLua_command       { fg="#51a0cf", bg="#182a2f", }, -- lualine_x_filetype_DevIconLua_command xxx guifg=#51a0cf guibg=#182a2f
    lualine_x_filetype_DevIconLua_terminal      { fg="#51a0cf", bg="#182a2f", }, -- lualine_x_filetype_DevIconLua_terminal xxx guifg=#51a0cf guibg=#182a2f
    lualine_x_filetype_DevIconLua_inactive      { fg="#51a0cf", bg="#182a2f", }, -- lualine_x_filetype_DevIconLua_inactive xxx guifg=#51a0cf guibg=#182a2f
    MiniHipatternsFixme                         { }, -- MiniHipatternsFixme xxx cterm= gui=
    MiniHipatternsHack                          { }, -- MiniHipatternsHack xxx cterm= gui=
    MiniHipatternsTodo                          { }, -- MiniHipatternsTodo xxx cterm= gui=
    MiniHipatternsNote                          { }, -- MiniHipatternsNote xxx cterm= gui=
    MiniHipatterns000000                        { fg="#ffffff", bg="#000000", }, -- MiniHipatterns000000 xxx guifg=#ffffff guibg=#000000
    MiniHipatternsffffff                        { fg="#000000", bg="#ffffff", }, -- MiniHipatternsffffff xxx guifg=#000000 guibg=#ffffff
    MiniHipatternsfcfcfc                        { fg="#000000", bg="#fcfcfc", }, -- MiniHipatternsfcfcfc xxx guifg=#000000 guibg=#fcfcfc
    MiniHipatterns04171d                        { fg="#ffffff", bg="#04171d", }, -- MiniHipatterns04171d xxx guifg=#ffffff guibg=#04171d
    MiniHipatterns808080                        { fg="#000000", bg="#808080", }, -- MiniHipatterns808080 xxx guifg=#000000 guibg=#808080
    MiniHipatterns032c36                        { fg="#ffffff", bg="#032c36", }, -- MiniHipatterns032c36 xxx guifg=#ffffff guibg=#032c36
    MiniHipatternsd13434                        { fg="#000000", bg="#d13434", }, -- MiniHipatternsd13434 xxx guifg=#000000 guibg=#d13434
    MiniHipatterns6ab791                        { fg="#000000", bg="#6ab791", }, -- MiniHipatterns6ab791 xxx guifg=#000000 guibg=#6ab791
    MiniHipatterns7f705b                        { fg="#ffffff", bg="#7f705b", }, -- MiniHipatterns7f705b xxx guifg=#ffffff guibg=#7f705b
    MiniHipatterns1697b1                        { fg="#000000", bg="#1697b1", }, -- MiniHipatterns1697b1 xxx guifg=#000000 guibg=#1697b1
    MiniHipatternsff5879                        { fg="#000000", bg="#ff5879", }, -- MiniHipatternsff5879 xxx guifg=#000000 guibg=#ff5879
    MiniHipatterns2fb0ab                        { fg="#000000", bg="#2fb0ab", }, -- MiniHipatterns2fb0ab xxx guifg=#000000 guibg=#2fb0ab
    MiniHipatternsf3f2e7                        { fg="#000000", bg="#f3f2e7", }, -- MiniHipatternsf3f2e7 xxx guifg=#000000 guibg=#f3f2e7
    MiniHipatterns055567                        { fg="#ffffff", bg="#055567", }, -- MiniHipatterns055567 xxx guifg=#ffffff guibg=#055567
    MiniHipatternsef5847                        { fg="#000000", bg="#ef5847", }, -- MiniHipatternsef5847 xxx guifg=#000000 guibg=#ef5847
    MiniHipatterns8ed9a2                        { fg="#000000", bg="#8ed9a2", }, -- MiniHipatterns8ed9a2 xxx guifg=#000000 guibg=#8ed9a2
    MiniHipatternsbcae8f                        { fg="#000000", bg="#bcae8f", }, -- MiniHipatternsbcae8f xxx guifg=#000000 guibg=#bcae8f
    MiniHipatterns45bad2                        { fg="#000000", bg="#45bad2", }, -- MiniHipatterns45bad2 xxx guifg=#000000 guibg=#45bad2
    MiniHipatternsff99a1                        { fg="#000000", bg="#ff99a1", }, -- MiniHipatternsff99a1 xxx guifg=#000000 guibg=#ff99a1
    MiniHipatterns79e4e3                        { fg="#000000", bg="#79e4e3", }, -- MiniHipatterns79e4e3 xxx guifg=#000000 guibg=#79e4e3
    MiniHipatternsfffff4                        { fg="#000000", bg="#fffff4", }, -- MiniHipatternsfffff4 xxx guifg=#000000 guibg=#fffff4
    MiniHipatternse8e8e8                        { fg="#000000", bg="#e8e8e8", }, -- MiniHipatternse8e8e8 xxx guifg=#000000 guibg=#e8e8e8
    MiniHipatternsd4d4d4                        { fg="#000000", bg="#d4d4d4", }, -- MiniHipatternsd4d4d4 xxx guifg=#000000 guibg=#d4d4d4
    MiniHipatternsc0c0c0                        { fg="#000000", bg="#c0c0c0", }, -- MiniHipatternsc0c0c0 xxx guifg=#000000 guibg=#c0c0c0
    MiniHipatterns182a2f                        { fg="#ffffff", bg="#182a2f", }, -- MiniHipatterns182a2f xxx guifg=#ffffff guibg=#182a2f
    MiniHipatterns2c3c41                        { fg="#ffffff", bg="#2c3c41", }, -- MiniHipatterns2c3c41 xxx guifg=#ffffff guibg=#2c3c41
    MiniHipatterns404f53                        { fg="#ffffff", bg="#404f53", }, -- MiniHipatterns404f53 xxx guifg=#ffffff guibg=#404f53
  }
end)
return theme
