-- autogenerated lush spec on Thu 11 Jan 2024 01:12:45 PM CST
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    SpecialKey                                  { fg="#e8e8e8", bg="#18292f", }, -- SpecialKey     xxx ctermfg=81 guifg=#e8e8e8 guibg=#18292f
    TermCursor                                  { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    NonText                                     { gui="bold", fg="#404e53", }, -- NonText        xxx ctermfg=12 gui=bold guifg=#404e53
    EndOfBuffer                                 { NonText }, -- EndOfBuffer    xxx links to NonText
    Whitespace                                  { NonText }, -- Whitespace     xxx links to NonText
    Directory                                   { fg="#33e7e1", }, -- Directory      xxx ctermfg=159 guifg=#33e7e1
    NvimTreeSymlinkFolderName                   { Directory }, -- NvimTreeSymlinkFolderName xxx links to Directory
    NvimTreeOpenedFolderName                    { Directory }, -- NvimTreeOpenedFolderName xxx links to Directory
    NvimTreeEmptyFolderName                     { Directory }, -- NvimTreeEmptyFolderName xxx links to Directory
    NvimTreeFolderName                          { Directory }, -- NvimTreeFolderName xxx links to Directory
    ErrorMsg                                    { gui="bold", fg="#a51d2d", bg="#18292f", }, -- ErrorMsg       xxx ctermfg=15 ctermbg=1 gui=bold guifg=#a51d2d guibg=#18292f
    NvimInvalidSpacing                          { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    IncSearch                                   { gui="reverse", fg="#04161d", bg="#d13434", }, -- IncSearch      xxx cterm=reverse gui=reverse guifg=#04161d guibg=#d13434
    Search                                      { gui="underline", fg="black", bg="yellow", }, -- Search         xxx ctermfg=0 ctermbg=11 gui=underline guifg=Black guibg=Yellow
    CurSearch                                   { Search }, -- CurSearch      xxx links to Search
    QuickFixLine                                { Search }, -- QuickFixLine   xxx links to Search
    Substitute                                  { Search }, -- Substitute     xxx links to Search
    MoreMsg                                     { gui="bold", fg="seagreen", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
    ModeMsg                                     { gui="bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    LineNr                                      { fg="#e8e8e8", bg="#18292f", }, -- LineNr         xxx ctermfg=11 guifg=#e8e8e8 guibg=#18292f
    LineNrAbove                                 { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                                 { LineNr }, -- LineNrBelow    xxx links to LineNr
    NvimTreeLineNr                              { LineNr }, -- NvimTreeLineNr xxx links to LineNr
    CursorLineNr                                { gui="bold", fg="#fcfcfc", bg="#18292f", }, -- CursorLineNr   xxx cterm=underline ctermfg=11 gui=bold guifg=#fcfcfc guibg=#18292f
    NvimTreeCursorLineNr                        { CursorLineNr }, -- NvimTreeCursorLineNr xxx links to CursorLineNr
    Question                                    { gui="bold", fg="green", }, -- Question       xxx ctermfg=121 gui=bold guifg=Green
    StatusLine                                  { gui="bold", fg="#e8e8e8", bg="#2c3b41", }, -- StatusLine     xxx cterm=bold,reverse gui=bold guifg=#e8e8e8 guibg=#2c3b41
    MsgSeparator                                { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    NvimTreeStatusLine                          { StatusLine }, -- NvimTreeStatusLine xxx links to StatusLine
    StatusLineNC                                { gui="reverse", }, -- StatusLineNC   xxx cterm=reverse gui=reverse
    NvimTreeStatusLineNC                        { StatusLineNC }, -- NvimTreeStatusLineNC xxx links to StatusLineNC
    VertSplit                                   { fg="#d4d4d4", bg="#2c3b41", }, -- VertSplit      xxx guifg=#d4d4d4 guibg=#2c3b41
    WinSeparator                                { VertSplit }, -- WinSeparator   xxx links to VertSplit
    Title                                       { gui="bold", fg="#fcfcfc", }, -- Title          xxx ctermfg=225 gui=bold guifg=#fcfcfc
    FloatTitle                                  { Title }, -- FloatTitle     xxx links to Title
    sym"@text.title"                            { Title }, -- @text.title    xxx links to Title
    Visual                                      { bg="darkgrey", }, -- Visual         xxx ctermbg=242 guibg=DarkGrey
    WarningMsg                                  { fg="#fcfcfc", bg="#f8e45c", }, -- WarningMsg     xxx ctermfg=224 guifg=#fcfcfc guibg=#f8e45c
    WildMenu                                    { fg="#1bbcdd", bg="#04161d", }, -- WildMenu       xxx ctermfg=0 ctermbg=11 guifg=#1bbcdd guibg=#04161d
    Folded                                      { fg="#c0c0c0", bg="#04161d", }, -- Folded         xxx ctermfg=14 ctermbg=242 guifg=#c0c0c0 guibg=#04161d
    FoldColumn                                  { fg="#dedbdb", bg="#18292f", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=#dedbdb guibg=#18292f
    CursorLineFold                              { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                     { gui="bold", fg="#fafafa", bg="#123d0f", }, -- DiffAdd        xxx ctermbg=4 gui=bold guifg=#fafafa guibg=#123d0f
    DiffChange                                  { fg="#fafafa", bg="#151b3c", }, -- DiffChange     xxx ctermbg=5 guifg=#fafafa guibg=#151b3c
    DiffDelete                                  { gui="bold", fg="blue", bg="#18292f", }, -- DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=Blue guibg=#18292f
    DiffText                                    { gui="bold", fg="#ffffff", bg="#ff0000", }, -- DiffText       xxx cterm=bold ctermbg=9 gui=bold guifg=#ffffff guibg=#ff0000
    SignColumn                                  { fg="#dedbdb", bg="#18292f", }, -- SignColumn     xxx ctermfg=14 ctermbg=242 guifg=#dedbdb guibg=#18292f
    CursorLineSign                              { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Conceal                                     { fg="lightgrey", bg="darkgrey", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
    SpellBad                                    { sp="red", gui="undercurl", }, -- SpellBad       xxx ctermbg=9 gui=undercurl guisp=Red
    NvimTreeCutHL                               { SpellBad }, -- NvimTreeCutHL  xxx links to SpellBad
    SpellCap                                    { sp="blue", gui="undercurl", }, -- SpellCap       xxx ctermbg=12 gui=undercurl guisp=Blue
    SpellRare                                   { sp="magenta", gui="undercurl", }, -- SpellRare      xxx ctermbg=13 gui=undercurl guisp=Magenta
    NvimTreeCopiedHL                            { SpellRare }, -- NvimTreeCopiedHL xxx links to SpellRare
    SpellLocal                                  { sp="cyan", gui="undercurl", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
    NvimTreeBookmarkHL                          { SpellLocal }, -- NvimTreeBookmarkHL xxx links to SpellLocal
    Pmenu                                       { fg="#fcfcfc", bg="#18292f", }, -- Pmenu          xxx ctermfg=0 ctermbg=13 guifg=#fcfcfc guibg=#18292f
    PmenuKind                                   { Pmenu }, -- PmenuKind      xxx links to Pmenu
    PmenuExtra                                  { Pmenu }, -- PmenuExtra     xxx links to Pmenu
    NormalFloat                                 { Pmenu }, -- NormalFloat    xxx links to Pmenu
    PmenuSel                                    { bg="#2c3b41", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guibg=#2c3b41
    PmenuKindSel                                { PmenuSel }, -- PmenuKindSel   xxx links to PmenuSel
    PmenuExtraSel                               { PmenuSel }, -- PmenuExtraSel  xxx links to PmenuSel
    PmenuSbar                                   { bg="grey", }, -- PmenuSbar      xxx ctermbg=248 guibg=Grey
    PmenuThumb                                  { bg="white", }, -- PmenuThumb     xxx ctermbg=15 guibg=White
    TabLine                                     { gui="underline", bg="darkgrey", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 gui=underline guibg=DarkGrey
    TabLineSel                                  { gui="bold", }, -- TabLineSel     xxx cterm=bold gui=bold
    TabLineFill                                 { gui="reverse", }, -- TabLineFill    xxx cterm=reverse gui=reverse
    CursorColumn                                { bg="#18292f", }, -- CursorColumn   xxx ctermbg=242 guibg=#18292f
    NvimTreeCursorColumn                        { CursorColumn }, -- NvimTreeCursorColumn xxx links to CursorColumn
    CursorLine                                  { bg="#18292f", }, -- CursorLine     xxx cterm=underline guibg=#18292f
    NvimTreeCursorLine                          { CursorLine }, -- NvimTreeCursorLine xxx links to CursorLine
    ColorColumn                                 { bg="#18292f", }, -- ColorColumn    xxx ctermbg=1 guibg=#18292f
    WinBar                                      { gui="bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC                                    { WinBar }, -- WinBarNC       xxx links to WinBar
    Cursor                                      { fg="#04161d", bg="#fcfcfc", }, -- Cursor         xxx guifg=#04161d guibg=#fcfcfc
    lCursor                                     { fg="bg", bg="fg", }, -- lCursor        xxx guifg=bg guibg=fg
    Normal                                      { fg="#fcfcfc", }, -- Normal         xxx guifg=#fcfcfc
    NvimSpacing                                 { Normal }, -- NvimSpacing    xxx links to Normal
    NvimTreeNormal                              { Normal }, -- NvimTreeNormal xxx links to Normal
    NvimTreePopup                               { Normal }, -- NvimTreePopup  xxx links to Normal
    DapUINormal                                 { Normal }, -- DapUINormal    xxx links to Normal
    DapUIVariable                               { Normal }, -- DapUIVariable  xxx links to Normal
    DapUIValue                                  { Normal }, -- DapUIValue     xxx links to Normal
    DapUIFrameName                              { Normal }, -- DapUIFrameName xxx links to Normal
    FloatShadow                                 { blend=80, bg="black", }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                          { blend=100, bg="black", }, -- FloatShadowThrough xxx guibg=Black blend=100
    RedrawDebugNormal                           { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                            { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                         { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                        { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                       { fg="white", bg="red", }, -- Error          xxx ctermfg=15 ctermbg=9 guifg=White guibg=Red
    NvimInvalid                                 { Error }, -- NvimInvalid    xxx links to Error
    luaParenError                               { Error }, -- luaParenError  xxx links to Error
    luaError                                    { Error }, -- luaError       xxx links to Error
    Todo                                        { gui="bold,reverse", fg="#e8e8e8", bg="#04161d", }, -- Todo           xxx ctermfg=0 ctermbg=11 gui=bold,reverse guifg=#e8e8e8 guibg=#04161d
    sym"@text.todo"                             { Todo }, -- @text.todo     xxx links to Todo
    luaTodo                                     { Todo }, -- luaTodo        xxx links to Todo
    String                                      { fg="#1bbcdd", }, -- String         xxx guifg=#1bbcdd
    sym"@string"                                { String }, -- @string        xxx links to String
    NvimString                                  { String }, -- NvimString     xxx links to String
    luaString2                                  { String }, -- luaString2     xxx links to String
    luaString                                   { String }, -- luaString      xxx links to String
    Constant                                    { fg="#33e7e1", }, -- Constant       xxx ctermfg=13 guifg=#33e7e1
    sym"@constant"                              { Constant }, -- @constant      xxx links to Constant
    sym"@lsp.type.enumMember"                   { Constant }, -- @lsp.type.enumMember xxx links to Constant
    luaConstant                                 { Constant }, -- luaConstant    xxx links to Constant
    Character                                   { fg="#33e7e1", }, -- Character      xxx guifg=#33e7e1
    sym"@character"                             { Character }, -- @character     xxx links to Character
    Number                                      { fg="#33e7e1", }, -- Number         xxx guifg=#33e7e1
    sym"@number"                                { Number }, -- @number        xxx links to Number
    NvimNumber                                  { Number }, -- NvimNumber     xxx links to Number
    luaNumber                                   { Number }, -- luaNumber      xxx links to Number
    Boolean                                     { fg="#33e7e1", }, -- Boolean        xxx guifg=#33e7e1
    sym"@boolean"                               { Boolean }, -- @boolean       xxx links to Boolean
    Float                                       { fg="#33e7e1", }, -- Float          xxx guifg=#33e7e1
    sym"@float"                                 { Float }, -- @float         xxx links to Float
    Function                                    { fg="#00c663", }, -- Function       xxx guifg=#00c663
    sym"@function"                              { Function }, -- @function      xxx links to Function
    sym"@method"                                { Function }, -- @method        xxx links to Function
    sym"@lsp.type.decorator"                    { Function }, -- @lsp.type.decorator xxx links to Function
    sym"@lsp.type.function"                     { Function }, -- @lsp.type.function xxx links to Function
    sym"@lsp.type.method"                       { Function }, -- @lsp.type.method xxx links to Function
    luaMetaMethod                               { Function }, -- luaMetaMethod  xxx links to Function
    luaFunction                                 { Function }, -- luaFunction    xxx links to Function
    Identifier                                  { gui="italic", fg="#fca3b3", }, -- Identifier     xxx cterm=bold ctermfg=14 gui=italic guifg=#fca3b3
    sym"@text.reference"                        { Identifier }, -- @text.reference xxx links to Identifier
    sym"@parameter"                             { Identifier }, -- @parameter     xxx links to Identifier
    sym"@field"                                 { Identifier }, -- @field         xxx links to Identifier
    sym"@property"                              { Identifier }, -- @property      xxx links to Identifier
    sym"@variable"                              { Identifier }, -- @variable      xxx links to Identifier
    sym"@namespace"                             { Identifier }, -- @namespace     xxx links to Identifier
    sym"@lsp.type.parameter"                    { Identifier }, -- @lsp.type.parameter xxx links to Identifier
    sym"@lsp.type.property"                     { Identifier }, -- @lsp.type.property xxx links to Identifier
    sym"@lsp.type.variable"                     { Identifier }, -- @lsp.type.variable xxx links to Identifier
    NvimIdentifier                              { Identifier }, -- NvimIdentifier xxx links to Identifier
    luaFunc                                     { Identifier }, -- luaFunc        xxx links to Identifier
    Conditional                                 { fg="#d13434", }, -- Conditional    xxx guifg=#d13434
    sym"@conditional"                           { Conditional }, -- @conditional   xxx links to Conditional
    luaCondElse                                 { Conditional }, -- luaCondElse    xxx links to Conditional
    luaCond                                     { Conditional }, -- luaCond        xxx links to Conditional
    Statement                                   { gui="bold", fg="#d13434", }, -- Statement      xxx ctermfg=11 gui=bold guifg=#d13434
    Repeat                                      { Statement }, -- Repeat         xxx links to Statement
    Exception                                   { Statement }, -- Exception      xxx links to Statement
    luaStatement                                { Statement }, -- luaStatement   xxx links to Statement
    Label                                       { fg="#44b5a1", }, -- Label          xxx guifg=#44b5a1
    sym"@label"                                 { Label }, -- @label         xxx links to Label
    luaLabel                                    { Label }, -- luaLabel       xxx links to Label
    Operator                                    { fg="#d13434", }, -- Operator       xxx guifg=#d13434
    sym"@operator"                              { Operator }, -- @operator      xxx links to Operator
    NvimAssignment                              { Operator }, -- NvimAssignment xxx links to Operator
    NvimOperator                                { Operator }, -- NvimOperator   xxx links to Operator
    luaOperator                                 { Operator }, -- luaOperator    xxx links to Operator
    Keyword                                     { gui="bold", fg="#d13434", }, -- Keyword        xxx gui=bold guifg=#d13434
    sym"@keyword"                               { Keyword }, -- @keyword       xxx links to Keyword
    PreProc                                     { fg="#d13434", }, -- PreProc        xxx ctermfg=81 guifg=#d13434
    Include                                     { PreProc }, -- Include        xxx links to PreProc
    Macro                                       { PreProc }, -- Macro          xxx links to PreProc
    PreCondit                                   { PreProc }, -- PreCondit      xxx links to PreProc
    sym"@preproc"                               { PreProc }, -- @preproc       xxx links to PreProc
    Define                                      { fg="#d13434", }, -- Define         xxx guifg=#d13434
    sym"@constant.macro"                        { Define }, -- @constant.macro xxx links to Define
    sym"@define"                                { Define }, -- @define        xxx links to Define
    StorageClass                                { gui="italic", fg="#fca3b3", }, -- StorageClass   xxx gui=italic guifg=#fca3b3
    sym"@storageclass"                          { StorageClass }, -- @storageclass  xxx links to StorageClass
    Type                                        { gui="bold", fg="#fca3b3", }, -- Type           xxx ctermfg=121 gui=bold guifg=#fca3b3
    Structure                                   { Type }, -- Structure      xxx links to Type
    Typedef                                     { Type }, -- Typedef        xxx links to Type
    sym"@type"                                  { Type }, -- @type          xxx links to Type
    sym"@lsp.type.type"                         { Type }, -- @lsp.type.type xxx links to Type
    NvimNumberPrefix                            { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                             { Type }, -- NvimOptionSigil xxx links to Type
    Tag                                         { fg="#d13434", }, -- Tag            xxx guifg=#d13434
    sym"@tag"                                   { Tag }, -- @tag           xxx links to Tag
    Special                                     { fg="#fcfcfc", }, -- Special        xxx ctermfg=224 guifg=#fcfcfc
    SpecialChar                                 { Special }, -- SpecialChar    xxx links to Special
    Delimiter                                   { Special }, -- Delimiter      xxx links to Special
    SpecialComment                              { Special }, -- SpecialComment xxx links to Special
    Debug                                       { Special }, -- Debug          xxx links to Special
    sym"@constant.builtin"                      { Special }, -- @constant.builtin xxx links to Special
    sym"@function.builtin"                      { Special }, -- @function.builtin xxx links to Special
    sym"@constructor"                           { Special }, -- @constructor   xxx links to Special
    DiagnosticError                             { fg="red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticVirtualTextError                  { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticFloatingError                     { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticSignError                         { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    NvimTreeLspDiagnosticsError                 { DiagnosticError }, -- NvimTreeLspDiagnosticsError xxx links to DiagnosticError
    DiagnosticWarn                              { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticVirtualTextWarn                   { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticFloatingWarn                      { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                          { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    NvimTreeLspDiagnosticsWarning               { DiagnosticWarn }, -- NvimTreeLspDiagnosticsWarning xxx links to DiagnosticWarn
    DiagnosticInfo                              { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticVirtualTextInfo                   { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticFloatingInfo                      { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                          { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    NvimTreeLspDiagnosticsInformation           { DiagnosticInfo }, -- NvimTreeLspDiagnosticsInformation xxx links to DiagnosticInfo
    DiagnosticHint                              { fg="lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticVirtualTextHint                   { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticFloatingHint                      { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticSignHint                          { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    NvimTreeLspDiagnosticsHint                  { DiagnosticHint }, -- NvimTreeLspDiagnosticsHint xxx links to DiagnosticHint
    DiagnosticOk                                { fg="lightgreen", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticVirtualTextOk                     { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticFloatingOk                        { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticSignOk                            { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    DiagnosticUnderlineError                    { sp="red", gui="underline", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                     { sp="orange", gui="underline", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                     { sp="lightblue", gui="underline", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                     { sp="lightgrey", gui="underline", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    DiagnosticUnderlineOk                       { sp="lightgreen", gui="underline", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    DiagnosticDeprecated                        { sp="red", gui="strikethrough", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    Comment                                     { fg="#dedbdb", }, -- Comment        xxx ctermfg=14 guifg=#dedbdb
    DiagnosticUnnecessary                       { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@text.literal"                          { Comment }, -- @text.literal  xxx links to Comment
    sym"@comment"                               { Comment }, -- @comment       xxx links to Comment
    sym"@lsp.type.comment"                      { Comment }, -- @lsp.type.comment xxx links to Comment
    NvimTreeGitIgnored                          { Comment }, -- NvimTreeGitIgnored xxx links to Comment
    luaComment                                  { Comment }, -- luaComment     xxx links to Comment
    Underlined                                  { gui="underline", fg="#80a0ff", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#80a0ff
    sym"@text.uri"                              { Underlined }, -- @text.uri      xxx links to Underlined
    sym"@text.underline"                        { Underlined }, -- @text.underline xxx links to Underlined
    MatchParen                                  { gui="underline", fg="#f8e45c", bg="darkcyan", }, -- MatchParen     xxx ctermbg=6 gui=underline guifg=#f8e45c guibg=DarkCyan
    Ignore                                      { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                           { fg="red", bg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                             { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape               { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape        { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    rubyAttribute                               { fg="#b0d2e5", }, -- rubyAttribute  xxx guifg=#b0d2e5
    rubyLocalVariableOrMethod                   { fg="#44b5a1", }, -- rubyLocalVariableOrMethod xxx guifg=#44b5a1
    rubyGlobalVariable                          { gui="italic", fg="#44b5a1", }, -- rubyGlobalVariable xxx gui=italic guifg=#44b5a1
    rubyInstanceVariable                        { fg="#44b5a1", }, -- rubyInstanceVariable xxx guifg=#44b5a1
    rubyKeyword                                 { fg="#d13434", }, -- rubyKeyword    xxx guifg=#d13434
    rubyKeywordAsMethod                         { gui="bold", fg="#d13434", }, -- rubyKeywordAsMethod xxx gui=bold guifg=#d13434
    rubyClassDeclaration                        { gui="bold", fg="#d13434", }, -- rubyClassDeclaration xxx gui=bold guifg=#d13434
    rubyClass                                   { gui="bold", fg="#d13434", }, -- rubyClass      xxx gui=bold guifg=#d13434
    rubyNumber                                  { fg="#33e7e1", }, -- rubyNumber     xxx guifg=#33e7e1
    pythonBuiltinFunc                           { fg="#b0d2e5", }, -- pythonBuiltinFunc xxx guifg=#b0d2e5
    goBuiltins                                  { fg="#b0d2e5", }, -- goBuiltins     xxx guifg=#b0d2e5
    jsBuiltins                                  { fg="#b0d2e5", }, -- jsBuiltins     xxx guifg=#b0d2e5
    jsFunction                                  { gui="bold", fg="#d13434", }, -- jsFunction     xxx gui=bold guifg=#d13434
    jsGlobalObjects                             { fg="#fca3b3", }, -- jsGlobalObjects xxx guifg=#fca3b3
    jsAssignmentExps                            { fg="#44b5a1", }, -- jsAssignmentExps xxx guifg=#44b5a1
    htmlLink                                    { gui="underline", fg="#44b5a1", }, -- htmlLink       xxx gui=underline guifg=#44b5a1
    htmlStatement                               { fg="#d13434", }, -- htmlStatement  xxx guifg=#d13434
    htmlSpecialTagName                          { fg="#d13434", }, -- htmlSpecialTagName xxx guifg=#d13434
    mkdCode                                     { fg="#b0d2e5", }, -- mkdCode        xxx guifg=#b0d2e5
    CmpItemAbbr                                 { }, -- CmpItemAbbr    xxx cterm= gui=
    CmpItemAbbrDefault                          { fg="#fcfcfc", }, -- CmpItemAbbrDefault xxx guifg=#fcfcfc
    CmpItemAbbrDeprecated                       { }, -- CmpItemAbbrDeprecated xxx cterm= gui=
    CmpItemAbbrDeprecatedDefault                { fg="#dedbdb", }, -- CmpItemAbbrDeprecatedDefault xxx guifg=#dedbdb
    CmpItemAbbrMatch                            { }, -- CmpItemAbbrMatch xxx cterm= gui=
    CmpItemAbbrMatchDefault                     { fg="#fcfcfc", }, -- CmpItemAbbrMatchDefault xxx guifg=#fcfcfc
    CmpItemAbbrMatchFuzzy                       { }, -- CmpItemAbbrMatchFuzzy xxx cterm= gui=
    CmpItemAbbrMatchFuzzyDefault                { fg="#fcfcfc", }, -- CmpItemAbbrMatchFuzzyDefault xxx guifg=#fcfcfc
    CmpItemKind                                 { }, -- CmpItemKind    xxx cterm= gui=
    CmpItemKindPropertyDefault                  { CmpItemKind }, -- CmpItemKindPropertyDefault xxx links to CmpItemKind
    CmpItemKindEnumDefault                      { CmpItemKind }, -- CmpItemKindEnumDefault xxx links to CmpItemKind
    CmpItemKindUnitDefault                      { CmpItemKind }, -- CmpItemKindUnitDefault xxx links to CmpItemKind
    CmpItemKindKeywordDefault                   { CmpItemKind }, -- CmpItemKindKeywordDefault xxx links to CmpItemKind
    CmpItemKindColorDefault                     { CmpItemKind }, -- CmpItemKindColorDefault xxx links to CmpItemKind
    CmpItemKindReferenceDefault                 { CmpItemKind }, -- CmpItemKindReferenceDefault xxx links to CmpItemKind
    CmpItemKindFolderDefault                    { CmpItemKind }, -- CmpItemKindFolderDefault xxx links to CmpItemKind
    CmpItemKindEventDefault                     { CmpItemKind }, -- CmpItemKindEventDefault xxx links to CmpItemKind
    CmpItemKindTextDefault                      { CmpItemKind }, -- CmpItemKindTextDefault xxx links to CmpItemKind
    CmpItemKindOperatorDefault                  { CmpItemKind }, -- CmpItemKindOperatorDefault xxx links to CmpItemKind
    CmpItemKindEnumMemberDefault                { CmpItemKind }, -- CmpItemKindEnumMemberDefault xxx links to CmpItemKind
    CmpItemKindStructDefault                    { CmpItemKind }, -- CmpItemKindStructDefault xxx links to CmpItemKind
    CmpItemKindConstantDefault                  { CmpItemKind }, -- CmpItemKindConstantDefault xxx links to CmpItemKind
    CmpItemKindTypeParameterDefault             { CmpItemKind }, -- CmpItemKindTypeParameterDefault xxx links to CmpItemKind
    CmpItemKindValueDefault                     { CmpItemKind }, -- CmpItemKindValueDefault xxx links to CmpItemKind
    CmpItemKindVariableDefault                  { CmpItemKind }, -- CmpItemKindVariableDefault xxx links to CmpItemKind
    CmpItemKindFileDefault                      { CmpItemKind }, -- CmpItemKindFileDefault xxx links to CmpItemKind
    CmpItemKindMethodDefault                    { CmpItemKind }, -- CmpItemKindMethodDefault xxx links to CmpItemKind
    CmpItemKindFunctionDefault                  { CmpItemKind }, -- CmpItemKindFunctionDefault xxx links to CmpItemKind
    CmpItemKindConstructorDefault               { CmpItemKind }, -- CmpItemKindConstructorDefault xxx links to CmpItemKind
    CmpItemKindFieldDefault                     { CmpItemKind }, -- CmpItemKindFieldDefault xxx links to CmpItemKind
    CmpItemKindSnippetDefault                   { CmpItemKind }, -- CmpItemKindSnippetDefault xxx links to CmpItemKind
    CmpItemKindClassDefault                     { CmpItemKind }, -- CmpItemKindClassDefault xxx links to CmpItemKind
    CmpItemKindInterfaceDefault                 { CmpItemKind }, -- CmpItemKindInterfaceDefault xxx links to CmpItemKind
    CmpItemKindModuleDefault                    { CmpItemKind }, -- CmpItemKindModuleDefault xxx links to CmpItemKind
    CmpItemKindDefault                          { fg="#fcfcfc", }, -- CmpItemKindDefault xxx guifg=#fcfcfc
    CmpItemMenu                                 { }, -- CmpItemMenu    xxx cterm= gui=
    CmpItemMenuDefault                          { fg="#fcfcfc", }, -- CmpItemMenuDefault xxx guifg=#fcfcfc
    CmpItemKindProperty                         { }, -- CmpItemKindProperty xxx cterm= gui=
    CmpItemKindEnum                             { }, -- CmpItemKindEnum xxx cterm= gui=
    CmpItemKindUnit                             { }, -- CmpItemKindUnit xxx cterm= gui=
    CmpItemKindKeyword                          { }, -- CmpItemKindKeyword xxx cterm= gui=
    CmpItemKindColor                            { }, -- CmpItemKindColor xxx cterm= gui=
    CmpItemKindReference                        { }, -- CmpItemKindReference xxx cterm= gui=
    CmpItemKindFolder                           { }, -- CmpItemKindFolder xxx cterm= gui=
    CmpItemKindEvent                            { }, -- CmpItemKindEvent xxx cterm= gui=
    CmpItemKindText                             { }, -- CmpItemKindText xxx cterm= gui=
    CmpItemKindOperator                         { }, -- CmpItemKindOperator xxx cterm= gui=
    CmpItemKindEnumMember                       { }, -- CmpItemKindEnumMember xxx cterm= gui=
    CmpItemKindStruct                           { }, -- CmpItemKindStruct xxx cterm= gui=
    CmpItemKindConstant                         { }, -- CmpItemKindConstant xxx cterm= gui=
    CmpItemKindTypeParameter                    { }, -- CmpItemKindTypeParameter xxx cterm= gui=
    CmpItemKindValue                            { }, -- CmpItemKindValue xxx cterm= gui=
    CmpItemKindVariable                         { }, -- CmpItemKindVariable xxx cterm= gui=
    CmpItemKindFile                             { }, -- CmpItemKindFile xxx cterm= gui=
    CmpItemKindMethod                           { }, -- CmpItemKindMethod xxx cterm= gui=
    CmpItemKindFunction                         { }, -- CmpItemKindFunction xxx cterm= gui=
    CmpItemKindConstructor                      { }, -- CmpItemKindConstructor xxx cterm= gui=
    CmpItemKindField                            { }, -- CmpItemKindField xxx cterm= gui=
    CmpItemKindSnippet                          { }, -- CmpItemKindSnippet xxx cterm= gui=
    CmpItemKindClass                            { }, -- CmpItemKindClass xxx cterm= gui=
    CmpItemKindInterface                        { }, -- CmpItemKindInterface xxx cterm= gui=
    CmpItemKindModule                           { }, -- CmpItemKindModule xxx cterm= gui=
    TelescopePreviewExecute                     { }, -- TelescopePreviewExecute xxx cterm= gui=
    TelescopePreviewWrite                       { }, -- TelescopePreviewWrite xxx cterm= gui=
    TelescopePreviewRead                        { }, -- TelescopePreviewRead xxx cterm= gui=
    TelescopePreviewSocket                      { }, -- TelescopePreviewSocket xxx cterm= gui=
    TelescopePreviewLink                        { }, -- TelescopePreviewLink xxx cterm= gui=
    TelescopePreviewBlock                       { }, -- TelescopePreviewBlock xxx cterm= gui=
    TelescopePreviewDirectory                   { }, -- TelescopePreviewDirectory xxx cterm= gui=
    TelescopePreviewCharDev                     { }, -- TelescopePreviewCharDev xxx cterm= gui=
    TelescopePreviewPipe                        { }, -- TelescopePreviewPipe xxx cterm= gui=
    TelescopePreviewMatch                       { }, -- TelescopePreviewMatch xxx cterm= gui=
    TelescopePreviewLine                        { }, -- TelescopePreviewLine xxx cterm= gui=
    TelescopePromptPrefix                       { }, -- TelescopePromptPrefix xxx cterm= gui=
    TelescopeMatching                           { }, -- TelescopeMatching xxx cterm= gui=
    TelescopePromptCounter                      { }, -- TelescopePromptCounter xxx cterm= gui=
    TelescopePreviewTitle                       { }, -- TelescopePreviewTitle xxx cterm= gui=
    TelescopeTitle                              { }, -- TelescopeTitle xxx cterm= gui=
    TelescopeBorder                             { }, -- TelescopeBorder xxx cterm= gui=
    TelescopeResultsTitle                       { }, -- TelescopeResultsTitle xxx cterm= gui=
    TelescopePromptTitle                        { }, -- TelescopePromptTitle xxx cterm= gui=
    TelescopeNormal                             { }, -- TelescopeNormal xxx cterm= gui=
    TelescopePreviewBorder                      { }, -- TelescopePreviewBorder xxx cterm= gui=
    TelescopeResultsBorder                      { }, -- TelescopeResultsBorder xxx cterm= gui=
    TelescopePromptBorder                       { }, -- TelescopePromptBorder xxx cterm= gui=
    TelescopeResultsNormal                      { }, -- TelescopeResultsNormal xxx cterm= gui=
    TelescopePromptNormal                       { }, -- TelescopePromptNormal xxx cterm= gui=
    TelescopeMultiIcon                          { }, -- TelescopeMultiIcon xxx cterm= gui=
    TelescopeMultiSelection                     { }, -- TelescopeMultiSelection xxx cterm= gui=
    TelescopeSelectionCaret                     { }, -- TelescopeSelectionCaret xxx cterm= gui=
    TelescopeSelection                          { }, -- TelescopeSelection xxx cterm= gui=
    TelescopeResultsDiffAdd                     { }, -- TelescopeResultsDiffAdd xxx cterm= gui=
    TelescopeResultsDiffChange                  { }, -- TelescopeResultsDiffChange xxx cterm= gui=
    TelescopeResultsSpecialComment              { }, -- TelescopeResultsSpecialComment xxx cterm= gui=
    TelescopeResultsComment                     { }, -- TelescopeResultsComment xxx cterm= gui=
    TelescopeResultsNumber                      { }, -- TelescopeResultsNumber xxx cterm= gui=
    TelescopeResultsIdentifier                  { }, -- TelescopeResultsIdentifier xxx cterm= gui=
    TelescopeResultsLineNr                      { }, -- TelescopeResultsLineNr xxx cterm= gui=
    TelescopeResultsVariable                    { }, -- TelescopeResultsVariable xxx cterm= gui=
    TelescopeResultsDiffUntracked               { }, -- TelescopeResultsDiffUntracked xxx cterm= gui=
    TelescopeResultsStruct                      { }, -- TelescopeResultsStruct xxx cterm= gui=
    TelescopeResultsOperator                    { }, -- TelescopeResultsOperator xxx cterm= gui=
    TelescopeResultsMethod                      { }, -- TelescopeResultsMethod xxx cterm= gui=
    TelescopeResultsFunction                    { }, -- TelescopeResultsFunction xxx cterm= gui=
    TelescopeResultsField                       { }, -- TelescopeResultsField xxx cterm= gui=
    TelescopeResultsConstant                    { }, -- TelescopeResultsConstant xxx cterm= gui=
    TelescopeResultsClass                       { }, -- TelescopeResultsClass xxx cterm= gui=
    TelescopePreviewMessageFillchar             { }, -- TelescopePreviewMessageFillchar xxx cterm= gui=
    TelescopePreviewMessage                     { }, -- TelescopePreviewMessage xxx cterm= gui=
    TelescopePreviewNormal                      { }, -- TelescopePreviewNormal xxx cterm= gui=
    TelescopePreviewDate                        { }, -- TelescopePreviewDate xxx cterm= gui=
    TelescopeResultsDiffDelete                  { }, -- TelescopeResultsDiffDelete xxx cterm= gui=
    TelescopePreviewGroup                       { }, -- TelescopePreviewGroup xxx cterm= gui=
    TelescopePreviewUser                        { }, -- TelescopePreviewUser xxx cterm= gui=
    TelescopePreviewSize                        { }, -- TelescopePreviewSize xxx cterm= gui=
    TelescopePreviewSticky                      { }, -- TelescopePreviewSticky xxx cterm= gui=
    TelescopePreviewHyphen                      { }, -- TelescopePreviewHyphen xxx cterm= gui=
    LspInfoTip                                  { }, -- LspInfoTip     xxx cterm= gui=
    LspInfoList                                 { }, -- LspInfoList    xxx cterm= gui=
    LspInfoBorder                               { }, -- LspInfoBorder  xxx cterm= gui=
    LspInfoFiletype                             { }, -- LspInfoFiletype xxx cterm= gui=
    LspInfoTitle                                { }, -- LspInfoTitle   xxx cterm= gui=
    NvimTreeImageFile                           { gui="bold", fg="#b0d2e5", }, -- NvimTreeImageFile xxx gui=bold guifg=#b0d2e5
    NvimTreeSpecialFile                         { gui="bold,underline", fg="#404e53", }, -- NvimTreeSpecialFile xxx gui=bold,underline guifg=#404e53
    NvimTreeExecFile                            { gui="bold", fg="#d13434", }, -- NvimTreeExecFile xxx gui=bold guifg=#d13434
    NvimTreeRootFolder                          { fg="#b0d2e5", }, -- NvimTreeRootFolder xxx guifg=#b0d2e5
    NvimTreeFolderIcon                          { fg="#8094b4", }, -- NvimTreeFolderIcon xxx guifg=#8094b4
    NvimTreeClosedFolderIcon                    { NvimTreeFolderIcon }, -- NvimTreeClosedFolderIcon xxx links to NvimTreeFolderIcon
    NvimTreeOpenedFolderIcon                    { NvimTreeFolderIcon }, -- NvimTreeOpenedFolderIcon xxx links to NvimTreeFolderIcon
    NvimTreeSymlink                             { gui="bold", fg="#d4d4d4", }, -- NvimTreeSymlink xxx gui=bold guifg=#d4d4d4
    NvimTreeIndentMarker                        { fg="#8094b4", }, -- NvimTreeIndentMarker xxx guifg=#8094b4
    NvimTreeBookmark                            { fg="#d13434", }, -- NvimTreeBookmark xxx guifg=#d13434
    NvimTreeLiveFilterValue                     { gui="bold", }, -- NvimTreeLiveFilterValue xxx gui=bold
    NvimTreeLiveFilterPrefix                    { gui="bold", fg="#b0d2e5", }, -- NvimTreeLiveFilterPrefix xxx gui=bold guifg=#b0d2e5
    NvimTreeWindowPicker                        { gui="bold", fg="#ededed", bg="#4493c8", }, -- NvimTreeWindowPicker xxx gui=bold guifg=#ededed guibg=#4493c8
    NvimTreeGitNew                              { fg="#404e53", }, -- NvimTreeGitNew xxx guifg=#404e53
    NvimTreeFileNew                             { NvimTreeGitNew }, -- NvimTreeFileNew xxx links to NvimTreeGitNew
    NvimTreeGitRenamed                          { fg="#b0d2e5", }, -- NvimTreeGitRenamed xxx guifg=#b0d2e5
    NvimTreeFileRenamed                         { NvimTreeGitRenamed }, -- NvimTreeFileRenamed xxx links to NvimTreeGitRenamed
    NvimTreeGitMerge                            { fg="#44b5a1", }, -- NvimTreeGitMerge xxx guifg=#44b5a1
    NvimTreeFileMerge                           { NvimTreeGitMerge }, -- NvimTreeFileMerge xxx links to NvimTreeGitMerge
    NvimTreeGitStaged                           { fg="#d13434", }, -- NvimTreeGitStaged xxx guifg=#d13434
    NvimTreeFileStaged                          { NvimTreeGitStaged }, -- NvimTreeFileStaged xxx links to NvimTreeGitStaged
    NvimTreeGitDeleted                          { fg="#f8e45c", }, -- NvimTreeGitDeleted xxx guifg=#f8e45c
    NvimTreeFileDeleted                         { NvimTreeGitDeleted }, -- NvimTreeFileDeleted xxx links to NvimTreeGitDeleted
    NvimTreeGitDirty                            { fg="#f8e45c", }, -- NvimTreeGitDirty xxx guifg=#f8e45c
    NvimTreeFileDirty                           { NvimTreeGitDirty }, -- NvimTreeFileDirty xxx links to NvimTreeGitDirty
    NvimTreeModifiedFile                        { fg="#d13434", }, -- NvimTreeModifiedFile xxx guifg=#d13434
    NvimTreeOpenedFile                          { gui="bold", fg="#d13434", }, -- NvimTreeOpenedFile xxx gui=bold guifg=#d13434
    NvimTreeOpenedFileIcon                      { NvimTreeOpenedFile }, -- NvimTreeOpenedFileIcon xxx links to NvimTreeOpenedFile
    DevIconVerilog                              { fg="#019833", }, -- DevIconVerilog xxx ctermfg=28 guifg=#019833
    DevIconNPMrc                                { fg="#e8274b", }, -- DevIconNPMrc   xxx ctermfg=197 guifg=#e8274b
    DevIconConfigRu                             { fg="#701516", }, -- DevIconConfigRu xxx ctermfg=52 guifg=#701516
    DevIconMixLock                              { fg="#a074c4", }, -- DevIconMixLock xxx ctermfg=140 guifg=#a074c4
    DevIconClojureDart                          { fg="#519aba", }, -- DevIconClojureDart xxx ctermfg=74 guifg=#519aba
    DevIconEditorConfig                         { fg="#ffffff", }, -- DevIconEditorConfig xxx ctermfg=231 guifg=#ffffff
    DevIconAzureCli                             { fg="#0078d4", }, -- DevIconAzureCli xxx ctermfg=32 guifg=#0078d4
    DevIconNodeModules                          { fg="#e8274b", }, -- DevIconNodeModules xxx ctermfg=197 guifg=#e8274b
    DevIconPackageJson                          { fg="#e8274b", }, -- DevIconPackageJson xxx ctermfg=197 guifg=#e8274b
    DevIconSvelteConfig                         { fg="#ff3e00", }, -- DevIconSvelteConfig xxx ctermfg=196 guifg=#ff3e00
    DevIconRakefile                             { fg="#701516", }, -- DevIconRakefile xxx ctermfg=52 guifg=#701516
    sym"DevIconPy.typed"                        { fg="#ffbc03", }, -- DevIconPy.typed xxx ctermfg=214 guifg=#ffbc03
    DevIconPackageLockJson                      { fg="#7a0d21", }, -- DevIconPackageLockJson xxx ctermfg=52 guifg=#7a0d21
    DevIconScss                                 { fg="#f55385", }, -- DevIconScss    xxx ctermfg=204 guifg=#f55385
    DevIconMakefile                             { fg="#6d8086", }, -- DevIconMakefile xxx ctermfg=66 guifg=#6d8086
    DevIconFavicon                              { fg="#cbcb41", }, -- DevIconFavicon xxx ctermfg=185 guifg=#cbcb41
    DevIconScala                                { fg="#cc3e44", }, -- DevIconScala   xxx ctermfg=167 guifg=#cc3e44
    DevIconDockerfile                           { fg="#458ee6", }, -- DevIconDockerfile xxx ctermfg=68 guifg=#458ee6
    DevIconCMakeLists                           { fg="#6d8086", }, -- DevIconCMakeLists xxx ctermfg=66 guifg=#6d8086
    DevIconSass                                 { fg="#f55385", }, -- DevIconSass    xxx ctermfg=204 guifg=#f55385
    DevIconXml                                  { fg="#e37933", }, -- DevIconXml     xxx ctermfg=166 guifg=#e37933
    DevIconVimrc                                { fg="#019833", }, -- DevIconVimrc   xxx ctermfg=28 guifg=#019833
    DevIconRs                                   { fg="#dea584", }, -- DevIconRs      xxx ctermfg=216 guifg=#dea584
    DevIconBazelWorkspace                       { fg="#89e051", }, -- DevIconBazelWorkspace xxx ctermfg=113 guifg=#89e051
    DevIconRake                                 { fg="#701516", }, -- DevIconRake    xxx ctermfg=52 guifg=#701516
    DevIconPp                                   { fg="#ffa61a", }, -- DevIconPp      xxx ctermfg=214 guifg=#ffa61a
    DevIconGemspec                              { fg="#701516", }, -- DevIconGemspec xxx ctermfg=52 guifg=#701516
    DevIconSettingsJson                         { fg="#854cc7", }, -- DevIconSettingsJson xxx ctermfg=98 guifg=#854cc7
    DevIconLuaurc                               { fg="#00a2ff", }, -- DevIconLuaurc  xxx ctermfg=75 guifg=#00a2ff
    DevIconGvimrc                               { fg="#019833", }, -- DevIconGvimrc  xxx ctermfg=28 guifg=#019833
    DevIconSql                                  { fg="#dad8d8", }, -- DevIconSql     xxx ctermfg=188 guifg=#dad8d8
    DevIconTex                                  { fg="#3d6117", }, -- DevIconTex     xxx ctermfg=22 guifg=#3d6117
    DevIconTerraform                            { fg="#5f43e9", }, -- DevIconTerraform xxx ctermfg=93 guifg=#5f43e9
    DevIconTxt                                  { fg="#89e051", }, -- DevIconTxt     xxx ctermfg=113 guifg=#89e051
    DevIconSml                                  { fg="#e37933", }, -- DevIconSml     xxx ctermfg=166 guifg=#e37933
    DevIconCobol                                { fg="#005ca5", }, -- DevIconCobol   xxx ctermfg=25 guifg=#005ca5
    DevIconDsStore                              { fg="#41535b", }, -- DevIconDsStore xxx ctermfg=239 guifg=#41535b
    DevIconPm                                   { fg="#519aba", }, -- DevIconPm      xxx ctermfg=74 guifg=#519aba
    DevIconRmd                                  { fg="#519aba", }, -- DevIconRmd     xxx ctermfg=74 guifg=#519aba
    DevIconTcl                                  { fg="#1e5cb3", }, -- DevIconTcl     xxx ctermfg=25 guifg=#1e5cb3
    DevIconJsonc                                { fg="#cbcb41", }, -- DevIconJsonc   xxx ctermfg=185 guifg=#cbcb41
    DevIconDesktopEntry                         { fg="#563d7c", }, -- DevIconDesktopEntry xxx ctermfg=54 guifg=#563d7c
    DevIconReScriptInterface                    { fg="#f55385", }, -- DevIconReScriptInterface xxx ctermfg=204 guifg=#f55385
    DevIconConfiguration                        { fg="#ececec", }, -- DevIconConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconReScript                             { fg="#cc3e44", }, -- DevIconReScript xxx ctermfg=167 guifg=#cc3e44
    DevIconGitLogo                              { fg="#f14c28", }, -- DevIconGitLogo xxx ctermfg=196 guifg=#f14c28
    DevIconTerminal                             { fg="#31b53e", }, -- DevIconTerminal xxx ctermfg=34 guifg=#31b53e
    DevIconCMake                                { fg="#6d8086", }, -- DevIconCMake   xxx ctermfg=66 guifg=#6d8086
    DevIconEex                                  { fg="#a074c4", }, -- DevIconEex     xxx ctermfg=140 guifg=#a074c4
    DevIconProlog                               { fg="#e4b854", }, -- DevIconProlog  xxx ctermfg=179 guifg=#e4b854
    DevIconTs                                   { fg="#519aba", }, -- DevIconTs      xxx ctermfg=74 guifg=#519aba
    DevIconR                                    { fg="#2266ba", }, -- DevIconR       xxx ctermfg=25 guifg=#2266ba
    DevIconPy                                   { fg="#ffbc03", }, -- DevIconPy      xxx ctermfg=214 guifg=#ffbc03
    DevIconPxd                                  { fg="#5aa7e4", }, -- DevIconPxd     xxx ctermfg=39 guifg=#5aa7e4
    DevIconHtm                                  { fg="#e34c26", }, -- DevIconHtm     xxx ctermfg=196 guifg=#e34c26
    DevIconZsh                                  { fg="#89e051", }, -- DevIconZsh     xxx ctermfg=113 guifg=#89e051
    DevIconH                                    { fg="#a074c4", }, -- DevIconH       xxx ctermfg=140 guifg=#a074c4
    DevIconIni                                  { fg="#6d8086", }, -- DevIconIni     xxx ctermfg=66 guifg=#6d8086
    DevIconPsScriptfile                         { fg="#4273ca", }, -- DevIconPsScriptfile xxx ctermfg=68 guifg=#4273ca
    DevIconBat                                  { fg="#c1f12e", }, -- DevIconBat     xxx ctermfg=191 guifg=#c1f12e
    DevIconToml                                 { fg="#ffffff", }, -- DevIconToml    xxx ctermfg=231 guifg=#ffffff
    DevIconTestJs                               { fg="#cbcb41", }, -- DevIconTestJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconAi                                   { fg="#cbcb41", }, -- DevIconAi      xxx ctermfg=185 guifg=#cbcb41
    DevIconD                                    { fg="#427819", }, -- DevIconD       xxx ctermfg=28 guifg=#427819
    DevIconCPlusPlus                            { fg="#f34b7d", }, -- DevIconCPlusPlus xxx ctermfg=204 guifg=#f34b7d
    DevIconDart                                 { fg="#03589c", }, -- DevIconDart    xxx ctermfg=25 guifg=#03589c
    DevIconDb                                   { fg="#dad8d8", }, -- DevIconDb      xxx ctermfg=188 guifg=#dad8d8
    DevIconClojure                              { fg="#8dc149", }, -- DevIconClojure xxx ctermfg=113 guifg=#8dc149
    DevIconMdx                                  { fg="#519aba", }, -- DevIconMdx     xxx ctermfg=74 guifg=#519aba
    DevIconElm                                  { fg="#519aba", }, -- DevIconElm     xxx ctermfg=74 guifg=#519aba
    DevIconWasm                                 { fg="#5c4cdb", }, -- DevIconWasm    xxx ctermfg=62 guifg=#5c4cdb
    DevIconPdf                                  { fg="#b30b00", }, -- DevIconPdf     xxx ctermfg=124 guifg=#b30b00
    DevIconDump                                 { fg="#dad8d8", }, -- DevIconDump    xxx ctermfg=188 guifg=#dad8d8
    DevIconLeex                                 { fg="#a074c4", }, -- DevIconLeex    xxx ctermfg=140 guifg=#a074c4
    DevIconVlang                                { fg="#5d87bf", }, -- DevIconVlang   xxx ctermfg=67 guifg=#5d87bf
    DevIconTypeScriptReactSpec                  { fg="#1354bf", }, -- DevIconTypeScriptReactSpec xxx ctermfg=26 guifg=#1354bf
    DevIconCsv                                  { fg="#89e051", }, -- DevIconCsv     xxx ctermfg=113 guifg=#89e051
    DevIconCss                                  { fg="#42a5f5", }, -- DevIconCss     xxx ctermfg=75 guifg=#42a5f5
    DevIconMl                                   { fg="#e37933", }, -- DevIconMl      xxx ctermfg=166 guifg=#e37933
    DevIconRazorPage                            { fg="#512bd4", }, -- DevIconRazorPage xxx ctermfg=56 guifg=#512bd4
    DevIconNim                                  { fg="#f3d400", }, -- DevIconNim     xxx ctermfg=220 guifg=#f3d400
    DevIconClojureC                             { fg="#8dc149", }, -- DevIconClojureC xxx ctermfg=113 guifg=#8dc149
    DevIconClojureJS                            { fg="#519aba", }, -- DevIconClojureJS xxx ctermfg=74 guifg=#519aba
    DevIconCrystal                              { fg="#c8c8c8", }, -- DevIconCrystal xxx ctermfg=251 guifg=#c8c8c8
    DevIconRss                                  { fg="#fb9d3b", }, -- DevIconRss     xxx ctermfg=215 guifg=#fb9d3b
    DevIconTrueTypeFont                         { fg="#ececec", }, -- DevIconTrueTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconLog                                  { fg="#ffffff", }, -- DevIconLog     xxx ctermfg=231 guifg=#ffffff
    DevIconHxx                                  { fg="#a074c4", }, -- DevIconHxx     xxx ctermfg=140 guifg=#a074c4
    DevIconBibTeX                               { fg="#cbcb41", }, -- DevIconBibTeX  xxx ctermfg=185 guifg=#cbcb41
    DevIconEnv                                  { fg="#faf743", }, -- DevIconEnv     xxx ctermfg=227 guifg=#faf743
    DevIconGodotProject                         { fg="#6d8086", }, -- DevIconGodotProject xxx ctermfg=66 guifg=#6d8086
    DevIconFlac                                 { fg="#66d8ef", }, -- DevIconFlac    xxx ctermfg=45 guifg=#66d8ef
    DevIconEjs                                  { fg="#cbcb41", }, -- DevIconEjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconDropbox                              { fg="#0061fe", }, -- DevIconDropbox xxx ctermfg=27 guifg=#0061fe
    DevIconLua                                  { fg="#51a0cf", }, -- DevIconLua     xxx ctermfg=74 guifg=#51a0cf
    DevIconDrools                               { fg="#ffafaf", }, -- DevIconDrools  xxx ctermfg=217 guifg=#ffafaf
    DevIconDocx                                 { fg="#185abd", }, -- DevIconDocx    xxx ctermfg=26 guifg=#185abd
    DevIconCson                                 { fg="#cbcb41", }, -- DevIconCson    xxx ctermfg=185 guifg=#cbcb41
    DevIconCp                                   { fg="#519aba", }, -- DevIconCp      xxx ctermfg=74 guifg=#519aba
    DevIconBmp                                  { fg="#a074c4", }, -- DevIconBmp     xxx ctermfg=140 guifg=#a074c4
    DevIconAac                                  { fg="#66d8ef", }, -- DevIconAac     xxx ctermfg=45 guifg=#66d8ef
    DevIconVagrantfile                          { fg="#1563ff", }, -- DevIconVagrantfile xxx ctermfg=27 guifg=#1563ff
    DevIconLicense                              { fg="#cbcb41", }, -- DevIconLicense xxx ctermfg=185 guifg=#cbcb41
    DevIconLuau                                 { fg="#00a2ff", }, -- DevIconLuau    xxx ctermfg=75 guifg=#00a2ff
    DevIconGemfile                              { fg="#701516", }, -- DevIconGemfile xxx ctermfg=52 guifg=#701516
    DevIconVue                                  { fg="#8dc149", }, -- DevIconVue     xxx ctermfg=113 guifg=#8dc149
    DevIconBazel                                { fg="#89e051", }, -- DevIconBazel   xxx ctermfg=113 guifg=#89e051
    DevIconCoffee                               { fg="#cbcb41", }, -- DevIconCoffee  xxx ctermfg=185 guifg=#cbcb41
    DevIconImportConfiguration                  { fg="#ececec", }, -- DevIconImportConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconBazelBuild                           { fg="#89e051", }, -- DevIconBazelBuild xxx ctermfg=113 guifg=#89e051
    DevIconVHDL                                 { fg="#019833", }, -- DevIconVHDL    xxx ctermfg=28 guifg=#019833
    DevIconDefault                              { fg="#6d8086", }, -- DevIconDefault xxx ctermfg=66 guifg=#6d8086
    DevIconPyc                                  { fg="#ffe291", }, -- DevIconPyc     xxx ctermfg=222 guifg=#ffe291
    DevIconHh                                   { fg="#a074c4", }, -- DevIconHh      xxx ctermfg=140 guifg=#a074c4
    DevIconPxi                                  { fg="#5aa7e4", }, -- DevIconPxi     xxx ctermfg=39 guifg=#5aa7e4
    DevIconCSharpProject                        { fg="#512bd4", }, -- DevIconCSharpProject xxx ctermfg=56 guifg=#512bd4
    DevIconPsd                                  { fg="#519aba", }, -- DevIconPsd     xxx ctermfg=74 guifg=#519aba
    DevIconMts                                  { fg="#519aba", }, -- DevIconMts     xxx ctermfg=74 guifg=#519aba
    DevIconTextResource                         { fg="#cbcb41", }, -- DevIconTextResource xxx ctermfg=185 guifg=#cbcb41
    DevIconNix                                  { fg="#7ebae4", }, -- DevIconNix     xxx ctermfg=110 guifg=#7ebae4
    DevIconAwk                                  { fg="#4d5a5e", }, -- DevIconAwk     xxx ctermfg=240 guifg=#4d5a5e
    DevIconGo                                   { fg="#519aba", }, -- DevIconGo      xxx ctermfg=74 guifg=#519aba
    DevIconQuery                                { fg="#90a850", }, -- DevIconQuery   xxx ctermfg=107 guifg=#90a850
    DevIconMarkdown                             { fg="#519aba", }, -- DevIconMarkdown xxx ctermfg=74 guifg=#519aba
    DevIconOrgMode                              { fg="#77aa99", }, -- DevIconOrgMode xxx ctermfg=73 guifg=#77aa99
    DevIconZig                                  { fg="#f69a1b", }, -- DevIconZig     xxx ctermfg=172 guifg=#f69a1b
    DevIconBrewfile                             { fg="#701516", }, -- DevIconBrewfile xxx ctermfg=52 guifg=#701516
    DevIconHrl                                  { fg="#b83998", }, -- DevIconHrl     xxx ctermfg=163 guifg=#b83998
    DevIconTwig                                 { fg="#8dc149", }, -- DevIconTwig    xxx ctermfg=113 guifg=#8dc149
    DevIconCpp                                  { fg="#519aba", }, -- DevIconCpp     xxx ctermfg=74 guifg=#519aba
    DevIconSln                                  { fg="#854cc7", }, -- DevIconSln     xxx ctermfg=98 guifg=#854cc7
    DevIconPsManifestfile                       { fg="#6975c4", }, -- DevIconPsManifestfile xxx ctermfg=68 guifg=#6975c4
    DevIconPsScriptModulefile                   { fg="#6975c4", }, -- DevIconPsScriptModulefile xxx ctermfg=68 guifg=#6975c4
    DevIconWebmanifest                          { fg="#f1e05a", }, -- DevIconWebmanifest xxx ctermfg=185 guifg=#f1e05a
    DevIconBashrc                               { fg="#89e051", }, -- DevIconBashrc  xxx ctermfg=113 guifg=#89e051
    DevIconTsx                                  { fg="#1354bf", }, -- DevIconTsx     xxx ctermfg=26 guifg=#1354bf
    DevIconXaml                                 { fg="#512bd4", }, -- DevIconXaml    xxx ctermfg=56 guifg=#512bd4
    DevIconCts                                  { fg="#519aba", }, -- DevIconCts     xxx ctermfg=74 guifg=#519aba
    DevIconHurl                                 { fg="#ff0288", }, -- DevIconHurl    xxx ctermfg=198 guifg=#ff0288
    DevIconPhp                                  { fg="#a074c4", }, -- DevIconPhp     xxx ctermfg=140 guifg=#a074c4
    DevIconGruntfile                            { fg="#e37933", }, -- DevIconGruntfile xxx ctermfg=166 guifg=#e37933
    DevIconNPMIgnore                            { fg="#e8274b", }, -- DevIconNPMIgnore xxx ctermfg=197 guifg=#e8274b
    DevIconKotlin                               { fg="#7f52ff", }, -- DevIconKotlin  xxx ctermfg=99 guifg=#7f52ff
    DevIconKotlinScript                         { fg="#7f52ff", }, -- DevIconKotlinScript xxx ctermfg=99 guifg=#7f52ff
    DevIconJsx                                  { fg="#20c2e3", }, -- DevIconJsx     xxx ctermfg=45 guifg=#20c2e3
    DevIconScheme                               { fg="#000000", }, -- DevIconScheme  xxx ctermfg=16 guifg=#000000
    DevIconCjs                                  { fg="#cbcb41", }, -- DevIconCjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconSh                                   { fg="#4d5a5e", }, -- DevIconSh      xxx ctermfg=240 guifg=#4d5a5e
    DevIconWebOpenFontFormat                    { fg="#ececec", }, -- DevIconWebOpenFontFormat xxx ctermfg=255 guifg=#ececec
    DevIconJs                                   { fg="#cbcb41", }, -- DevIconJs      xxx ctermfg=185 guifg=#cbcb41
    DevIconMjs                                  { fg="#f1e05a", }, -- DevIconMjs     xxx ctermfg=185 guifg=#f1e05a
    DevIconJson5                                { fg="#cbcb41", }, -- DevIconJson5   xxx ctermfg=185 guifg=#cbcb41
    DevIconGitlabCI                             { fg="#e24329", }, -- DevIconGitlabCI xxx ctermfg=196 guifg=#e24329
    DevIconFs                                   { fg="#519aba", }, -- DevIconFs      xxx ctermfg=74 guifg=#519aba
    DevIconVim                                  { fg="#019833", }, -- DevIconVim     xxx ctermfg=28 guifg=#019833
    DevIconJava                                 { fg="#cc3e44", }, -- DevIconJava    xxx ctermfg=167 guifg=#cc3e44
    DevIconCsh                                  { fg="#4d5a5e", }, -- DevIconCsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconPrisma                               { fg="#ffffff", }, -- DevIconPrisma  xxx ctermfg=231 guifg=#ffffff
    DevIconNswag                                { fg="#85ea2d", }, -- DevIconNswag   xxx ctermfg=112 guifg=#85ea2d
    DevIconEpp                                  { fg="#ffa61a", }, -- DevIconEpp     xxx ctermfg=214 guifg=#ffa61a
    DevIconBzl                                  { fg="#89e051", }, -- DevIconBzl     xxx ctermfg=113 guifg=#89e051
    DevIconMli                                  { fg="#e37933", }, -- DevIconMli     xxx ctermfg=166 guifg=#e37933
    DevIconAvif                                 { fg="#a074c4", }, -- DevIconAvif    xxx ctermfg=140 guifg=#a074c4
    DevIconMustache                             { fg="#e37933", }, -- DevIconMustache xxx ctermfg=166 guifg=#e37933
    DevIconFsharp                               { fg="#519aba", }, -- DevIconFsharp  xxx ctermfg=74 guifg=#519aba
    DevIconWav                                  { fg="#66d8ef", }, -- DevIconWav     xxx ctermfg=45 guifg=#66d8ef
    DevIconPyo                                  { fg="#ffe291", }, -- DevIconPyo     xxx ctermfg=222 guifg=#ffe291
    DevIconLhs                                  { fg="#a074c4", }, -- DevIconLhs     xxx ctermfg=140 guifg=#a074c4
    DevIconStyl                                 { fg="#8dc149", }, -- DevIconStyl    xxx ctermfg=113 guifg=#8dc149
    DevIconFsx                                  { fg="#519aba", }, -- DevIconFsx     xxx ctermfg=74 guifg=#519aba
    DevIconGDScript                             { fg="#6d8086", }, -- DevIconGDScript xxx ctermfg=66 guifg=#6d8086
    DevIconRproj                                { fg="#358a5b", }, -- DevIconRproj   xxx ctermfg=29 guifg=#358a5b
    DevIconConf                                 { fg="#6d8086", }, -- DevIconConf    xxx ctermfg=66 guifg=#6d8086
    DevIconOgg                                  { fg="#66d8ef", }, -- DevIconOgg     xxx ctermfg=45 guifg=#66d8ef
    DevIconOPUS                                 { fg="#f88a02", }, -- DevIconOPUS    xxx ctermfg=208 guifg=#f88a02
    DevIconOpenTypeFont                         { fg="#ececec", }, -- DevIconOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconGitModules                           { fg="#41535b", }, -- DevIconGitModules xxx ctermfg=239 guifg=#41535b
    DevIconPpt                                  { fg="#cb4a32", }, -- DevIconPpt     xxx ctermfg=160 guifg=#cb4a32
    DevIconSystemVerilog                        { fg="#019833", }, -- DevIconSystemVerilog xxx ctermfg=28 guifg=#019833
    DevIconGitIgnore                            { fg="#41535b", }, -- DevIconGitIgnore xxx ctermfg=239 guifg=#41535b
    DevIconSwift                                { fg="#e37933", }, -- DevIconSwift   xxx ctermfg=166 guifg=#e37933
    DevIconSvg                                  { fg="#ffb13b", }, -- DevIconSvg     xxx ctermfg=214 guifg=#ffb13b
    DevIconSvelte                               { fg="#ff3e00", }, -- DevIconSvelte  xxx ctermfg=196 guifg=#ff3e00
    DevIconBinaryGLTF                           { fg="#ffb13b", }, -- DevIconBinaryGLTF xxx ctermfg=214 guifg=#ffb13b
    DevIconHeex                                 { fg="#a074c4", }, -- DevIconHeex    xxx ctermfg=140 guifg=#a074c4
    DevIconCxx                                  { fg="#519aba", }, -- DevIconCxx     xxx ctermfg=74 guifg=#519aba
    DevIconFish                                 { fg="#4d5a5e", }, -- DevIconFish    xxx ctermfg=240 guifg=#4d5a5e
    DevIconDiff                                 { fg="#41535b", }, -- DevIconDiff    xxx ctermfg=239 guifg=#41535b
    DevIconSpecTs                               { fg="#519aba", }, -- DevIconSpecTs  xxx ctermfg=74 guifg=#519aba
    DevIconJson                                 { fg="#cbcb41", }, -- DevIconJson    xxx ctermfg=185 guifg=#cbcb41
    DevIconCs                                   { fg="#596706", }, -- DevIconCs      xxx ctermfg=58 guifg=#596706
    DevIconExs                                  { fg="#a074c4", }, -- DevIconExs     xxx ctermfg=140 guifg=#a074c4
    DevIconWebpack                              { fg="#519aba", }, -- DevIconWebpack xxx ctermfg=74 guifg=#519aba
    DevIconFennel                               { fg="#fff3d7", }, -- DevIconFennel  xxx ctermfg=230 guifg=#fff3d7
    DevIconsbt                                  { fg="#cc3e44", }, -- DevIconsbt     xxx ctermfg=167 guifg=#cc3e44
    DevIconHs                                   { fg="#a074c4", }, -- DevIconHs      xxx ctermfg=140 guifg=#a074c4
    DevIconHtml                                 { fg="#e44d26", }, -- DevIconHtml    xxx ctermfg=196 guifg=#e44d26
    DevIconYml                                  { fg="#6d8086", }, -- DevIconYml     xxx ctermfg=66 guifg=#6d8086
    DevIconErb                                  { fg="#701516", }, -- DevIconErb     xxx ctermfg=52 guifg=#701516
    DevIconFortran                              { fg="#734f96", }, -- DevIconFortran xxx ctermfg=97 guifg=#734f96
    DevIconVala                                 { fg="#7239b3", }, -- DevIconVala    xxx ctermfg=91 guifg=#7239b3
    DevIconHbs                                  { fg="#f0772b", }, -- DevIconHbs     xxx ctermfg=202 guifg=#f0772b
    DevIconErl                                  { fg="#b83998", }, -- DevIconErl     xxx ctermfg=163 guifg=#b83998
    DevIconMd                                   { fg="#ffffff", }, -- DevIconMd      xxx ctermfg=231 guifg=#ffffff
    DevIconJavaScriptReactSpec                  { fg="#20c2e3", }, -- DevIconJavaScriptReactSpec xxx ctermfg=45 guifg=#20c2e3
    DevIconHaml                                 { fg="#eaeae1", }, -- DevIconHaml    xxx ctermfg=255 guifg=#eaeae1
    DevIconJavaScriptReactTest                  { fg="#20c2e3", }, -- DevIconJavaScriptReactTest xxx ctermfg=45 guifg=#20c2e3
    DevIconTestTs                               { fg="#519aba", }, -- DevIconTestTs  xxx ctermfg=74 guifg=#519aba
    DevIconSolidity                             { fg="#519aba", }, -- DevIconSolidity xxx ctermfg=74 guifg=#519aba
    DevIconEdn                                  { fg="#519aba", }, -- DevIconEdn     xxx ctermfg=74 guifg=#519aba
    DevIconTypeScriptReactTest                  { fg="#1354bf", }, -- DevIconTypeScriptReactTest xxx ctermfg=26 guifg=#1354bf
    DevIconGulpfile                             { fg="#cc3e44", }, -- DevIconGulpfile xxx ctermfg=167 guifg=#cc3e44
    DevIconMaterial                             { fg="#b83998", }, -- DevIconMaterial xxx ctermfg=163 guifg=#b83998
    DevIconEx                                   { fg="#a074c4", }, -- DevIconEx      xxx ctermfg=140 guifg=#a074c4
    DevIconIco                                  { fg="#cbcb41", }, -- DevIconIco     xxx ctermfg=185 guifg=#cbcb41
    DevIconEslintrc                             { fg="#4b32c3", }, -- DevIconEslintrc xxx ctermfg=56 guifg=#4b32c3
    DevIconBabelrc                              { fg="#cbcb41", }, -- DevIconBabelrc xxx ctermfg=185 guifg=#cbcb41
    DevIconLock                                 { fg="#bbbbbb", }, -- DevIconLock    xxx ctermfg=250 guifg=#bbbbbb
    DevIconDoc                                  { fg="#185abd", }, -- DevIconDoc     xxx ctermfg=26 guifg=#185abd
    DevIconGraphQL                              { fg="#e535ab", }, -- DevIconGraphQL xxx ctermfg=199 guifg=#e535ab
    DevIconTor                                  { fg="#519aba", }, -- DevIconTor     xxx ctermfg=74 guifg=#519aba
    DevIconXcPlayground                         { fg="#e37933", }, -- DevIconXcPlayground xxx ctermfg=166 guifg=#e37933
    DevIconXls                                  { fg="#207245", }, -- DevIconXls     xxx ctermfg=29 guifg=#207245
    DevIconXlsx                                 { fg="#207245", }, -- DevIconXlsx    xxx ctermfg=29 guifg=#207245
    DevIconWebm                                 { fg="#fd971f", }, -- DevIconWebm    xxx ctermfg=208 guifg=#fd971f
    DevIconLiquid                               { fg="#95bf47", }, -- DevIconLiquid  xxx ctermfg=106 guifg=#95bf47
    DevIconSuo                                  { fg="#854cc7", }, -- DevIconSuo     xxx ctermfg=98 guifg=#854cc7
    DevIconHuff                                 { fg="#4242c7", }, -- DevIconHuff    xxx ctermfg=56 guifg=#4242c7
    DevIconPl                                   { fg="#519aba", }, -- DevIconPl      xxx ctermfg=74 guifg=#519aba
    DevIconRb                                   { fg="#701516", }, -- DevIconRb      xxx ctermfg=52 guifg=#701516
    DevIconBash                                 { fg="#89e051", }, -- DevIconBash    xxx ctermfg=113 guifg=#89e051
    DevIconPyd                                  { fg="#ffe291", }, -- DevIconPyd     xxx ctermfg=222 guifg=#ffe291
    DevIconKsh                                  { fg="#4d5a5e", }, -- DevIconKsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconSig                                  { fg="#e37933", }, -- DevIconSig     xxx ctermfg=166 guifg=#e37933
    DevIconPsb                                  { fg="#519aba", }, -- DevIconPsb     xxx ctermfg=74 guifg=#519aba
    DevIconProcfile                             { fg="#a074c4", }, -- DevIconProcfile xxx ctermfg=140 guifg=#a074c4
    DevIconLess                                 { fg="#563d7c", }, -- DevIconLess    xxx ctermfg=54 guifg=#563d7c
    DevIconPackedResource                       { fg="#6d8086", }, -- DevIconPackedResource xxx ctermfg=66 guifg=#6d8086
    DevIconGitConfig                            { fg="#41535b", }, -- DevIconGitConfig xxx ctermfg=239 guifg=#41535b
    DevIconFsi                                  { fg="#519aba", }, -- DevIconFsi     xxx ctermfg=74 guifg=#519aba
    DevIconMp4                                  { fg="#fd971f", }, -- DevIconMp4     xxx ctermfg=208 guifg=#fd971f
    DevIconMp3                                  { fg="#66d8ef", }, -- DevIconMp3     xxx ctermfg=45 guifg=#66d8ef
    DevIconMOV                                  { fg="#fd971f", }, -- DevIconMOV     xxx ctermfg=208 guifg=#fd971f
    DevIconMotoko                               { fg="#9772fb", }, -- DevIconMotoko  xxx ctermfg=135 guifg=#9772fb
    DevIconMkv                                  { fg="#fd971f", }, -- DevIconMkv     xxx ctermfg=208 guifg=#fd971f
    DevIconMint                                 { fg="#87c095", }, -- DevIconMint    xxx ctermfg=108 guifg=#87c095
    DevIconM4V                                  { fg="#fd971f", }, -- DevIconM4V     xxx ctermfg=208 guifg=#fd971f
    DevIconM4A                                  { fg="#66d8ef", }, -- DevIconM4A     xxx ctermfg=45 guifg=#66d8ef
    DevIconZshenv                               { fg="#89e051", }, -- DevIconZshenv  xxx ctermfg=113 guifg=#89e051
    DevIconPyi                                  { fg="#ffbc03", }, -- DevIconPyi     xxx ctermfg=214 guifg=#ffbc03
    DevIconZshprofile                           { fg="#89e051", }, -- DevIconZshprofile xxx ctermfg=113 guifg=#89e051
    DevIconZshrc                                { fg="#89e051", }, -- DevIconZshrc   xxx ctermfg=113 guifg=#89e051
    DevIconAppleScript                          { fg="#6d8085", }, -- DevIconAppleScript xxx ctermfg=66 guifg=#6d8085
    DevIconTextScene                            { fg="#a074c4", }, -- DevIconTextScene xxx ctermfg=140 guifg=#a074c4
    DevIconXul                                  { fg="#e37933", }, -- DevIconXul     xxx ctermfg=166 guifg=#e37933
    DevIconGitAttributes                        { fg="#41535b", }, -- DevIconGitAttributes xxx ctermfg=239 guifg=#41535b
    DevIconYaml                                 { fg="#6d8086", }, -- DevIconYaml    xxx ctermfg=66 guifg=#6d8086
    DevIconPyx                                  { fg="#5aa7e4", }, -- DevIconPyx     xxx ctermfg=39 guifg=#5aa7e4
    DevIconJpegXl                               { fg="#a074c4", }, -- DevIconJpegXl  xxx ctermfg=140 guifg=#a074c4
    DevIconWebp                                 { fg="#a074c4", }, -- DevIconWebp    xxx ctermfg=140 guifg=#a074c4
    DevIconGif                                  { fg="#a074c4", }, -- DevIconGif     xxx ctermfg=140 guifg=#a074c4
    DevIconPng                                  { fg="#a074c4", }, -- DevIconPng     xxx ctermfg=140 guifg=#a074c4
    DevIconJpeg                                 { fg="#a074c4", }, -- DevIconJpeg    xxx ctermfg=140 guifg=#a074c4
    DevIconJpg                                  { fg="#a074c4", }, -- DevIconJpg     xxx ctermfg=140 guifg=#a074c4
    DevIconBashProfile                          { fg="#89e051", }, -- DevIconBashProfile xxx ctermfg=113 guifg=#89e051
    DevIconSpecJs                               { fg="#cbcb41", }, -- DevIconSpecJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconJl                                   { fg="#a270ba", }, -- DevIconJl      xxx ctermfg=133 guifg=#a270ba
    DevIconGitCommit                            { fg="#41535b", }, -- DevIconGitCommit xxx ctermfg=239 guifg=#41535b
    DevIconTFVars                               { fg="#5f43e9", }, -- DevIconTFVars  xxx ctermfg=93 guifg=#5f43e9
    DevIconHpp                                  { fg="#a074c4", }, -- DevIconHpp     xxx ctermfg=140 guifg=#a074c4
    DevIconC                                    { fg="#599eff", }, -- DevIconC       xxx ctermfg=111 guifg=#599eff
    DevIconSlim                                 { fg="#e34c26", }, -- DevIconSlim    xxx ctermfg=196 guifg=#e34c26
    DevIconEmbeddedOpenTypeFont                 { fg="#ececec", }, -- DevIconEmbeddedOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconFsscript                             { fg="#519aba", }, -- DevIconFsscript xxx ctermfg=74 guifg=#519aba
    DevIconRlib                                 { fg="#dea584", }, -- DevIconRlib    xxx ctermfg=216 guifg=#dea584
    NeoscrollHiddenCursor                       { gui="reverse", blend=100, }, -- NeoscrollHiddenCursor xxx gui=reverse blend=100
    MiniAnimateCursor                           { gui="reverse,nocombine", }, -- MiniAnimateCursor xxx cterm=reverse,nocombine gui=reverse,nocombine
    MiniAnimateNormalFloat                      { }, -- MiniAnimateNormalFloat xxx cterm= gui=
    lualine_a_insert                            { gui="bold", fg="#000000", bg="#1bbcdd", }, -- lualine_a_insert xxx gui=bold guifg=#000000 guibg=#1bbcdd
    lualine_b_insert                            { fg="#1bbcdd", bg="#000000", }, -- lualine_b_insert xxx guifg=#1bbcdd guibg=#000000
    lualine_c_insert                            { fg="#ffffff", bg="#18292f", }, -- lualine_c_insert xxx guifg=#ffffff guibg=#18292f
    lualine_a_visual                            { gui="bold", fg="#000000", bg="#33e7e1", }, -- lualine_a_visual xxx gui=bold guifg=#000000 guibg=#33e7e1
    lualine_b_visual                            { fg="#33e7e1", bg="#000000", }, -- lualine_b_visual xxx guifg=#33e7e1 guibg=#000000
    lualine_c_visual                            { fg="#ffffff", bg="#18292f", }, -- lualine_c_visual xxx guifg=#ffffff guibg=#18292f
    lualine_a_command                           { gui="bold", fg="#000000", bg="#fca3b3", }, -- lualine_a_command xxx gui=bold guifg=#000000 guibg=#fca3b3
    lualine_b_command                           { fg="#fca3b3", bg="#000000", }, -- lualine_b_command xxx guifg=#fca3b3 guibg=#000000
    lualine_c_command                           { fg="#ffffff", bg="#18292f", }, -- lualine_c_command xxx guifg=#ffffff guibg=#18292f
    lualine_a_normal                            { gui="bold", fg="#000000", bg="#d13434", }, -- lualine_a_normal xxx gui=bold guifg=#000000 guibg=#d13434
    lualine_b_normal                            { fg="#d13434", bg="#000000", }, -- lualine_b_normal xxx guifg=#d13434 guibg=#000000
    lualine_c_normal                            { fg="#ffffff", bg="#18292f", }, -- lualine_c_normal xxx guifg=#ffffff guibg=#18292f
    lualine_a_replace                           { gui="bold", fg="#000000", bg="#44b5a1", }, -- lualine_a_replace xxx gui=bold guifg=#000000 guibg=#44b5a1
    lualine_b_replace                           { fg="#44b5a1", bg="#000000", }, -- lualine_b_replace xxx guifg=#44b5a1 guibg=#000000
    lualine_c_replace                           { fg="#ffffff", bg="#18292f", }, -- lualine_c_replace xxx guifg=#ffffff guibg=#18292f
    lualine_b_diff_added_normal                 { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_normal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_insert                 { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_insert xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_visual                 { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_visual xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_replace                { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_replace xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_command                { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_command xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_terminal               { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_terminal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_inactive               { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_added_inactive xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_normal              { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_normal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_insert              { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_insert xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_visual              { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_visual xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_replace             { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_replace xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_command             { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_command xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_terminal            { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_terminal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_inactive            { fg="#fafafa", bg="#000000", }, -- lualine_b_diff_modified_inactive xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_removed_normal               { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_normal xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_insert               { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_insert xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_visual               { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_visual xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_replace              { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_replace xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_command              { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_command xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_terminal             { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_terminal xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_inactive             { fg="#0000ff", bg="#000000", }, -- lualine_b_diff_removed_inactive xxx guifg=#0000ff guibg=#000000
    lualine_b_diagnostics_error_normal          { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_normal xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_insert          { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_insert xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_visual          { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_visual xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_replace         { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_replace xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_command         { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_command xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_terminal        { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_terminal xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_inactive        { fg="#ff0000", bg="#000000", }, -- lualine_b_diagnostics_error_inactive xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_warn_normal           { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_normal xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_insert           { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_insert xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_visual           { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_visual xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_replace          { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_replace xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_command          { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_command xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_terminal         { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_terminal xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_inactive         { fg="#ffa500", bg="#000000", }, -- lualine_b_diagnostics_warn_inactive xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_info_normal           { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_normal xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_insert           { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_insert xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_visual           { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_visual xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_replace          { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_replace xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_command          { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_command xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_terminal         { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_terminal xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_inactive         { fg="#add8e6", bg="#000000", }, -- lualine_b_diagnostics_info_inactive xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_hint_normal           { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_normal xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_insert           { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_insert xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_visual           { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_visual xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_replace          { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_replace xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_command          { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_command xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_terminal         { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_terminal xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_inactive         { fg="#d3d3d3", bg="#000000", }, -- lualine_b_diagnostics_hint_inactive xxx guifg=#d3d3d3 guibg=#000000
    DapUIScope                                  { fg="#00f1f5", }, -- DapUIScope     xxx guifg=#00f1f5
    DapUIType                                   { fg="#d484ff", }, -- DapUIType      xxx guifg=#d484ff
    DapUIModifiedValue                          { gui="bold", fg="#00f1f5", }, -- DapUIModifiedValue xxx gui=bold guifg=#00f1f5
    DapUIDecoration                             { fg="#00f1f5", }, -- DapUIDecoration xxx guifg=#00f1f5
    DapUIThread                                 { fg="#a9ff68", }, -- DapUIThread    xxx guifg=#a9ff68
    DapUIStoppedThread                          { fg="#00f1f5", }, -- DapUIStoppedThread xxx guifg=#00f1f5
    DapUISource                                 { fg="#d484ff", }, -- DapUISource    xxx guifg=#d484ff
    DapUILineNumber                             { fg="#00f1f5", }, -- DapUILineNumber xxx guifg=#00f1f5
    DapUIBreakpointsLine                        { DapUILineNumber }, -- DapUIBreakpointsLine xxx links to DapUILineNumber
    DapUIFloatBorder                            { fg="#00f1f5", }, -- DapUIFloatBorder xxx guifg=#00f1f5
    DapUIWatchesEmpty                           { fg="#f70067", }, -- DapUIWatchesEmpty xxx guifg=#f70067
    DapUIWatchesValue                           { fg="#a9ff68", }, -- DapUIWatchesValue xxx guifg=#a9ff68
    DapUIWatchesError                           { fg="#f70067", }, -- DapUIWatchesError xxx guifg=#f70067
    DapUIBreakpointsPath                        { fg="#00f1f5", }, -- DapUIBreakpointsPath xxx guifg=#00f1f5
    DapUIBreakpointsInfo                        { fg="#a9ff68", }, -- DapUIBreakpointsInfo xxx guifg=#a9ff68
    DapUIBreakpointsCurrentLine                 { gui="bold", fg="#a9ff68", }, -- DapUIBreakpointsCurrentLine xxx gui=bold guifg=#a9ff68
    DapUICurrentFrameName                       { DapUIBreakpointsCurrentLine }, -- DapUICurrentFrameName xxx links to DapUIBreakpointsCurrentLine
    DapUIBreakpointsDisabledLine                { fg="#424242", }, -- DapUIBreakpointsDisabledLine xxx guifg=#424242
    DapUIStepOver                               { fg="#00f1f5", }, -- DapUIStepOver  xxx guifg=#00f1f5
    DapUIStepInto                               { fg="#00f1f5", }, -- DapUIStepInto  xxx guifg=#00f1f5
    DapUIStepBack                               { fg="#00f1f5", }, -- DapUIStepBack  xxx guifg=#00f1f5
    DapUIStepOut                                { fg="#00f1f5", }, -- DapUIStepOut   xxx guifg=#00f1f5
    DapUIStop                                   { fg="#f70067", }, -- DapUIStop      xxx guifg=#f70067
    DapUIPlayPause                              { fg="#a9ff68", }, -- DapUIPlayPause xxx guifg=#a9ff68
    DapUIRestart                                { fg="#a9ff68", }, -- DapUIRestart   xxx guifg=#a9ff68
    DapUIUnavailable                            { fg="#424242", }, -- DapUIUnavailable xxx guifg=#424242
    DapUIWinSelect                              { gui="bold", fg="#00f1f5", }, -- DapUIWinSelect xxx ctermfg=14 gui=bold guifg=#00f1f5
    DapUINormalNC                               { }, -- DapUINormalNC  xxx cterm= gui=
    DapUIPlayPauseNC                            { fg="#a9ff68", }, -- DapUIPlayPauseNC xxx cterm= gui= guifg=#a9ff68
    DapUIRestartNC                              { fg="#a9ff68", }, -- DapUIRestartNC xxx cterm= gui= guifg=#a9ff68
    DapUIStopNC                                 { fg="#f70067", }, -- DapUIStopNC    xxx cterm= gui= guifg=#f70067
    DapUIUnavailableNC                          { fg="#424242", }, -- DapUIUnavailableNC xxx cterm= gui= guifg=#424242
    DapUIStepOverNC                             { fg="#00f1f5", }, -- DapUIStepOverNC xxx cterm= gui= guifg=#00f1f5
    DapUIStepIntoNC                             { fg="#00f1f5", }, -- DapUIStepIntoNC xxx cterm= gui= guifg=#00f1f5
    DapUIStepBackNC                             { fg="#00f1f5", }, -- DapUIStepBackNC xxx cterm= gui= guifg=#00f1f5
    DapUIStepOutNC                              { fg="#00f1f5", }, -- DapUIStepOutNC xxx cterm= gui= guifg=#00f1f5
    lualine_x_filetype_DevIconDefault_normal    { fg="#6d8086", bg="#18292f", }, -- lualine_x_filetype_DevIconDefault_normal xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_insert    { fg="#6d8086", bg="#18292f", }, -- lualine_x_filetype_DevIconDefault_insert xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_visual    { fg="#6d8086", bg="#18292f", }, -- lualine_x_filetype_DevIconDefault_visual xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_replace   { fg="#6d8086", bg="#18292f", }, -- lualine_x_filetype_DevIconDefault_replace xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_command   { fg="#6d8086", bg="#18292f", }, -- lualine_x_filetype_DevIconDefault_command xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_terminal  { fg="#6d8086", bg="#18292f", }, -- lualine_x_filetype_DevIconDefault_terminal xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_inactive  { fg="#6d8086", bg="#18292f", }, -- lualine_x_filetype_DevIconDefault_inactive xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconLua_normal        { fg="#51a0cf", bg="#18292f", }, -- lualine_x_filetype_DevIconLua_normal xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_insert        { fg="#51a0cf", bg="#18292f", }, -- lualine_x_filetype_DevIconLua_insert xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_visual        { fg="#51a0cf", bg="#18292f", }, -- lualine_x_filetype_DevIconLua_visual xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_replace       { fg="#51a0cf", bg="#18292f", }, -- lualine_x_filetype_DevIconLua_replace xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_command       { fg="#51a0cf", bg="#18292f", }, -- lualine_x_filetype_DevIconLua_command xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_terminal      { fg="#51a0cf", bg="#18292f", }, -- lualine_x_filetype_DevIconLua_terminal xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_inactive      { fg="#51a0cf", bg="#18292f", }, -- lualine_x_filetype_DevIconLua_inactive xxx guifg=#51a0cf guibg=#18292f
  }
end)
return theme
