-- autogenerated lush spec on Thu 11 Jan 2024 01:14:42 PM CST
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
local theme = lush(function(injected_functions)
  local sym = injected_functions.sym
  return {
    SpecialKey                                  { bg="#252527", fg="#e6cabe", }, -- SpecialKey     xxx ctermfg=81 guifg=#e6cabe guibg=#252527
    TermCursor                                  { gui="reverse", }, -- TermCursor     xxx cterm=reverse gui=reverse
    NonText                                     { gui="bold", fg="#4b4b4c", }, -- NonText        xxx ctermfg=12 gui=bold guifg=#4b4b4c
    EndOfBuffer                                 { NonText }, -- EndOfBuffer    xxx links to NonText
    Whitespace                                  { NonText }, -- Whitespace     xxx links to NonText
    TelescopePreviewHyphen                      { NonText }, -- TelescopePreviewHyphen xxx links to NonText
    TelescopePromptCounter                      { NonText }, -- TelescopePromptCounter xxx links to NonText
    TelescopeResultsDiffUntracked               { NonText }, -- TelescopeResultsDiffUntracked xxx links to NonText
    Directory                                   { fg="#91b3af", }, -- Directory      xxx ctermfg=159 guifg=#91b3af
    TelescopePreviewDirectory                   { Directory }, -- TelescopePreviewDirectory xxx links to Directory
    TelescopePreviewDate                        { Directory }, -- TelescopePreviewDate xxx links to Directory
    NvimTreeSymlinkFolderName                   { Directory }, -- NvimTreeSymlinkFolderName xxx links to Directory
    NvimTreeOpenedFolderName                    { Directory }, -- NvimTreeOpenedFolderName xxx links to Directory
    NvimTreeEmptyFolderName                     { Directory }, -- NvimTreeEmptyFolderName xxx links to Directory
    NvimTreeFolderName                          { Directory }, -- NvimTreeFolderName xxx links to Directory
    ErrorMsg                                    { bg="#252527", gui="bold", fg="#ff0000", }, -- ErrorMsg       xxx ctermfg=15 ctermbg=1 gui=bold guifg=#ff0000 guibg=#252527
    NvimInvalidSpacing                          { ErrorMsg }, -- NvimInvalidSpacing xxx links to ErrorMsg
    IncSearch                                   { bg="#ba3934", gui="reverse", fg="#121214", }, -- IncSearch      xxx cterm=reverse gui=reverse guifg=#121214 guibg=#ba3934
    Search                                      { bg="yellow", gui="underline", fg="black", }, -- Search         xxx ctermfg=0 ctermbg=11 gui=underline guifg=Black guibg=Yellow
    CurSearch                                   { Search }, -- CurSearch      xxx links to Search
    QuickFixLine                                { Search }, -- QuickFixLine   xxx links to Search
    Substitute                                  { Search }, -- Substitute     xxx links to Search
    TelescopePreviewMatch                       { Search }, -- TelescopePreviewMatch xxx links to Search
    MoreMsg                                     { gui="bold", fg="seagreen", }, -- MoreMsg        xxx ctermfg=121 gui=bold guifg=SeaGreen
    ModeMsg                                     { gui="bold", }, -- ModeMsg        xxx cterm=bold gui=bold
    LineNr                                      { bg="#252527", fg="#e6cabe", }, -- LineNr         xxx ctermfg=11 guifg=#e6cabe guibg=#252527
    LineNrAbove                                 { LineNr }, -- LineNrAbove    xxx links to LineNr
    LineNrBelow                                 { LineNr }, -- LineNrBelow    xxx links to LineNr
    TelescopeResultsLineNr                      { LineNr }, -- TelescopeResultsLineNr xxx links to LineNr
    NvimTreeLineNr                              { LineNr }, -- NvimTreeLineNr xxx links to LineNr
    CursorLineNr                                { bg="#252527", gui="bold", fg="#fadccf", }, -- CursorLineNr   xxx cterm=underline ctermfg=11 gui=bold guifg=#fadccf guibg=#252527
    NvimTreeCursorLineNr                        { CursorLineNr }, -- NvimTreeCursorLineNr xxx links to CursorLineNr
    Question                                    { gui="bold", fg="green", }, -- Question       xxx ctermfg=121 gui=bold guifg=Green
    StatusLine                                  { bg="#38383a", gui="bold", fg="#e6cabe", }, -- StatusLine     xxx cterm=bold,reverse gui=bold guifg=#e6cabe guibg=#38383a
    MsgSeparator                                { StatusLine }, -- MsgSeparator   xxx links to StatusLine
    NvimTreeStatusLine                          { StatusLine }, -- NvimTreeStatusLine xxx links to StatusLine
    StatusLineNC                                { gui="reverse", }, -- StatusLineNC   xxx cterm=reverse gui=reverse
    NvimTreeStatusLineNC                        { StatusLineNC }, -- NvimTreeStatusLineNC xxx links to StatusLineNC
    VertSplit                                   { bg="#38383a", fg="#d2b9ae", }, -- VertSplit      xxx guifg=#d2b9ae guibg=#38383a
    WinSeparator                                { VertSplit }, -- WinSeparator   xxx links to VertSplit
    Title                                       { gui="bold", fg="#fadccf", }, -- Title          xxx ctermfg=225 gui=bold guifg=#fadccf
    FloatTitle                                  { Title }, -- FloatTitle     xxx links to Title
    sym"@text.title"                            { Title }, -- @text.title    xxx links to Title
    LspInfoTitle                                { Title }, -- LspInfoTitle   xxx links to Title
    Visual                                      { bg="darkgrey", }, -- Visual         xxx ctermbg=242 guibg=DarkGrey
    TelescopePreviewLine                        { Visual }, -- TelescopePreviewLine xxx links to Visual
    TelescopeSelection                          { Visual }, -- TelescopeSelection xxx links to Visual
    WarningMsg                                  { bg="#ff8800", fg="#fadccf", }, -- WarningMsg     xxx ctermfg=224 guifg=#fadccf guibg=#ff8800
    WildMenu                                    { bg="#121214", fg="#bd9530", }, -- WildMenu       xxx ctermfg=0 ctermbg=11 guifg=#bd9530 guibg=#121214
    Folded                                      { bg="#121214", fg="#bea79d", }, -- Folded         xxx ctermfg=14 ctermbg=242 guifg=#bea79d guibg=#121214
    FoldColumn                                  { bg="#252527", fg="#808080", }, -- FoldColumn     xxx ctermfg=14 ctermbg=242 guifg=#808080 guibg=#252527
    CursorLineFold                              { FoldColumn }, -- CursorLineFold xxx links to FoldColumn
    DiffAdd                                     { bg="#123d0f", gui="bold", fg="#fafafa", }, -- DiffAdd        xxx ctermbg=4 gui=bold guifg=#fafafa guibg=#123d0f
    TelescopeResultsDiffAdd                     { DiffAdd }, -- TelescopeResultsDiffAdd xxx links to DiffAdd
    DiffChange                                  { bg="#151b3c", fg="#fafafa", }, -- DiffChange     xxx ctermbg=5 guifg=#fafafa guibg=#151b3c
    TelescopeResultsDiffChange                  { DiffChange }, -- TelescopeResultsDiffChange xxx links to DiffChange
    DiffDelete                                  { bg="#252527", gui="bold", fg="blue", }, -- DiffDelete     xxx ctermfg=12 ctermbg=6 gui=bold guifg=Blue guibg=#252527
    TelescopeResultsDiffDelete                  { DiffDelete }, -- TelescopeResultsDiffDelete xxx links to DiffDelete
    DiffText                                    { bg="#ff0000", gui="bold", fg="#ffffff", }, -- DiffText       xxx cterm=bold ctermbg=9 gui=bold guifg=#ffffff guibg=#ff0000
    SignColumn                                  { bg="#252527", fg="#808080", }, -- SignColumn     xxx ctermfg=14 ctermbg=242 guifg=#808080 guibg=#252527
    CursorLineSign                              { SignColumn }, -- CursorLineSign xxx links to SignColumn
    Conceal                                     { bg="darkgrey", fg="lightgrey", }, -- Conceal        xxx ctermfg=7 ctermbg=242 guifg=LightGrey guibg=DarkGrey
    SpellBad                                    { sp="red", gui="undercurl", }, -- SpellBad       xxx ctermbg=9 gui=undercurl guisp=Red
    NvimTreeCutHL                               { SpellBad }, -- NvimTreeCutHL  xxx links to SpellBad
    SpellCap                                    { sp="blue", gui="undercurl", }, -- SpellCap       xxx ctermbg=12 gui=undercurl guisp=Blue
    SpellRare                                   { sp="magenta", gui="undercurl", }, -- SpellRare      xxx ctermbg=13 gui=undercurl guisp=Magenta
    NvimTreeCopiedHL                            { SpellRare }, -- NvimTreeCopiedHL xxx links to SpellRare
    SpellLocal                                  { sp="cyan", gui="undercurl", }, -- SpellLocal     xxx ctermbg=14 gui=undercurl guisp=Cyan
    NvimTreeBookmarkHL                          { SpellLocal }, -- NvimTreeBookmarkHL xxx links to SpellLocal
    Pmenu                                       { bg="#252527", fg="#fadccf", }, -- Pmenu          xxx ctermfg=0 ctermbg=13 guifg=#fadccf guibg=#252527
    PmenuKind                                   { Pmenu }, -- PmenuKind      xxx links to Pmenu
    PmenuExtra                                  { Pmenu }, -- PmenuExtra     xxx links to Pmenu
    NormalFloat                                 { Pmenu }, -- NormalFloat    xxx links to Pmenu
    PmenuSel                                    { bg="#38383a", }, -- PmenuSel       xxx ctermfg=242 ctermbg=0 guibg=#38383a
    PmenuKindSel                                { PmenuSel }, -- PmenuKindSel   xxx links to PmenuSel
    PmenuExtraSel                               { PmenuSel }, -- PmenuExtraSel  xxx links to PmenuSel
    PmenuSbar                                   { bg="grey", }, -- PmenuSbar      xxx ctermbg=248 guibg=Grey
    PmenuThumb                                  { bg="white", }, -- PmenuThumb     xxx ctermbg=15 guibg=White
    TabLine                                     { bg="darkgrey", gui="underline", }, -- TabLine        xxx cterm=underline ctermfg=15 ctermbg=242 gui=underline guibg=DarkGrey
    TabLineSel                                  { gui="bold", }, -- TabLineSel     xxx cterm=bold gui=bold
    TabLineFill                                 { gui="reverse", }, -- TabLineFill    xxx cterm=reverse gui=reverse
    CursorColumn                                { bg="#252527", }, -- CursorColumn   xxx ctermbg=242 guibg=#252527
    NvimTreeCursorColumn                        { CursorColumn }, -- NvimTreeCursorColumn xxx links to CursorColumn
    CursorLine                                  { bg="#252527", }, -- CursorLine     xxx cterm=underline guibg=#252527
    NvimTreeCursorLine                          { CursorLine }, -- NvimTreeCursorLine xxx links to CursorLine
    ColorColumn                                 { bg="#252527", }, -- ColorColumn    xxx ctermbg=1 guibg=#252527
    WinBar                                      { gui="bold", }, -- WinBar         xxx cterm=bold gui=bold
    WinBarNC                                    { WinBar }, -- WinBarNC       xxx links to WinBar
    Cursor                                      { bg="#fadccf", fg="#121214", }, -- Cursor         xxx guifg=#121214 guibg=#fadccf
    lCursor                                     { bg="fg", fg="bg", }, -- lCursor        xxx guifg=bg guibg=fg
    Normal                                      { fg="#fadccf", }, -- Normal         xxx guifg=#fadccf
    NvimSpacing                                 { Normal }, -- NvimSpacing    xxx links to Normal
    TelescopeNormal                             { Normal }, -- TelescopeNormal xxx links to Normal
    NvimTreeNormal                              { Normal }, -- NvimTreeNormal xxx links to Normal
    NvimTreePopup                               { Normal }, -- NvimTreePopup  xxx links to Normal
    DapUINormal                                 { Normal }, -- DapUINormal    xxx links to Normal
    DapUIVariable                               { Normal }, -- DapUIVariable  xxx links to Normal
    DapUIValue                                  { Normal }, -- DapUIValue     xxx links to Normal
    DapUIFrameName                              { Normal }, -- DapUIFrameName xxx links to Normal
    FloatShadow                                 { bg="black", blend=80, }, -- FloatShadow    xxx guibg=Black blend=80
    FloatShadowThrough                          { bg="black", blend=100, }, -- FloatShadowThrough xxx guibg=Black blend=100
    RedrawDebugNormal                           { gui="reverse", }, -- RedrawDebugNormal xxx cterm=reverse gui=reverse
    RedrawDebugClear                            { bg="yellow", }, -- RedrawDebugClear xxx ctermbg=11 guibg=Yellow
    RedrawDebugComposed                         { bg="green", }, -- RedrawDebugComposed xxx ctermbg=10 guibg=Green
    RedrawDebugRecompose                        { bg="red", }, -- RedrawDebugRecompose xxx ctermbg=9 guibg=Red
    Error                                       { bg="red", fg="white", }, -- Error          xxx ctermfg=15 ctermbg=9 guifg=White guibg=Red
    NvimInvalid                                 { Error }, -- NvimInvalid    xxx links to Error
    luaParenError                               { Error }, -- luaParenError  xxx links to Error
    luaError                                    { Error }, -- luaError       xxx links to Error
    Todo                                        { bg="#121214", gui="bold,reverse", fg="#e6cabe", }, -- Todo           xxx ctermfg=0 ctermbg=11 gui=bold,reverse guifg=#e6cabe guibg=#121214
    sym"@text.todo"                             { Todo }, -- @text.todo     xxx links to Todo
    luaTodo                                     { Todo }, -- luaTodo        xxx links to Todo
    String                                      { fg="#bd9530", }, -- String         xxx guifg=#bd9530
    sym"@string"                                { String }, -- @string        xxx links to String
    NvimString                                  { String }, -- NvimString     xxx links to String
    TelescopePreviewSize                        { String }, -- TelescopePreviewSize xxx links to String
    TelescopePreviewExecute                     { String }, -- TelescopePreviewExecute xxx links to String
    luaString2                                  { String }, -- luaString2     xxx links to String
    luaString                                   { String }, -- luaString      xxx links to String
    Constant                                    { fg="#91b3af", }, -- Constant       xxx ctermfg=13 guifg=#91b3af
    sym"@constant"                              { Constant }, -- @constant      xxx links to Constant
    sym"@lsp.type.enumMember"                   { Constant }, -- @lsp.type.enumMember xxx links to Constant
    TelescopePreviewRead                        { Constant }, -- TelescopePreviewRead xxx links to Constant
    TelescopePreviewBlock                       { Constant }, -- TelescopePreviewBlock xxx links to Constant
    TelescopePreviewCharDev                     { Constant }, -- TelescopePreviewCharDev xxx links to Constant
    TelescopePreviewPipe                        { Constant }, -- TelescopePreviewPipe xxx links to Constant
    TelescopeResultsConstant                    { Constant }, -- TelescopeResultsConstant xxx links to Constant
    TelescopePreviewGroup                       { Constant }, -- TelescopePreviewGroup xxx links to Constant
    TelescopePreviewUser                        { Constant }, -- TelescopePreviewUser xxx links to Constant
    luaConstant                                 { Constant }, -- luaConstant    xxx links to Constant
    Character                                   { fg="#91b3af", }, -- Character      xxx guifg=#91b3af
    sym"@character"                             { Character }, -- @character     xxx links to Character
    Number                                      { fg="#91b3af", }, -- Number         xxx guifg=#91b3af
    sym"@number"                                { Number }, -- @number        xxx links to Number
    NvimNumber                                  { Number }, -- NvimNumber     xxx links to Number
    TelescopeResultsNumber                      { Number }, -- TelescopeResultsNumber xxx links to Number
    luaNumber                                   { Number }, -- luaNumber      xxx links to Number
    Boolean                                     { fg="#91b3af", }, -- Boolean        xxx guifg=#91b3af
    sym"@boolean"                               { Boolean }, -- @boolean       xxx links to Boolean
    Float                                       { fg="#91b3af", }, -- Float          xxx guifg=#91b3af
    sym"@float"                                 { Float }, -- @float         xxx links to Float
    Function                                    { fg="#b55600", }, -- Function       xxx guifg=#b55600
    sym"@function"                              { Function }, -- @function      xxx links to Function
    sym"@method"                                { Function }, -- @method        xxx links to Function
    sym"@lsp.type.decorator"                    { Function }, -- @lsp.type.decorator xxx links to Function
    sym"@lsp.type.function"                     { Function }, -- @lsp.type.function xxx links to Function
    sym"@lsp.type.method"                       { Function }, -- @lsp.type.method xxx links to Function
    TelescopeResultsFunction                    { Function }, -- TelescopeResultsFunction xxx links to Function
    TelescopeResultsField                       { Function }, -- TelescopeResultsField xxx links to Function
    TelescopeResultsClass                       { Function }, -- TelescopeResultsClass xxx links to Function
    LspInfoList                                 { Function }, -- LspInfoList    xxx links to Function
    luaMetaMethod                               { Function }, -- luaMetaMethod  xxx links to Function
    luaFunction                                 { Function }, -- luaFunction    xxx links to Function
    Identifier                                  { gui="italic", fg="#ea7eae", }, -- Identifier     xxx cterm=bold ctermfg=14 gui=italic guifg=#ea7eae
    sym"@text.reference"                        { Identifier }, -- @text.reference xxx links to Identifier
    sym"@parameter"                             { Identifier }, -- @parameter     xxx links to Identifier
    sym"@field"                                 { Identifier }, -- @field         xxx links to Identifier
    sym"@property"                              { Identifier }, -- @property      xxx links to Identifier
    sym"@variable"                              { Identifier }, -- @variable      xxx links to Identifier
    sym"@namespace"                             { Identifier }, -- @namespace     xxx links to Identifier
    sym"@lsp.type.parameter"                    { Identifier }, -- @lsp.type.parameter xxx links to Identifier
    sym"@lsp.type.property"                     { Identifier }, -- @lsp.type.property xxx links to Identifier
    sym"@lsp.type.variable"                     { Identifier }, -- @lsp.type.variable xxx links to Identifier
    NvimIdentifier                              { Identifier }, -- NvimIdentifier xxx links to Identifier
    TelescopePromptPrefix                       { Identifier }, -- TelescopePromptPrefix xxx links to Identifier
    TelescopeMultiIcon                          { Identifier }, -- TelescopeMultiIcon xxx links to Identifier
    TelescopeResultsIdentifier                  { Identifier }, -- TelescopeResultsIdentifier xxx links to Identifier
    luaFunc                                     { Identifier }, -- luaFunc        xxx links to Identifier
    Conditional                                 { fg="#ba3934", }, -- Conditional    xxx guifg=#ba3934
    sym"@conditional"                           { Conditional }, -- @conditional   xxx links to Conditional
    luaCondElse                                 { Conditional }, -- luaCondElse    xxx links to Conditional
    luaCond                                     { Conditional }, -- luaCond        xxx links to Conditional
    Statement                                   { gui="bold", fg="#ba3934", }, -- Statement      xxx ctermfg=11 gui=bold guifg=#ba3934
    Repeat                                      { Statement }, -- Repeat         xxx links to Statement
    Exception                                   { Statement }, -- Exception      xxx links to Statement
    TelescopePreviewWrite                       { Statement }, -- TelescopePreviewWrite xxx links to Statement
    TelescopePreviewSocket                      { Statement }, -- TelescopePreviewSocket xxx links to Statement
    luaStatement                                { Statement }, -- luaStatement   xxx links to Statement
    Label                                       { fg="#5f63b4", }, -- Label          xxx guifg=#5f63b4
    sym"@label"                                 { Label }, -- @label         xxx links to Label
    LspInfoBorder                               { Label }, -- LspInfoBorder  xxx links to Label
    luaLabel                                    { Label }, -- luaLabel       xxx links to Label
    Operator                                    { fg="#ba3934", }, -- Operator       xxx guifg=#ba3934
    sym"@operator"                              { Operator }, -- @operator      xxx links to Operator
    NvimAssignment                              { Operator }, -- NvimAssignment xxx links to Operator
    NvimOperator                                { Operator }, -- NvimOperator   xxx links to Operator
    TelescopeResultsOperator                    { Operator }, -- TelescopeResultsOperator xxx links to Operator
    luaOperator                                 { Operator }, -- luaOperator    xxx links to Operator
    Keyword                                     { gui="bold", fg="#ba3934", }, -- Keyword        xxx gui=bold guifg=#ba3934
    sym"@keyword"                               { Keyword }, -- @keyword       xxx links to Keyword
    TelescopePreviewSticky                      { Keyword }, -- TelescopePreviewSticky xxx links to Keyword
    PreProc                                     { fg="#ba3934", }, -- PreProc        xxx ctermfg=81 guifg=#ba3934
    Include                                     { PreProc }, -- Include        xxx links to PreProc
    Macro                                       { PreProc }, -- Macro          xxx links to PreProc
    PreCondit                                   { PreProc }, -- PreCondit      xxx links to PreProc
    sym"@preproc"                               { PreProc }, -- @preproc       xxx links to PreProc
    Define                                      { fg="#ba3934", }, -- Define         xxx guifg=#ba3934
    sym"@constant.macro"                        { Define }, -- @constant.macro xxx links to Define
    sym"@define"                                { Define }, -- @define        xxx links to Define
    StorageClass                                { gui="italic", fg="#ea7eae", }, -- StorageClass   xxx gui=italic guifg=#ea7eae
    sym"@storageclass"                          { StorageClass }, -- @storageclass  xxx links to StorageClass
    Type                                        { gui="bold", fg="#ea7eae", }, -- Type           xxx ctermfg=121 gui=bold guifg=#ea7eae
    Structure                                   { Type }, -- Structure      xxx links to Type
    Typedef                                     { Type }, -- Typedef        xxx links to Type
    sym"@type"                                  { Type }, -- @type          xxx links to Type
    sym"@lsp.type.type"                         { Type }, -- @lsp.type.type xxx links to Type
    NvimNumberPrefix                            { Type }, -- NvimNumberPrefix xxx links to Type
    NvimOptionSigil                             { Type }, -- NvimOptionSigil xxx links to Type
    TelescopeMultiSelection                     { Type }, -- TelescopeMultiSelection xxx links to Type
    LspInfoFiletype                             { Type }, -- LspInfoFiletype xxx links to Type
    Tag                                         { fg="#ba3934", }, -- Tag            xxx guifg=#ba3934
    sym"@tag"                                   { Tag }, -- @tag           xxx links to Tag
    Special                                     { fg="#fadccf", }, -- Special        xxx ctermfg=224 guifg=#fadccf
    SpecialChar                                 { Special }, -- SpecialChar    xxx links to Special
    Delimiter                                   { Special }, -- Delimiter      xxx links to Special
    SpecialComment                              { Special }, -- SpecialComment xxx links to Special
    Debug                                       { Special }, -- Debug          xxx links to Special
    sym"@constant.builtin"                      { Special }, -- @constant.builtin xxx links to Special
    sym"@function.builtin"                      { Special }, -- @function.builtin xxx links to Special
    sym"@constructor"                           { Special }, -- @constructor   xxx links to Special
    TelescopePreviewLink                        { Special }, -- TelescopePreviewLink xxx links to Special
    TelescopeMatching                           { Special }, -- TelescopeMatching xxx links to Special
    DiagnosticError                             { fg="red", }, -- DiagnosticError xxx ctermfg=1 guifg=Red
    DiagnosticVirtualTextError                  { DiagnosticError }, -- DiagnosticVirtualTextError xxx links to DiagnosticError
    DiagnosticFloatingError                     { DiagnosticError }, -- DiagnosticFloatingError xxx links to DiagnosticError
    DiagnosticSignError                         { DiagnosticError }, -- DiagnosticSignError xxx links to DiagnosticError
    NvimTreeLspDiagnosticsError                 { DiagnosticError }, -- NvimTreeLspDiagnosticsError xxx links to DiagnosticError
    DiagnosticWarn                              { fg="orange", }, -- DiagnosticWarn xxx ctermfg=3 guifg=Orange
    DiagnosticVirtualTextWarn                   { DiagnosticWarn }, -- DiagnosticVirtualTextWarn xxx links to DiagnosticWarn
    DiagnosticFloatingWarn                      { DiagnosticWarn }, -- DiagnosticFloatingWarn xxx links to DiagnosticWarn
    DiagnosticSignWarn                          { DiagnosticWarn }, -- DiagnosticSignWarn xxx links to DiagnosticWarn
    NvimTreeLspDiagnosticsWarning               { DiagnosticWarn }, -- NvimTreeLspDiagnosticsWarning xxx links to DiagnosticWarn
    DiagnosticInfo                              { fg="lightblue", }, -- DiagnosticInfo xxx ctermfg=4 guifg=LightBlue
    DiagnosticVirtualTextInfo                   { DiagnosticInfo }, -- DiagnosticVirtualTextInfo xxx links to DiagnosticInfo
    DiagnosticFloatingInfo                      { DiagnosticInfo }, -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
    DiagnosticSignInfo                          { DiagnosticInfo }, -- DiagnosticSignInfo xxx links to DiagnosticInfo
    NvimTreeLspDiagnosticsInformation           { DiagnosticInfo }, -- NvimTreeLspDiagnosticsInformation xxx links to DiagnosticInfo
    DiagnosticHint                              { fg="lightgrey", }, -- DiagnosticHint xxx ctermfg=7 guifg=LightGrey
    DiagnosticVirtualTextHint                   { DiagnosticHint }, -- DiagnosticVirtualTextHint xxx links to DiagnosticHint
    DiagnosticFloatingHint                      { DiagnosticHint }, -- DiagnosticFloatingHint xxx links to DiagnosticHint
    DiagnosticSignHint                          { DiagnosticHint }, -- DiagnosticSignHint xxx links to DiagnosticHint
    NvimTreeLspDiagnosticsHint                  { DiagnosticHint }, -- NvimTreeLspDiagnosticsHint xxx links to DiagnosticHint
    DiagnosticOk                                { fg="lightgreen", }, -- DiagnosticOk   xxx ctermfg=10 guifg=LightGreen
    DiagnosticVirtualTextOk                     { DiagnosticOk }, -- DiagnosticVirtualTextOk xxx links to DiagnosticOk
    DiagnosticFloatingOk                        { DiagnosticOk }, -- DiagnosticFloatingOk xxx links to DiagnosticOk
    DiagnosticSignOk                            { DiagnosticOk }, -- DiagnosticSignOk xxx links to DiagnosticOk
    DiagnosticUnderlineError                    { sp="red", gui="underline", }, -- DiagnosticUnderlineError xxx cterm=underline gui=underline guisp=Red
    DiagnosticUnderlineWarn                     { sp="orange", gui="underline", }, -- DiagnosticUnderlineWarn xxx cterm=underline gui=underline guisp=Orange
    DiagnosticUnderlineInfo                     { sp="lightblue", gui="underline", }, -- DiagnosticUnderlineInfo xxx cterm=underline gui=underline guisp=LightBlue
    DiagnosticUnderlineHint                     { sp="lightgrey", gui="underline", }, -- DiagnosticUnderlineHint xxx cterm=underline gui=underline guisp=LightGrey
    DiagnosticUnderlineOk                       { sp="lightgreen", gui="underline", }, -- DiagnosticUnderlineOk xxx cterm=underline gui=underline guisp=LightGreen
    DiagnosticDeprecated                        { sp="red", gui="strikethrough", }, -- DiagnosticDeprecated xxx cterm=strikethrough gui=strikethrough guisp=Red
    Comment                                     { fg="#808080", }, -- Comment        xxx ctermfg=14 guifg=#808080
    DiagnosticUnnecessary                       { Comment }, -- DiagnosticUnnecessary xxx links to Comment
    sym"@text.literal"                          { Comment }, -- @text.literal  xxx links to Comment
    sym"@comment"                               { Comment }, -- @comment       xxx links to Comment
    sym"@lsp.type.comment"                      { Comment }, -- @lsp.type.comment xxx links to Comment
    TelescopeResultsComment                     { Comment }, -- TelescopeResultsComment xxx links to Comment
    LspInfoTip                                  { Comment }, -- LspInfoTip     xxx links to Comment
    NvimTreeGitIgnored                          { Comment }, -- NvimTreeGitIgnored xxx links to Comment
    luaComment                                  { Comment }, -- luaComment     xxx links to Comment
    Underlined                                  { gui="underline", fg="#80a0ff", }, -- Underlined     xxx cterm=underline ctermfg=81 gui=underline guifg=#80a0ff
    sym"@text.uri"                              { Underlined }, -- @text.uri      xxx links to Underlined
    sym"@text.underline"                        { Underlined }, -- @text.underline xxx links to Underlined
    MatchParen                                  { bg="darkcyan", gui="underline", fg="#ff8800", }, -- MatchParen     xxx ctermbg=6 gui=underline guifg=#ff8800 guibg=DarkCyan
    Ignore                                      { fg="bg", }, -- Ignore         xxx ctermfg=0 guifg=bg
    NvimInternalError                           { bg="red", fg="red", }, -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
    NvimFigureBrace                             { NvimInternalError }, -- NvimFigureBrace xxx links to NvimInternalError
    NvimSingleQuotedUnknownEscape               { NvimInternalError }, -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
    NvimInvalidSingleQuotedUnknownEscape        { NvimInternalError }, -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
    rubyAttribute                               { fg="#3d3b4b", }, -- rubyAttribute  xxx guifg=#3d3b4b
    rubyLocalVariableOrMethod                   { fg="#5f63b4", }, -- rubyLocalVariableOrMethod xxx guifg=#5f63b4
    rubyGlobalVariable                          { gui="italic", fg="#5f63b4", }, -- rubyGlobalVariable xxx gui=italic guifg=#5f63b4
    rubyInstanceVariable                        { fg="#5f63b4", }, -- rubyInstanceVariable xxx guifg=#5f63b4
    rubyKeyword                                 { fg="#ba3934", }, -- rubyKeyword    xxx guifg=#ba3934
    rubyKeywordAsMethod                         { gui="bold", fg="#ba3934", }, -- rubyKeywordAsMethod xxx gui=bold guifg=#ba3934
    rubyClassDeclaration                        { gui="bold", fg="#ba3934", }, -- rubyClassDeclaration xxx gui=bold guifg=#ba3934
    rubyClass                                   { gui="bold", fg="#ba3934", }, -- rubyClass      xxx gui=bold guifg=#ba3934
    rubyNumber                                  { fg="#91b3af", }, -- rubyNumber     xxx guifg=#91b3af
    pythonBuiltinFunc                           { fg="#3d3b4b", }, -- pythonBuiltinFunc xxx guifg=#3d3b4b
    goBuiltins                                  { fg="#3d3b4b", }, -- goBuiltins     xxx guifg=#3d3b4b
    jsBuiltins                                  { fg="#3d3b4b", }, -- jsBuiltins     xxx guifg=#3d3b4b
    jsFunction                                  { gui="bold", fg="#ba3934", }, -- jsFunction     xxx gui=bold guifg=#ba3934
    jsGlobalObjects                             { fg="#ea7eae", }, -- jsGlobalObjects xxx guifg=#ea7eae
    jsAssignmentExps                            { fg="#5f63b4", }, -- jsAssignmentExps xxx guifg=#5f63b4
    htmlLink                                    { gui="underline", fg="#5f63b4", }, -- htmlLink       xxx gui=underline guifg=#5f63b4
    htmlStatement                               { fg="#ba3934", }, -- htmlStatement  xxx guifg=#ba3934
    htmlSpecialTagName                          { fg="#ba3934", }, -- htmlSpecialTagName xxx guifg=#ba3934
    mkdCode                                     { fg="#3d3b4b", }, -- mkdCode        xxx guifg=#3d3b4b
    CmpItemAbbrDefault                          { fg="#fadccf", }, -- CmpItemAbbrDefault xxx guifg=#fadccf
    CmpItemAbbr                                 { CmpItemAbbrDefault }, -- CmpItemAbbr    xxx links to CmpItemAbbrDefault
    CmpItemAbbrDeprecatedDefault                { fg="#808080", }, -- CmpItemAbbrDeprecatedDefault xxx guifg=#808080
    CmpItemAbbrDeprecated                       { CmpItemAbbrDeprecatedDefault }, -- CmpItemAbbrDeprecated xxx links to CmpItemAbbrDeprecatedDefault
    CmpItemAbbrMatchDefault                     { fg="#fadccf", }, -- CmpItemAbbrMatchDefault xxx guifg=#fadccf
    CmpItemAbbrMatch                            { CmpItemAbbrMatchDefault }, -- CmpItemAbbrMatch xxx links to CmpItemAbbrMatchDefault
    CmpItemAbbrMatchFuzzyDefault                { fg="#fadccf", }, -- CmpItemAbbrMatchFuzzyDefault xxx guifg=#fadccf
    CmpItemAbbrMatchFuzzy                       { CmpItemAbbrMatchFuzzyDefault }, -- CmpItemAbbrMatchFuzzy xxx links to CmpItemAbbrMatchFuzzyDefault
    CmpItemKindDefault                          { fg="#fadccf", }, -- CmpItemKindDefault xxx guifg=#fadccf
    CmpItemKind                                 { CmpItemKindDefault }, -- CmpItemKind    xxx links to CmpItemKindDefault
    CmpItemMenuDefault                          { fg="#fadccf", }, -- CmpItemMenuDefault xxx guifg=#fadccf
    CmpItemMenu                                 { CmpItemMenuDefault }, -- CmpItemMenu    xxx links to CmpItemMenuDefault
    NvimTreeRootFolder                          { fg="#3d3b4b", }, -- NvimTreeRootFolder xxx guifg=#3d3b4b
    NvimTreeFolderIcon                          { fg="#8094b4", }, -- NvimTreeFolderIcon xxx guifg=#8094b4
    NvimTreeClosedFolderIcon                    { NvimTreeFolderIcon }, -- NvimTreeClosedFolderIcon xxx links to NvimTreeFolderIcon
    NvimTreeOpenedFolderIcon                    { NvimTreeFolderIcon }, -- NvimTreeOpenedFolderIcon xxx links to NvimTreeFolderIcon
    NvimTreeSymlink                             { gui="bold", fg="#d2b9ae", }, -- NvimTreeSymlink xxx gui=bold guifg=#d2b9ae
    NvimTreeIndentMarker                        { fg="#8094b4", }, -- NvimTreeIndentMarker xxx guifg=#8094b4
    NvimTreeBookmark                            { fg="#ba3934", }, -- NvimTreeBookmark xxx guifg=#ba3934
    NvimTreeLiveFilterValue                     { gui="bold", }, -- NvimTreeLiveFilterValue xxx gui=bold
    NvimTreeLiveFilterPrefix                    { gui="bold", fg="#3d3b4b", }, -- NvimTreeLiveFilterPrefix xxx gui=bold guifg=#3d3b4b
    NvimTreeWindowPicker                        { bg="#4493c8", gui="bold", fg="#ededed", }, -- NvimTreeWindowPicker xxx gui=bold guifg=#ededed guibg=#4493c8
    NvimTreeGitNew                              { fg="#4b4b4c", }, -- NvimTreeGitNew xxx guifg=#4b4b4c
    NvimTreeFileNew                             { NvimTreeGitNew }, -- NvimTreeFileNew xxx links to NvimTreeGitNew
    NvimTreeGitRenamed                          { fg="#3d3b4b", }, -- NvimTreeGitRenamed xxx guifg=#3d3b4b
    NvimTreeFileRenamed                         { NvimTreeGitRenamed }, -- NvimTreeFileRenamed xxx links to NvimTreeGitRenamed
    NvimTreeGitMerge                            { fg="#5f63b4", }, -- NvimTreeGitMerge xxx guifg=#5f63b4
    NvimTreeFileMerge                           { NvimTreeGitMerge }, -- NvimTreeFileMerge xxx links to NvimTreeGitMerge
    NvimTreeGitStaged                           { fg="#ba3934", }, -- NvimTreeGitStaged xxx guifg=#ba3934
    NvimTreeFileStaged                          { NvimTreeGitStaged }, -- NvimTreeFileStaged xxx links to NvimTreeGitStaged
    NvimTreeGitDeleted                          { fg="#ff8800", }, -- NvimTreeGitDeleted xxx guifg=#ff8800
    NvimTreeFileDeleted                         { NvimTreeGitDeleted }, -- NvimTreeFileDeleted xxx links to NvimTreeGitDeleted
    NvimTreeGitDirty                            { fg="#ff8800", }, -- NvimTreeGitDirty xxx guifg=#ff8800
    NvimTreeFileDirty                           { NvimTreeGitDirty }, -- NvimTreeFileDirty xxx links to NvimTreeGitDirty
    NvimTreeModifiedFile                        { fg="#ba3934", }, -- NvimTreeModifiedFile xxx guifg=#ba3934
    NvimTreeOpenedFile                          { gui="bold", fg="#ba3934", }, -- NvimTreeOpenedFile xxx gui=bold guifg=#ba3934
    NvimTreeOpenedFileIcon                      { NvimTreeOpenedFile }, -- NvimTreeOpenedFileIcon xxx links to NvimTreeOpenedFile
    NvimTreeImageFile                           { gui="bold", fg="#3d3b4b", }, -- NvimTreeImageFile xxx gui=bold guifg=#3d3b4b
    NvimTreeSpecialFile                         { gui="bold,underline", fg="#4b4b4c", }, -- NvimTreeSpecialFile xxx gui=bold,underline guifg=#4b4b4c
    NvimTreeExecFile                            { gui="bold", fg="#ba3934", }, -- NvimTreeExecFile xxx gui=bold guifg=#ba3934
    DevIconBibTeX                               { fg="#cbcb41", }, -- DevIconBibTeX  xxx ctermfg=185 guifg=#cbcb41
    DevIconZshenv                               { fg="#89e051", }, -- DevIconZshenv  xxx ctermfg=113 guifg=#89e051
    DevIconZshprofile                           { fg="#89e051", }, -- DevIconZshprofile xxx ctermfg=113 guifg=#89e051
    DevIconZshrc                                { fg="#89e051", }, -- DevIconZshrc   xxx ctermfg=113 guifg=#89e051
    DevIconAwk                                  { fg="#4d5a5e", }, -- DevIconAwk     xxx ctermfg=240 guifg=#4d5a5e
    DevIconDockerfile                           { fg="#458ee6", }, -- DevIconDockerfile xxx ctermfg=68 guifg=#458ee6
    DevIconPy                                   { fg="#ffbc03", }, -- DevIconPy      xxx ctermfg=214 guifg=#ffbc03
    DevIconBashProfile                          { fg="#89e051", }, -- DevIconBashProfile xxx ctermfg=113 guifg=#89e051
    DevIconCobol                                { fg="#005ca5", }, -- DevIconCobol   xxx ctermfg=25 guifg=#005ca5
    DevIconPxd                                  { fg="#5aa7e4", }, -- DevIconPxd     xxx ctermfg=39 guifg=#5aa7e4
    DevIconTex                                  { fg="#3d6117", }, -- DevIconTex     xxx ctermfg=22 guifg=#3d6117
    DevIconTerraform                            { fg="#5f43e9", }, -- DevIconTerraform xxx ctermfg=93 guifg=#5f43e9
    DevIconTxt                                  { fg="#89e051", }, -- DevIconTxt     xxx ctermfg=113 guifg=#89e051
    DevIconAppleScript                          { fg="#6d8085", }, -- DevIconAppleScript xxx ctermfg=66 guifg=#6d8085
    DevIconLog                                  { fg="#ffffff", }, -- DevIconLog     xxx ctermfg=231 guifg=#ffffff
    DevIconBazel                                { fg="#89e051", }, -- DevIconBazel   xxx ctermfg=113 guifg=#89e051
    DevIconIni                                  { fg="#6d8086", }, -- DevIconIni     xxx ctermfg=66 guifg=#6d8086
    DevIconBat                                  { fg="#c1f12e", }, -- DevIconBat     xxx ctermfg=191 guifg=#c1f12e
    DevIconTerminal                             { fg="#31b53e", }, -- DevIconTerminal xxx ctermfg=34 guifg=#31b53e
    DevIconPm                                   { fg="#519aba", }, -- DevIconPm      xxx ctermfg=74 guifg=#519aba
    DevIconDart                                 { fg="#03589c", }, -- DevIconDart    xxx ctermfg=25 guifg=#03589c
    DevIconGulpfile                             { fg="#cc3e44", }, -- DevIconGulpfile xxx ctermfg=167 guifg=#cc3e44
    DevIconMaterial                             { fg="#b83998", }, -- DevIconMaterial xxx ctermfg=163 guifg=#b83998
    DevIconAvif                                 { fg="#a074c4", }, -- DevIconAvif    xxx ctermfg=140 guifg=#a074c4
    DevIconIco                                  { fg="#cbcb41", }, -- DevIconIco     xxx ctermfg=185 guifg=#cbcb41
    DevIconGitCommit                            { fg="#41535b", }, -- DevIconGitCommit xxx ctermfg=239 guifg=#41535b
    DevIconFsscript                             { fg="#519aba", }, -- DevIconFsscript xxx ctermfg=74 guifg=#519aba
    DevIconLock                                 { fg="#bbbbbb", }, -- DevIconLock    xxx ctermfg=250 guifg=#bbbbbb
    DevIconDoc                                  { fg="#185abd", }, -- DevIconDoc     xxx ctermfg=26 guifg=#185abd
    DevIconMustache                             { fg="#e37933", }, -- DevIconMustache xxx ctermfg=166 guifg=#e37933
    DevIconFsharp                               { fg="#519aba", }, -- DevIconFsharp  xxx ctermfg=74 guifg=#519aba
    DevIconRlib                                 { fg="#dea584", }, -- DevIconRlib    xxx ctermfg=216 guifg=#dea584
    DevIconSql                                  { fg="#dad8d8", }, -- DevIconSql     xxx ctermfg=188 guifg=#dad8d8
    DevIconXcPlayground                         { fg="#e37933", }, -- DevIconXcPlayground xxx ctermfg=166 guifg=#e37933
    DevIconPdf                                  { fg="#b30b00", }, -- DevIconPdf     xxx ctermfg=124 guifg=#b30b00
    DevIconXlsx                                 { fg="#207245", }, -- DevIconXlsx    xxx ctermfg=29 guifg=#207245
    DevIconMakefile                             { fg="#6d8086", }, -- DevIconMakefile xxx ctermfg=66 guifg=#6d8086
    DevIconCsv                                  { fg="#89e051", }, -- DevIconCsv     xxx ctermfg=113 guifg=#89e051
    DevIconWav                                  { fg="#66d8ef", }, -- DevIconWav     xxx ctermfg=45 guifg=#66d8ef
    DevIconSuo                                  { fg="#e37933", }, -- DevIconSuo     xxx ctermfg=166 guifg=#e37933
    DevIconGitLogo                              { fg="#f14c28", }, -- DevIconGitLogo xxx ctermfg=196 guifg=#f14c28
    DevIconRazorPage                            { fg="#512bd4", }, -- DevIconRazorPage xxx ctermfg=56 guifg=#512bd4
    DevIconSlim                                 { fg="#e34c26", }, -- DevIconSlim    xxx ctermfg=196 guifg=#e34c26
    DevIconRproj                                { fg="#358a5b", }, -- DevIconRproj   xxx ctermfg=29 guifg=#358a5b
    DevIconPyo                                  { fg="#ffe291", }, -- DevIconPyo     xxx ctermfg=222 guifg=#ffe291
    DevIconCrystal                              { fg="#c8c8c8", }, -- DevIconCrystal xxx ctermfg=251 guifg=#c8c8c8
    DevIconEmbeddedOpenTypeFont                 { fg="#ececec", }, -- DevIconEmbeddedOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconMli                                  { fg="#e37933", }, -- DevIconMli     xxx ctermfg=166 guifg=#e37933
    DevIconPsb                                  { fg="#519aba", }, -- DevIconPsb     xxx ctermfg=74 guifg=#519aba
    DevIconProcfile                             { fg="#a074c4", }, -- DevIconProcfile xxx ctermfg=140 guifg=#a074c4
    DevIconPpt                                  { fg="#cb4a32", }, -- DevIconPpt     xxx ctermfg=160 guifg=#cb4a32
    DevIconPackedResource                       { fg="#6d8086", }, -- DevIconPackedResource xxx ctermfg=66 guifg=#6d8086
    DevIconOpenTypeFont                         { fg="#ececec", }, -- DevIconOpenTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconHpp                                  { fg="#a074c4", }, -- DevIconHpp     xxx ctermfg=140 guifg=#a074c4
    DevIconOgg                                  { fg="#66d8ef", }, -- DevIconOgg     xxx ctermfg=45 guifg=#66d8ef
    DevIconNodeModules                          { fg="#e8274b", }, -- DevIconNodeModules xxx ctermfg=197 guifg=#e8274b
    DevIconPackageJson                          { fg="#e8274b", }, -- DevIconPackageJson xxx ctermfg=197 guifg=#e8274b
    DevIconCxx                                  { fg="#519aba", }, -- DevIconCxx     xxx ctermfg=74 guifg=#519aba
    DevIconCPlusPlus                            { fg="#f34b7d", }, -- DevIconCPlusPlus xxx ctermfg=204 guifg=#f34b7d
    DevIconJl                                   { fg="#a270ba", }, -- DevIconJl      xxx ctermfg=133 guifg=#a270ba
    DevIconMint                                 { fg="#87c095", }, -- DevIconMint    xxx ctermfg=108 guifg=#87c095
    DevIconM4V                                  { fg="#fd971f", }, -- DevIconM4V     xxx ctermfg=208 guifg=#fd971f
    DevIconHh                                   { fg="#a074c4", }, -- DevIconHh      xxx ctermfg=140 guifg=#a074c4
    DevIconLicense                              { fg="#cbcb41", }, -- DevIconLicense xxx ctermfg=185 guifg=#cbcb41
    DevIconMixLock                              { fg="#a074c4", }, -- DevIconMixLock xxx ctermfg=140 guifg=#a074c4
    DevIconGruntfile                            { fg="#e37933", }, -- DevIconGruntfile xxx ctermfg=166 guifg=#e37933
    DevIconGodotProject                         { fg="#6d8086", }, -- DevIconGodotProject xxx ctermfg=66 guifg=#6d8086
    DevIconWebmanifest                          { fg="#f1e05a", }, -- DevIconWebmanifest xxx ctermfg=185 guifg=#f1e05a
    DevIconFlac                                 { fg="#66d8ef", }, -- DevIconFlac    xxx ctermfg=45 guifg=#66d8ef
    DevIconEditorConfig                         { fg="#ffffff", }, -- DevIconEditorConfig xxx ctermfg=231 guifg=#ffffff
    DevIconDropbox                              { fg="#0061fe", }, -- DevIconDropbox xxx ctermfg=27 guifg=#0061fe
    DevIconZsh                                  { fg="#89e051", }, -- DevIconZsh     xxx ctermfg=113 guifg=#89e051
    DevIconDrools                               { fg="#ffafaf", }, -- DevIconDrools  xxx ctermfg=217 guifg=#ffafaf
    DevIconDocx                                 { fg="#185abd", }, -- DevIconDocx    xxx ctermfg=26 guifg=#185abd
    DevIconCson                                 { fg="#cbcb41", }, -- DevIconCson    xxx ctermfg=185 guifg=#cbcb41
    DevIconCp                                   { fg="#519aba", }, -- DevIconCp      xxx ctermfg=74 guifg=#519aba
    DevIconBmp                                  { fg="#a074c4", }, -- DevIconBmp     xxx ctermfg=140 guifg=#a074c4
    DevIconAac                                  { fg="#66d8ef", }, -- DevIconAac     xxx ctermfg=45 guifg=#66d8ef
    DevIconVagrantfile                          { fg="#1563ff", }, -- DevIconVagrantfile xxx ctermfg=27 guifg=#1563ff
    DevIconGemfile                              { fg="#701516", }, -- DevIconGemfile xxx ctermfg=52 guifg=#701516
    DevIconBrewfile                             { fg="#701516", }, -- DevIconBrewfile xxx ctermfg=52 guifg=#701516
    DevIconHurl                                 { fg="#ff0288", }, -- DevIconHurl    xxx ctermfg=198 guifg=#ff0288
    DevIconHrl                                  { fg="#b83998", }, -- DevIconHrl     xxx ctermfg=163 guifg=#b83998
    DevIconErl                                  { fg="#b83998", }, -- DevIconErl     xxx ctermfg=163 guifg=#b83998
    DevIconEpp                                  { fg="#ffa61a", }, -- DevIconEpp     xxx ctermfg=214 guifg=#ffa61a
    DevIconJava                                 { fg="#cc3e44", }, -- DevIconJava    xxx ctermfg=167 guifg=#cc3e44
    DevIconVlang                                { fg="#5d87bf", }, -- DevIconVlang   xxx ctermfg=67 guifg=#5d87bf
    DevIconConf                                 { fg="#6d8086", }, -- DevIconConf    xxx ctermfg=66 guifg=#6d8086
    DevIconConfigRu                             { fg="#701516", }, -- DevIconConfigRu xxx ctermfg=52 guifg=#701516
    DevIconPxi                                  { fg="#5aa7e4", }, -- DevIconPxi     xxx ctermfg=39 guifg=#5aa7e4
    DevIconClojureDart                          { fg="#519aba", }, -- DevIconClojureDart xxx ctermfg=74 guifg=#519aba
    DevIconWebp                                 { fg="#a074c4", }, -- DevIconWebp    xxx ctermfg=140 guifg=#a074c4
    DevIconGif                                  { fg="#a074c4", }, -- DevIconGif     xxx ctermfg=140 guifg=#a074c4
    DevIconPng                                  { fg="#a074c4", }, -- DevIconPng     xxx ctermfg=140 guifg=#a074c4
    DevIconJpeg                                 { fg="#a074c4", }, -- DevIconJpeg    xxx ctermfg=140 guifg=#a074c4
    DevIconJpg                                  { fg="#a074c4", }, -- DevIconJpg     xxx ctermfg=140 guifg=#a074c4
    DevIconHeex                                 { fg="#a074c4", }, -- DevIconHeex    xxx ctermfg=140 guifg=#a074c4
    DevIconAzureCli                             { fg="#0078d4", }, -- DevIconAzureCli xxx ctermfg=32 guifg=#0078d4
    DevIconToml                                 { fg="#ffffff", }, -- DevIconToml    xxx ctermfg=231 guifg=#ffffff
    DevIconMarkdown                             { fg="#519aba", }, -- DevIconMarkdown xxx ctermfg=74 guifg=#519aba
    DevIconHs                                   { fg="#a074c4", }, -- DevIconHs      xxx ctermfg=140 guifg=#a074c4
    DevIconMd                                   { fg="#ffffff", }, -- DevIconMd      xxx ctermfg=231 guifg=#ffffff
    DevIconTcl                                  { fg="#1e5cb3", }, -- DevIconTcl     xxx ctermfg=25 guifg=#1e5cb3
    DevIconVala                                 { fg="#7239b3", }, -- DevIconVala    xxx ctermfg=91 guifg=#7239b3
    DevIconHbs                                  { fg="#f0772b", }, -- DevIconHbs     xxx ctermfg=202 guifg=#f0772b
    DevIconHaml                                 { fg="#eaeae1", }, -- DevIconHaml    xxx ctermfg=255 guifg=#eaeae1
    DevIconSystemVerilog                        { fg="#019833", }, -- DevIconSystemVerilog xxx ctermfg=28 guifg=#019833
    DevIconSwift                                { fg="#e37933", }, -- DevIconSwift   xxx ctermfg=166 guifg=#e37933
    sym"DevIconPy.typed"                        { fg="#ffbc03", }, -- DevIconPy.typed xxx ctermfg=214 guifg=#ffbc03
    DevIconSvelte                               { fg="#ff3e00", }, -- DevIconSvelte  xxx ctermfg=196 guifg=#ff3e00
    DevIconPackageLockJson                      { fg="#7a0d21", }, -- DevIconPackageLockJson xxx ctermfg=52 guifg=#7a0d21
    DevIconWebOpenFontFormat                    { fg="#ececec", }, -- DevIconWebOpenFontFormat xxx ctermfg=255 guifg=#ececec
    DevIconGraphQL                              { fg="#e535ab", }, -- DevIconGraphQL xxx ctermfg=199 guifg=#e535ab
    DevIconRb                                   { fg="#701516", }, -- DevIconRb      xxx ctermfg=52 guifg=#701516
    DevIconFavicon                              { fg="#cbcb41", }, -- DevIconFavicon xxx ctermfg=185 guifg=#cbcb41
    DevIconTextResource                         { fg="#cbcb41", }, -- DevIconTextResource xxx ctermfg=185 guifg=#cbcb41
    DevIconCMakeLists                           { fg="#6d8086", }, -- DevIconCMakeLists xxx ctermfg=66 guifg=#6d8086
    DevIconLiquid                               { fg="#95bf47", }, -- DevIconLiquid  xxx ctermfg=106 guifg=#95bf47
    DevIconMotoko                               { fg="#9772fb", }, -- DevIconMotoko  xxx ctermfg=135 guifg=#9772fb
    DevIconEnv                                  { fg="#faf743", }, -- DevIconEnv     xxx ctermfg=227 guifg=#faf743
    DevIconBashrc                               { fg="#89e051", }, -- DevIconBashrc  xxx ctermfg=113 guifg=#89e051
    DevIconFsx                                  { fg="#519aba", }, -- DevIconFsx     xxx ctermfg=74 guifg=#519aba
    DevIconFsi                                  { fg="#519aba", }, -- DevIconFsi     xxx ctermfg=74 guifg=#519aba
    DevIconLhs                                  { fg="#a074c4", }, -- DevIconLhs     xxx ctermfg=140 guifg=#a074c4
    DevIconSettingsJson                         { fg="#854cc7", }, -- DevIconSettingsJson xxx ctermfg=98 guifg=#854cc7
    DevIconHtm                                  { fg="#e34c26", }, -- DevIconHtm     xxx ctermfg=196 guifg=#e34c26
    DevIconVerilog                              { fg="#019833", }, -- DevIconVerilog xxx ctermfg=28 guifg=#019833
    DevIconLess                                 { fg="#563d7c", }, -- DevIconLess    xxx ctermfg=54 guifg=#563d7c
    DevIconH                                    { fg="#a074c4", }, -- DevIconH       xxx ctermfg=140 guifg=#a074c4
    DevIconGvimrc                               { fg="#019833", }, -- DevIconGvimrc  xxx ctermfg=28 guifg=#019833
    DevIconDesktopEntry                         { fg="#563d7c", }, -- DevIconDesktopEntry xxx ctermfg=54 guifg=#563d7c
    DevIconD                                    { fg="#427819", }, -- DevIconD       xxx ctermfg=28 guifg=#427819
    DevIconPyi                                  { fg="#ffbc03", }, -- DevIconPyi     xxx ctermfg=214 guifg=#ffbc03
    DevIconScss                                 { fg="#f55385", }, -- DevIconScss    xxx ctermfg=204 guifg=#f55385
    DevIconDsStore                              { fg="#41535b", }, -- DevIconDsStore xxx ctermfg=239 guifg=#41535b
    DevIconCoffee                               { fg="#cbcb41", }, -- DevIconCoffee  xxx ctermfg=185 guifg=#cbcb41
    DevIconClojure                              { fg="#8dc149", }, -- DevIconClojure xxx ctermfg=113 guifg=#8dc149
    DevIconScheme                               { fg="#000000", }, -- DevIconScheme  xxx ctermfg=16 guifg=#000000
    DevIconElm                                  { fg="#519aba", }, -- DevIconElm     xxx ctermfg=74 guifg=#519aba
    DevIconsbt                                  { fg="#cc3e44", }, -- DevIconsbt     xxx ctermfg=167 guifg=#cc3e44
    DevIconPsManifestfile                       { fg="#6975c4", }, -- DevIconPsManifestfile xxx ctermfg=68 guifg=#6975c4
    DevIconLeex                                 { fg="#a074c4", }, -- DevIconLeex    xxx ctermfg=140 guifg=#a074c4
    DevIconTypeScriptReactTest                  { fg="#1354bf", }, -- DevIconTypeScriptReactTest xxx ctermfg=26 guifg=#1354bf
    DevIconJson                                 { fg="#cbcb41", }, -- DevIconJson    xxx ctermfg=185 guifg=#cbcb41
    DevIconVim                                  { fg="#019833", }, -- DevIconVim     xxx ctermfg=28 guifg=#019833
    DevIconRs                                   { fg="#dea584", }, -- DevIconRs      xxx ctermfg=216 guifg=#dea584
    DevIconRake                                 { fg="#701516", }, -- DevIconRake    xxx ctermfg=52 guifg=#701516
    DevIconLuau                                 { fg="#00a2ff", }, -- DevIconLuau    xxx ctermfg=75 guifg=#00a2ff
    DevIconGemspec                              { fg="#701516", }, -- DevIconGemspec xxx ctermfg=52 guifg=#701516
    DevIconNix                                  { fg="#7ebae4", }, -- DevIconNix     xxx ctermfg=110 guifg=#7ebae4
    DevIconNim                                  { fg="#f3d400", }, -- DevIconNim     xxx ctermfg=220 guifg=#f3d400
    DevIconWebpack                              { fg="#519aba", }, -- DevIconWebpack xxx ctermfg=74 guifg=#519aba
    DevIconDefault                              { fg="#6d8086", }, -- DevIconDefault xxx ctermfg=66 guifg=#6d8086
    DevIconLua                                  { fg="#51a0cf", }, -- DevIconLua     xxx ctermfg=74 guifg=#51a0cf
    DevIconXul                                  { fg="#e37933", }, -- DevIconXul     xxx ctermfg=166 guifg=#e37933
    DevIconSml                                  { fg="#e37933", }, -- DevIconSml     xxx ctermfg=166 guifg=#e37933
    DevIconFs                                   { fg="#519aba", }, -- DevIconFs      xxx ctermfg=74 guifg=#519aba
    DevIconTypeScriptReactSpec                  { fg="#1354bf", }, -- DevIconTypeScriptReactSpec xxx ctermfg=26 guifg=#1354bf
    DevIconSpecTs                               { fg="#519aba", }, -- DevIconSpecTs  xxx ctermfg=74 guifg=#519aba
    DevIconJavaScriptReactSpec                  { fg="#20c2e3", }, -- DevIconJavaScriptReactSpec xxx ctermfg=45 guifg=#20c2e3
    DevIconSpecJs                               { fg="#cbcb41", }, -- DevIconSpecJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconVue                                  { fg="#8dc149", }, -- DevIconVue     xxx ctermfg=113 guifg=#8dc149
    DevIconImportConfiguration                  { fg="#ececec", }, -- DevIconImportConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconBazelBuild                           { fg="#89e051", }, -- DevIconBazelBuild xxx ctermfg=113 guifg=#89e051
    DevIconReScriptInterface                    { fg="#f55385", }, -- DevIconReScriptInterface xxx ctermfg=204 guifg=#f55385
    DevIconReScript                             { fg="#cc3e44", }, -- DevIconReScript xxx ctermfg=167 guifg=#cc3e44
    DevIconVHDL                                 { fg="#019833", }, -- DevIconVHDL    xxx ctermfg=28 guifg=#019833
    DevIconQuery                                { fg="#90a850", }, -- DevIconQuery   xxx ctermfg=107 guifg=#90a850
    DevIconEex                                  { fg="#a074c4", }, -- DevIconEex     xxx ctermfg=140 guifg=#a074c4
    DevIconBzl                                  { fg="#89e051", }, -- DevIconBzl     xxx ctermfg=113 guifg=#89e051
    DevIconTsx                                  { fg="#1354bf", }, -- DevIconTsx     xxx ctermfg=26 guifg=#1354bf
    DevIconCts                                  { fg="#519aba", }, -- DevIconCts     xxx ctermfg=74 guifg=#519aba
    DevIconMts                                  { fg="#519aba", }, -- DevIconMts     xxx ctermfg=74 guifg=#519aba
    DevIconTwig                                 { fg="#8dc149", }, -- DevIconTwig    xxx ctermfg=113 guifg=#8dc149
    DevIconCsh                                  { fg="#4d5a5e", }, -- DevIconCsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconCpp                                  { fg="#519aba", }, -- DevIconCpp     xxx ctermfg=74 guifg=#519aba
    DevIconPrisma                               { fg="#ffffff", }, -- DevIconPrisma  xxx ctermfg=231 guifg=#ffffff
    DevIconTFVars                               { fg="#5f43e9", }, -- DevIconTFVars  xxx ctermfg=93 guifg=#5f43e9
    DevIconJsonc                                { fg="#cbcb41", }, -- DevIconJsonc   xxx ctermfg=185 guifg=#cbcb41
    DevIconEdn                                  { fg="#519aba", }, -- DevIconEdn     xxx ctermfg=74 guifg=#519aba
    DevIconEx                                   { fg="#a074c4", }, -- DevIconEx      xxx ctermfg=140 guifg=#a074c4
    DevIconHtml                                 { fg="#e44d26", }, -- DevIconHtml    xxx ctermfg=196 guifg=#e44d26
    DevIconPl                                   { fg="#519aba", }, -- DevIconPl      xxx ctermfg=74 guifg=#519aba
    DevIconR                                    { fg="#2266ba", }, -- DevIconR       xxx ctermfg=25 guifg=#2266ba
    DevIconBash                                 { fg="#89e051", }, -- DevIconBash    xxx ctermfg=113 guifg=#89e051
    DevIconSh                                   { fg="#4d5a5e", }, -- DevIconSh      xxx ctermfg=240 guifg=#4d5a5e
    DevIconKsh                                  { fg="#4d5a5e", }, -- DevIconKsh     xxx ctermfg=240 guifg=#4d5a5e
    DevIconSig                                  { fg="#e37933", }, -- DevIconSig     xxx ctermfg=166 guifg=#e37933
    DevIconTor                                  { fg="#519aba", }, -- DevIconTor     xxx ctermfg=74 guifg=#519aba
    DevIconXml                                  { fg="#e37933", }, -- DevIconXml     xxx ctermfg=166 guifg=#e37933
    DevIconProlog                               { fg="#e4b854", }, -- DevIconProlog  xxx ctermfg=179 guifg=#e4b854
    DevIconPsScriptfile                         { fg="#4273ca", }, -- DevIconPsScriptfile xxx ctermfg=68 guifg=#4273ca
    DevIconGitlabCI                             { fg="#e24329", }, -- DevIconGitlabCI xxx ctermfg=196 guifg=#e24329
    DevIconClojureC                             { fg="#8dc149", }, -- DevIconClojureC xxx ctermfg=113 guifg=#8dc149
    DevIconPp                                   { fg="#ffa61a", }, -- DevIconPp      xxx ctermfg=214 guifg=#ffa61a
    DevIconHxx                                  { fg="#a074c4", }, -- DevIconHxx     xxx ctermfg=140 guifg=#a074c4
    DevIconM4A                                  { fg="#66d8ef", }, -- DevIconM4A     xxx ctermfg=45 guifg=#66d8ef
    DevIconPyc                                  { fg="#ffe291", }, -- DevIconPyc     xxx ctermfg=222 guifg=#ffe291
    DevIconPyd                                  { fg="#ffe291", }, -- DevIconPyd     xxx ctermfg=222 guifg=#ffe291
    DevIconClojureJS                            { fg="#519aba", }, -- DevIconClojureJS xxx ctermfg=74 guifg=#519aba
    DevIconConfiguration                        { fg="#ececec", }, -- DevIconConfiguration xxx ctermfg=255 guifg=#ececec
    DevIconYml                                  { fg="#6d8086", }, -- DevIconYml     xxx ctermfg=66 guifg=#6d8086
    DevIconOrgMode                              { fg="#77aa99", }, -- DevIconOrgMode xxx ctermfg=73 guifg=#77aa99
    DevIconOPUS                                 { fg="#f88a02", }, -- DevIconOPUS    xxx ctermfg=208 guifg=#f88a02
    DevIconRss                                  { fg="#fb9d3b", }, -- DevIconRss     xxx ctermfg=215 guifg=#fb9d3b
    DevIconFish                                 { fg="#4d5a5e", }, -- DevIconFish    xxx ctermfg=240 guifg=#4d5a5e
    DevIconCSharpProject                        { fg="#512bd4", }, -- DevIconCSharpProject xxx ctermfg=56 guifg=#512bd4
    DevIconSln                                  { fg="#854cc7", }, -- DevIconSln     xxx ctermfg=98 guifg=#854cc7
    DevIconMl                                   { fg="#e37933", }, -- DevIconMl      xxx ctermfg=166 guifg=#e37933
    DevIconBazelWorkspace                       { fg="#89e051", }, -- DevIconBazelWorkspace xxx ctermfg=113 guifg=#89e051
    DevIconSolidity                             { fg="#519aba", }, -- DevIconSolidity xxx ctermfg=74 guifg=#519aba
    DevIconStyl                                 { fg="#8dc149", }, -- DevIconStyl    xxx ctermfg=113 guifg=#8dc149
    DevIconC                                    { fg="#599eff", }, -- DevIconC       xxx ctermfg=111 guifg=#599eff
    DevIconSvelteConfig                         { fg="#ff3e00", }, -- DevIconSvelteConfig xxx ctermfg=196 guifg=#ff3e00
    DevIconRakefile                             { fg="#701516", }, -- DevIconRakefile xxx ctermfg=52 guifg=#701516
    DevIconXaml                                 { fg="#512bd4", }, -- DevIconXaml    xxx ctermfg=56 guifg=#512bd4
    DevIconJavaScriptReactTest                  { fg="#20c2e3", }, -- DevIconJavaScriptReactTest xxx ctermfg=45 guifg=#20c2e3
    DevIconSvg                                  { fg="#ffb13b", }, -- DevIconSvg     xxx ctermfg=214 guifg=#ffb13b
    DevIconTs                                   { fg="#519aba", }, -- DevIconTs      xxx ctermfg=74 guifg=#519aba
    DevIconTextScene                            { fg="#a074c4", }, -- DevIconTextScene xxx ctermfg=140 guifg=#a074c4
    DevIconMjs                                  { fg="#f1e05a", }, -- DevIconMjs     xxx ctermfg=185 guifg=#f1e05a
    DevIconJs                                   { fg="#cbcb41", }, -- DevIconJs      xxx ctermfg=185 guifg=#cbcb41
    DevIconWasm                                 { fg="#5c4cdb", }, -- DevIconWasm    xxx ctermfg=62 guifg=#5c4cdb
    DevIconCjs                                  { fg="#cbcb41", }, -- DevIconCjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconLuaurc                               { fg="#00a2ff", }, -- DevIconLuaurc  xxx ctermfg=75 guifg=#00a2ff
    DevIconZig                                  { fg="#f69a1b", }, -- DevIconZig     xxx ctermfg=172 guifg=#f69a1b
    DevIconJsx                                  { fg="#20c2e3", }, -- DevIconJsx     xxx ctermfg=45 guifg=#20c2e3
    DevIconDb                                   { fg="#dad8d8", }, -- DevIconDb      xxx ctermfg=188 guifg=#dad8d8
    DevIconBinaryGLTF                           { fg="#ffb13b", }, -- DevIconBinaryGLTF xxx ctermfg=214 guifg=#ffb13b
    DevIconWebm                                 { fg="#fd971f", }, -- DevIconWebm    xxx ctermfg=208 guifg=#fd971f
    DevIconKotlinScript                         { fg="#7f52ff", }, -- DevIconKotlinScript xxx ctermfg=99 guifg=#7f52ff
    DevIconKotlin                               { fg="#7f52ff", }, -- DevIconKotlin  xxx ctermfg=99 guifg=#7f52ff
    DevIconSass                                 { fg="#f55385", }, -- DevIconSass    xxx ctermfg=204 guifg=#f55385
    DevIconTestJs                               { fg="#cbcb41", }, -- DevIconTestJs  xxx ctermfg=185 guifg=#cbcb41
    DevIconPsScriptModulefile                   { fg="#6975c4", }, -- DevIconPsScriptModulefile xxx ctermfg=68 guifg=#6975c4
    DevIconScala                                { fg="#cc3e44", }, -- DevIconScala   xxx ctermfg=167 guifg=#cc3e44
    DevIconPyx                                  { fg="#5aa7e4", }, -- DevIconPyx     xxx ctermfg=39 guifg=#5aa7e4
    DevIconTrueTypeFont                         { fg="#ececec", }, -- DevIconTrueTypeFont xxx ctermfg=255 guifg=#ececec
    DevIconPhp                                  { fg="#a074c4", }, -- DevIconPhp     xxx ctermfg=140 guifg=#a074c4
    DevIconEslintrc                             { fg="#4b32c3", }, -- DevIconEslintrc xxx ctermfg=56 guifg=#4b32c3
    DevIconBabelrc                              { fg="#cbcb41", }, -- DevIconBabelrc xxx ctermfg=185 guifg=#cbcb41
    DevIconVimrc                                { fg="#019833", }, -- DevIconVimrc   xxx ctermfg=28 guifg=#019833
    DevIconGDScript                             { fg="#6d8086", }, -- DevIconGDScript xxx ctermfg=66 guifg=#6d8086
    DevIconCss                                  { fg="#42a5f5", }, -- DevIconCss     xxx ctermfg=75 guifg=#42a5f5
    DevIconGo                                   { fg="#519aba", }, -- DevIconGo      xxx ctermfg=74 guifg=#519aba
    DevIconHuff                                 { fg="#4242c7", }, -- DevIconHuff    xxx ctermfg=56 guifg=#4242c7
    DevIconAi                                   { fg="#cbcb41", }, -- DevIconAi      xxx ctermfg=185 guifg=#cbcb41
    DevIconExs                                  { fg="#a074c4", }, -- DevIconExs     xxx ctermfg=140 guifg=#a074c4
    DevIconTestTs                               { fg="#519aba", }, -- DevIconTestTs  xxx ctermfg=74 guifg=#519aba
    DevIconFortran                              { fg="#734f96", }, -- DevIconFortran xxx ctermfg=97 guifg=#734f96
    DevIconMdx                                  { fg="#519aba", }, -- DevIconMdx     xxx ctermfg=74 guifg=#519aba
    DevIconEjs                                  { fg="#cbcb41", }, -- DevIconEjs     xxx ctermfg=185 guifg=#cbcb41
    DevIconErb                                  { fg="#701516", }, -- DevIconErb     xxx ctermfg=52 guifg=#701516
    DevIconJson5                                { fg="#cbcb41", }, -- DevIconJson5   xxx ctermfg=185 guifg=#cbcb41
    DevIconDiff                                 { fg="#41535b", }, -- DevIconDiff    xxx ctermfg=239 guifg=#41535b
    DevIconCMake                                { fg="#6d8086", }, -- DevIconCMake   xxx ctermfg=66 guifg=#6d8086
    DevIconJpegXl                               { fg="#a074c4", }, -- DevIconJpegXl  xxx ctermfg=140 guifg=#a074c4
    DevIconMkv                                  { fg="#fd971f", }, -- DevIconMkv     xxx ctermfg=208 guifg=#fd971f
    DevIconMOV                                  { fg="#fd971f", }, -- DevIconMOV     xxx ctermfg=208 guifg=#fd971f
    DevIconMp3                                  { fg="#66d8ef", }, -- DevIconMp3     xxx ctermfg=45 guifg=#66d8ef
    DevIconMp4                                  { fg="#fd971f", }, -- DevIconMp4     xxx ctermfg=208 guifg=#fd971f
    DevIconNswag                                { fg="#85ea2d", }, -- DevIconNswag   xxx ctermfg=112 guifg=#85ea2d
    DevIconFennel                               { fg="#fff3d7", }, -- DevIconFennel  xxx ctermfg=230 guifg=#fff3d7
    DevIconGitIgnore                            { fg="#41535b", }, -- DevIconGitIgnore xxx ctermfg=239 guifg=#41535b
    DevIconGitAttributes                        { fg="#41535b", }, -- DevIconGitAttributes xxx ctermfg=239 guifg=#41535b
    DevIconGitModules                           { fg="#41535b", }, -- DevIconGitModules xxx ctermfg=239 guifg=#41535b
    DevIconGitConfig                            { fg="#41535b", }, -- DevIconGitConfig xxx ctermfg=239 guifg=#41535b
    DevIconXls                                  { fg="#207245", }, -- DevIconXls     xxx ctermfg=29 guifg=#207245
    DevIconPsd                                  { fg="#519aba", }, -- DevIconPsd     xxx ctermfg=74 guifg=#519aba
    DevIconYaml                                 { fg="#6d8086", }, -- DevIconYaml    xxx ctermfg=66 guifg=#6d8086
    DevIconNPMIgnore                            { fg="#e8274b", }, -- DevIconNPMIgnore xxx ctermfg=197 guifg=#e8274b
    DevIconCs                                   { fg="#596706", }, -- DevIconCs      xxx ctermfg=58 guifg=#596706
    DevIconDump                                 { fg="#dad8d8", }, -- DevIconDump    xxx ctermfg=188 guifg=#dad8d8
    DevIconNPMrc                                { fg="#e8274b", }, -- DevIconNPMrc   xxx ctermfg=197 guifg=#e8274b
    DevIconRmd                                  { fg="#519aba", }, -- DevIconRmd     xxx ctermfg=74 guifg=#519aba
    NeoscrollHiddenCursor                       { gui="reverse", blend=100, }, -- NeoscrollHiddenCursor xxx gui=reverse blend=100
    MiniAnimateCursor                           { gui="reverse,nocombine", }, -- MiniAnimateCursor xxx cterm=reverse,nocombine gui=reverse,nocombine
    MiniAnimateNormalFloat                      { }, -- MiniAnimateNormalFloat xxx cterm= gui=
    lualine_b_normal                            { bg="#000000", fg="#d13434", }, -- lualine_b_normal xxx guifg=#d13434 guibg=#000000
    lualine_a_normal                            { bg="#d13434", gui="bold", fg="#000000", }, -- lualine_a_normal xxx gui=bold guifg=#000000 guibg=#d13434
    lualine_c_normal                            { bg="#18292f", fg="#ffffff", }, -- lualine_c_normal xxx guifg=#ffffff guibg=#18292f
    lualine_b_visual                            { bg="#000000", fg="#33e7e1", }, -- lualine_b_visual xxx guifg=#33e7e1 guibg=#000000
    lualine_a_visual                            { bg="#33e7e1", gui="bold", fg="#000000", }, -- lualine_a_visual xxx gui=bold guifg=#000000 guibg=#33e7e1
    lualine_c_visual                            { bg="#18292f", fg="#ffffff", }, -- lualine_c_visual xxx guifg=#ffffff guibg=#18292f
    lualine_b_insert                            { bg="#000000", fg="#1bbcdd", }, -- lualine_b_insert xxx guifg=#1bbcdd guibg=#000000
    lualine_a_insert                            { bg="#1bbcdd", gui="bold", fg="#000000", }, -- lualine_a_insert xxx gui=bold guifg=#000000 guibg=#1bbcdd
    lualine_c_insert                            { bg="#18292f", fg="#ffffff", }, -- lualine_c_insert xxx guifg=#ffffff guibg=#18292f
    lualine_b_command                           { bg="#000000", fg="#fca3b3", }, -- lualine_b_command xxx guifg=#fca3b3 guibg=#000000
    lualine_a_command                           { bg="#fca3b3", gui="bold", fg="#000000", }, -- lualine_a_command xxx gui=bold guifg=#000000 guibg=#fca3b3
    lualine_c_command                           { bg="#18292f", fg="#ffffff", }, -- lualine_c_command xxx guifg=#ffffff guibg=#18292f
    lualine_b_replace                           { bg="#000000", fg="#44b5a1", }, -- lualine_b_replace xxx guifg=#44b5a1 guibg=#000000
    lualine_a_replace                           { bg="#44b5a1", gui="bold", fg="#000000", }, -- lualine_a_replace xxx gui=bold guifg=#000000 guibg=#44b5a1
    lualine_c_replace                           { bg="#18292f", fg="#ffffff", }, -- lualine_c_replace xxx guifg=#ffffff guibg=#18292f
    lualine_b_diff_added_normal                 { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_added_normal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_insert                 { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_added_insert xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_visual                 { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_added_visual xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_replace                { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_added_replace xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_command                { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_added_command xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_terminal               { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_added_terminal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_added_inactive               { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_added_inactive xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_normal              { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_modified_normal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_insert              { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_modified_insert xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_visual              { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_modified_visual xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_replace             { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_modified_replace xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_command             { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_modified_command xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_terminal            { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_modified_terminal xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_modified_inactive            { bg="#000000", fg="#fafafa", }, -- lualine_b_diff_modified_inactive xxx guifg=#fafafa guibg=#000000
    lualine_b_diff_removed_normal               { bg="#000000", fg="#0000ff", }, -- lualine_b_diff_removed_normal xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_insert               { bg="#000000", fg="#0000ff", }, -- lualine_b_diff_removed_insert xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_visual               { bg="#000000", fg="#0000ff", }, -- lualine_b_diff_removed_visual xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_replace              { bg="#000000", fg="#0000ff", }, -- lualine_b_diff_removed_replace xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_command              { bg="#000000", fg="#0000ff", }, -- lualine_b_diff_removed_command xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_terminal             { bg="#000000", fg="#0000ff", }, -- lualine_b_diff_removed_terminal xxx guifg=#0000ff guibg=#000000
    lualine_b_diff_removed_inactive             { bg="#000000", fg="#0000ff", }, -- lualine_b_diff_removed_inactive xxx guifg=#0000ff guibg=#000000
    lualine_b_diagnostics_error_normal          { bg="#000000", fg="#ff0000", }, -- lualine_b_diagnostics_error_normal xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_insert          { bg="#000000", fg="#ff0000", }, -- lualine_b_diagnostics_error_insert xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_visual          { bg="#000000", fg="#ff0000", }, -- lualine_b_diagnostics_error_visual xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_replace         { bg="#000000", fg="#ff0000", }, -- lualine_b_diagnostics_error_replace xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_command         { bg="#000000", fg="#ff0000", }, -- lualine_b_diagnostics_error_command xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_terminal        { bg="#000000", fg="#ff0000", }, -- lualine_b_diagnostics_error_terminal xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_error_inactive        { bg="#000000", fg="#ff0000", }, -- lualine_b_diagnostics_error_inactive xxx guifg=#ff0000 guibg=#000000
    lualine_b_diagnostics_warn_normal           { bg="#000000", fg="#ffa500", }, -- lualine_b_diagnostics_warn_normal xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_insert           { bg="#000000", fg="#ffa500", }, -- lualine_b_diagnostics_warn_insert xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_visual           { bg="#000000", fg="#ffa500", }, -- lualine_b_diagnostics_warn_visual xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_replace          { bg="#000000", fg="#ffa500", }, -- lualine_b_diagnostics_warn_replace xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_command          { bg="#000000", fg="#ffa500", }, -- lualine_b_diagnostics_warn_command xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_terminal         { bg="#000000", fg="#ffa500", }, -- lualine_b_diagnostics_warn_terminal xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_warn_inactive         { bg="#000000", fg="#ffa500", }, -- lualine_b_diagnostics_warn_inactive xxx guifg=#ffa500 guibg=#000000
    lualine_b_diagnostics_info_normal           { bg="#000000", fg="#add8e6", }, -- lualine_b_diagnostics_info_normal xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_insert           { bg="#000000", fg="#add8e6", }, -- lualine_b_diagnostics_info_insert xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_visual           { bg="#000000", fg="#add8e6", }, -- lualine_b_diagnostics_info_visual xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_replace          { bg="#000000", fg="#add8e6", }, -- lualine_b_diagnostics_info_replace xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_command          { bg="#000000", fg="#add8e6", }, -- lualine_b_diagnostics_info_command xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_terminal         { bg="#000000", fg="#add8e6", }, -- lualine_b_diagnostics_info_terminal xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_info_inactive         { bg="#000000", fg="#add8e6", }, -- lualine_b_diagnostics_info_inactive xxx guifg=#add8e6 guibg=#000000
    lualine_b_diagnostics_hint_normal           { bg="#000000", fg="#d3d3d3", }, -- lualine_b_diagnostics_hint_normal xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_insert           { bg="#000000", fg="#d3d3d3", }, -- lualine_b_diagnostics_hint_insert xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_visual           { bg="#000000", fg="#d3d3d3", }, -- lualine_b_diagnostics_hint_visual xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_replace          { bg="#000000", fg="#d3d3d3", }, -- lualine_b_diagnostics_hint_replace xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_command          { bg="#000000", fg="#d3d3d3", }, -- lualine_b_diagnostics_hint_command xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_terminal         { bg="#000000", fg="#d3d3d3", }, -- lualine_b_diagnostics_hint_terminal xxx guifg=#d3d3d3 guibg=#000000
    lualine_b_diagnostics_hint_inactive         { bg="#000000", fg="#d3d3d3", }, -- lualine_b_diagnostics_hint_inactive xxx guifg=#d3d3d3 guibg=#000000
    DapUIScope                                  { fg="#00f1f5", }, -- DapUIScope     xxx guifg=#00f1f5
    DapUIType                                   { fg="#d484ff", }, -- DapUIType      xxx guifg=#d484ff
    DapUIModifiedValue                          { gui="bold", fg="#00f1f5", }, -- DapUIModifiedValue xxx gui=bold guifg=#00f1f5
    DapUIDecoration                             { fg="#00f1f5", }, -- DapUIDecoration xxx guifg=#00f1f5
    DapUIThread                                 { fg="#a9ff68", }, -- DapUIThread    xxx guifg=#a9ff68
    DapUIStoppedThread                          { fg="#00f1f5", }, -- DapUIStoppedThread xxx guifg=#00f1f5
    DapUISource                                 { fg="#d484ff", }, -- DapUISource    xxx guifg=#d484ff
    DapUILineNumber                             { fg="#00f1f5", }, -- DapUILineNumber xxx guifg=#00f1f5
    DapUIBreakpointsLine                        { DapUILineNumber }, -- DapUIBreakpointsLine xxx links to DapUILineNumber
    DapUIFloatBorder                            { fg="#00f1f5", }, -- DapUIFloatBorder xxx guifg=#00f1f5
    DapUIWatchesEmpty                           { fg="#f70067", }, -- DapUIWatchesEmpty xxx guifg=#f70067
    DapUIWatchesValue                           { fg="#a9ff68", }, -- DapUIWatchesValue xxx guifg=#a9ff68
    DapUIWatchesError                           { fg="#f70067", }, -- DapUIWatchesError xxx guifg=#f70067
    DapUIBreakpointsPath                        { fg="#00f1f5", }, -- DapUIBreakpointsPath xxx guifg=#00f1f5
    DapUIBreakpointsInfo                        { fg="#a9ff68", }, -- DapUIBreakpointsInfo xxx guifg=#a9ff68
    DapUIBreakpointsCurrentLine                 { gui="bold", fg="#a9ff68", }, -- DapUIBreakpointsCurrentLine xxx gui=bold guifg=#a9ff68
    DapUICurrentFrameName                       { DapUIBreakpointsCurrentLine }, -- DapUICurrentFrameName xxx links to DapUIBreakpointsCurrentLine
    DapUIBreakpointsDisabledLine                { fg="#424242", }, -- DapUIBreakpointsDisabledLine xxx guifg=#424242
    DapUIStepOver                               { fg="#00f1f5", }, -- DapUIStepOver  xxx guifg=#00f1f5
    DapUIStepInto                               { fg="#00f1f5", }, -- DapUIStepInto  xxx guifg=#00f1f5
    DapUIStepBack                               { fg="#00f1f5", }, -- DapUIStepBack  xxx guifg=#00f1f5
    DapUIStepOut                                { fg="#00f1f5", }, -- DapUIStepOut   xxx guifg=#00f1f5
    DapUIStop                                   { fg="#f70067", }, -- DapUIStop      xxx guifg=#f70067
    DapUIPlayPause                              { fg="#a9ff68", }, -- DapUIPlayPause xxx guifg=#a9ff68
    DapUIRestart                                { fg="#a9ff68", }, -- DapUIRestart   xxx guifg=#a9ff68
    DapUIUnavailable                            { fg="#424242", }, -- DapUIUnavailable xxx guifg=#424242
    DapUIWinSelect                              { gui="bold", fg="#00f1f5", }, -- DapUIWinSelect xxx ctermfg=14 gui=bold guifg=#00f1f5
    DapUINormalNC                               { }, -- DapUINormalNC  xxx cterm= gui=
    DapUIPlayPauseNC                            { fg="#a9ff68", }, -- DapUIPlayPauseNC xxx cterm= gui= guifg=#a9ff68
    DapUIRestartNC                              { fg="#a9ff68", }, -- DapUIRestartNC xxx cterm= gui= guifg=#a9ff68
    DapUIStopNC                                 { fg="#f70067", }, -- DapUIStopNC    xxx cterm= gui= guifg=#f70067
    DapUIUnavailableNC                          { fg="#424242", }, -- DapUIUnavailableNC xxx cterm= gui= guifg=#424242
    DapUIStepOverNC                             { fg="#00f1f5", }, -- DapUIStepOverNC xxx cterm= gui= guifg=#00f1f5
    DapUIStepIntoNC                             { fg="#00f1f5", }, -- DapUIStepIntoNC xxx cterm= gui= guifg=#00f1f5
    DapUIStepBackNC                             { fg="#00f1f5", }, -- DapUIStepBackNC xxx cterm= gui= guifg=#00f1f5
    DapUIStepOutNC                              { fg="#00f1f5", }, -- DapUIStepOutNC xxx cterm= gui= guifg=#00f1f5
    lualine_x_filetype_DevIconDefault_normal    { bg="#18292f", fg="#6d8086", }, -- lualine_x_filetype_DevIconDefault_normal xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_insert    { bg="#18292f", fg="#6d8086", }, -- lualine_x_filetype_DevIconDefault_insert xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_visual    { bg="#18292f", fg="#6d8086", }, -- lualine_x_filetype_DevIconDefault_visual xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_replace   { bg="#18292f", fg="#6d8086", }, -- lualine_x_filetype_DevIconDefault_replace xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_command   { bg="#18292f", fg="#6d8086", }, -- lualine_x_filetype_DevIconDefault_command xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_terminal  { bg="#18292f", fg="#6d8086", }, -- lualine_x_filetype_DevIconDefault_terminal xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconDefault_inactive  { bg="#18292f", fg="#6d8086", }, -- lualine_x_filetype_DevIconDefault_inactive xxx guifg=#6d8086 guibg=#18292f
    lualine_x_filetype_DevIconLua_normal        { bg="#18292f", fg="#51a0cf", }, -- lualine_x_filetype_DevIconLua_normal xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_insert        { bg="#18292f", fg="#51a0cf", }, -- lualine_x_filetype_DevIconLua_insert xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_visual        { bg="#18292f", fg="#51a0cf", }, -- lualine_x_filetype_DevIconLua_visual xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_replace       { bg="#18292f", fg="#51a0cf", }, -- lualine_x_filetype_DevIconLua_replace xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_command       { bg="#18292f", fg="#51a0cf", }, -- lualine_x_filetype_DevIconLua_command xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_terminal      { bg="#18292f", fg="#51a0cf", }, -- lualine_x_filetype_DevIconLua_terminal xxx guifg=#51a0cf guibg=#18292f
    lualine_x_filetype_DevIconLua_inactive      { bg="#18292f", fg="#51a0cf", }, -- lualine_x_filetype_DevIconLua_inactive xxx guifg=#51a0cf guibg=#18292f
  }
end)
return theme
